// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="yolo_yolo_top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=5440,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=2,HLS_SYN_FF=3614,HLS_SYN_LUT=2900,HLS_VERSION=2019_2}" *)

module yolo_yolo_top (
        ap_clk,
        ap_rst_n,
        inStream_TDATA,
        inStream_TVALID,
        inStream_TREADY,
        inStream_TKEEP,
        inStream_TSTRB,
        inStream_TUSER,
        inStream_TLAST,
        inStream_TID,
        inStream_TDEST,
        outStream_TDATA,
        outStream_TVALID,
        outStream_TREADY,
        outStream_TKEEP,
        outStream_TSTRB,
        outStream_TUSER,
        outStream_TLAST,
        outStream_TID,
        outStream_TDEST,
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_pp0_stage0 = 6'd2;
parameter    ap_ST_fsm_pp0_stage1 = 6'd4;
parameter    ap_ST_fsm_pp0_stage2 = 6'd8;
parameter    ap_ST_fsm_pp0_stage3 = 6'd16;
parameter    ap_ST_fsm_state37 = 6'd32;
parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] inStream_TDATA;
input   inStream_TVALID;
output   inStream_TREADY;
input  [7:0] inStream_TKEEP;
input  [7:0] inStream_TSTRB;
input  [1:0] inStream_TUSER;
input  [0:0] inStream_TLAST;
input  [4:0] inStream_TID;
input  [5:0] inStream_TDEST;
output  [63:0] outStream_TDATA;
output   outStream_TVALID;
input   outStream_TREADY;
output  [7:0] outStream_TKEEP;
output  [7:0] outStream_TSTRB;
output  [1:0] outStream_TUSER;
output  [0:0] outStream_TLAST;
output  [4:0] outStream_TID;
output  [5:0] outStream_TDEST;
input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
output   interrupt;

reg inStream_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] activate_en_V;
wire   [4:0] input_h_V;
wire   [4:0] input_w_V;
reg    inStream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln14_reg_806;
reg    outStream_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter8;
reg   [0:0] icmp_ln14_reg_806_pp0_iter8_reg;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg   [12:0] indvar_flatten17_reg_209;
reg   [4:0] i_op_assign_reg_220;
reg   [8:0] indvar_flatten_reg_232;
reg   [4:0] i_op_assign_1_reg_243;
reg   [3:0] input_ch_idx_0_reg_254;
reg   [15:0] tmp_data_sub_data_0_s_reg_265;
reg   [15:0] tmp_data_sub_data_1_s_reg_275;
reg   [31:0] activate_en_V_read_reg_767;
wire   [5:0] add_ln1354_fu_341_p2;
reg   [5:0] add_ln1354_reg_774;
wire   [5:0] add_ln1354_1_fu_351_p2;
reg   [5:0] add_ln1354_1_reg_780;
wire   [28:0] trunc_ln791_fu_357_p1;
reg   [28:0] trunc_ln791_reg_786;
wire   [8:0] bound_fu_369_p1;
reg   [8:0] bound_reg_791;
wire   [12:0] bound4_fu_381_p2;
reg   [12:0] bound4_reg_796;
wire   [0:0] icmp_ln56_3_fu_387_p2;
reg   [0:0] icmp_ln56_3_reg_801;
wire   [0:0] icmp_ln14_fu_417_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state10_pp0_stage0_iter2;
wire    ap_block_state14_pp0_stage0_iter3;
wire    ap_block_state18_pp0_stage0_iter4;
wire    ap_block_state22_pp0_stage0_iter5;
wire    ap_block_state26_pp0_stage0_iter6;
wire    ap_block_state30_pp0_stage0_iter7;
wire    ap_block_state34_pp0_stage0_iter8;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln14_reg_806_pp0_iter1_reg;
reg   [0:0] icmp_ln14_reg_806_pp0_iter2_reg;
reg   [0:0] icmp_ln14_reg_806_pp0_iter3_reg;
reg   [0:0] icmp_ln14_reg_806_pp0_iter4_reg;
reg   [0:0] icmp_ln14_reg_806_pp0_iter5_reg;
reg   [0:0] icmp_ln14_reg_806_pp0_iter6_reg;
reg   [0:0] icmp_ln14_reg_806_pp0_iter7_reg;
wire   [12:0] add_ln14_fu_422_p2;
reg   [12:0] add_ln14_reg_810;
wire   [0:0] icmp_ln17_fu_428_p2;
reg   [0:0] icmp_ln17_reg_815;
wire   [4:0] select_ln1598_fu_433_p3;
reg   [4:0] select_ln1598_reg_821;
wire   [4:0] add_ln14_1_fu_441_p2;
reg   [4:0] add_ln14_1_reg_826;
wire   [0:0] and_ln1598_fu_489_p2;
reg   [0:0] and_ln1598_reg_831;
wire   [4:0] col_idx_fu_495_p2;
reg   [4:0] col_idx_reg_836;
wire   [3:0] select_ln1598_3_fu_507_p3;
reg   [3:0] select_ln1598_3_reg_841;
wire   [4:0] bvh_d_index_fu_542_p3;
reg   [4:0] bvh_d_index_reg_846;
wire   [0:0] p_Result_s_fu_565_p2;
reg   [0:0] p_Result_s_reg_853;
reg   [0:0] p_Result_s_reg_853_pp0_iter1_reg;
reg   [0:0] p_Result_s_reg_853_pp0_iter2_reg;
reg   [0:0] p_Result_s_reg_853_pp0_iter3_reg;
reg   [0:0] p_Result_s_reg_853_pp0_iter4_reg;
reg   [0:0] p_Result_s_reg_853_pp0_iter5_reg;
reg   [0:0] p_Result_s_reg_853_pp0_iter6_reg;
reg   [0:0] p_Result_s_reg_853_pp0_iter7_reg;
wire   [0:0] tmp_last_V_fu_583_p2;
reg   [0:0] tmp_last_V_reg_857;
reg   [0:0] tmp_last_V_reg_857_pp0_iter1_reg;
reg   [0:0] tmp_last_V_reg_857_pp0_iter2_reg;
reg   [0:0] tmp_last_V_reg_857_pp0_iter3_reg;
reg   [0:0] tmp_last_V_reg_857_pp0_iter4_reg;
reg   [0:0] tmp_last_V_reg_857_pp0_iter5_reg;
reg   [0:0] tmp_last_V_reg_857_pp0_iter6_reg;
reg   [0:0] tmp_last_V_reg_857_pp0_iter7_reg;
reg   [0:0] tmp_last_V_reg_857_pp0_iter8_reg;
wire   [8:0] add_ln17_fu_589_p2;
reg   [8:0] add_ln17_reg_862;
reg   [7:0] tmp_keep_V_reg_867;
reg    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_block_state11_pp0_stage1_iter2;
wire    ap_block_state15_pp0_stage1_iter3;
wire    ap_block_state19_pp0_stage1_iter4;
wire    ap_block_state23_pp0_stage1_iter5;
wire    ap_block_state27_pp0_stage1_iter6;
wire    ap_block_state31_pp0_stage1_iter7;
wire    ap_block_state35_pp0_stage1_iter8;
reg    ap_block_state35_io;
reg    ap_block_pp0_stage1_11001;
reg   [7:0] tmp_keep_V_reg_867_pp0_iter1_reg;
reg   [7:0] tmp_keep_V_reg_867_pp0_iter2_reg;
reg   [7:0] tmp_keep_V_reg_867_pp0_iter3_reg;
reg   [7:0] tmp_keep_V_reg_867_pp0_iter4_reg;
reg   [7:0] tmp_keep_V_reg_867_pp0_iter5_reg;
reg   [7:0] tmp_keep_V_reg_867_pp0_iter6_reg;
reg   [7:0] tmp_keep_V_reg_867_pp0_iter7_reg;
reg   [7:0] tmp_strb_V_reg_872;
reg   [7:0] tmp_strb_V_reg_872_pp0_iter1_reg;
reg   [7:0] tmp_strb_V_reg_872_pp0_iter2_reg;
reg   [7:0] tmp_strb_V_reg_872_pp0_iter3_reg;
reg   [7:0] tmp_strb_V_reg_872_pp0_iter4_reg;
reg   [7:0] tmp_strb_V_reg_872_pp0_iter5_reg;
reg   [7:0] tmp_strb_V_reg_872_pp0_iter6_reg;
reg   [7:0] tmp_strb_V_reg_872_pp0_iter7_reg;
reg   [1:0] tmp_user_V_reg_877;
reg   [1:0] tmp_user_V_reg_877_pp0_iter1_reg;
reg   [1:0] tmp_user_V_reg_877_pp0_iter2_reg;
reg   [1:0] tmp_user_V_reg_877_pp0_iter3_reg;
reg   [1:0] tmp_user_V_reg_877_pp0_iter4_reg;
reg   [1:0] tmp_user_V_reg_877_pp0_iter5_reg;
reg   [1:0] tmp_user_V_reg_877_pp0_iter6_reg;
reg   [1:0] tmp_user_V_reg_877_pp0_iter7_reg;
reg   [4:0] tmp_id_V_reg_882;
reg   [4:0] tmp_id_V_reg_882_pp0_iter1_reg;
reg   [4:0] tmp_id_V_reg_882_pp0_iter2_reg;
reg   [4:0] tmp_id_V_reg_882_pp0_iter3_reg;
reg   [4:0] tmp_id_V_reg_882_pp0_iter4_reg;
reg   [4:0] tmp_id_V_reg_882_pp0_iter5_reg;
reg   [4:0] tmp_id_V_reg_882_pp0_iter6_reg;
reg   [4:0] tmp_id_V_reg_882_pp0_iter7_reg;
reg   [5:0] tmp_dest_V_reg_887;
reg   [5:0] tmp_dest_V_reg_887_pp0_iter1_reg;
reg   [5:0] tmp_dest_V_reg_887_pp0_iter2_reg;
reg   [5:0] tmp_dest_V_reg_887_pp0_iter3_reg;
reg   [5:0] tmp_dest_V_reg_887_pp0_iter4_reg;
reg   [5:0] tmp_dest_V_reg_887_pp0_iter5_reg;
reg   [5:0] tmp_dest_V_reg_887_pp0_iter6_reg;
reg   [5:0] tmp_dest_V_reg_887_pp0_iter7_reg;
wire   [15:0] trunc_ln203_fu_619_p1;
reg   [15:0] p_02_new_reg_898;
reg   [15:0] p_01_new_reg_904;
reg   [15:0] p_0_new_reg_910;
wire   [0:0] p_Result_1_fu_674_p2;
reg   [0:0] p_Result_1_reg_916;
reg   [0:0] p_Result_1_reg_916_pp0_iter1_reg;
reg   [0:0] p_Result_1_reg_916_pp0_iter2_reg;
reg   [0:0] p_Result_1_reg_916_pp0_iter3_reg;
reg   [0:0] p_Result_1_reg_916_pp0_iter4_reg;
reg   [0:0] p_Result_1_reg_916_pp0_iter5_reg;
reg   [0:0] p_Result_1_reg_916_pp0_iter6_reg;
reg   [0:0] p_Result_1_reg_916_pp0_iter7_reg;
wire   [0:0] p_Result_2_fu_700_p2;
reg   [0:0] p_Result_2_reg_920;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_block_state12_pp0_stage2_iter2;
wire    ap_block_state16_pp0_stage2_iter3;
wire    ap_block_state20_pp0_stage2_iter4;
wire    ap_block_state24_pp0_stage2_iter5;
wire    ap_block_state28_pp0_stage2_iter6;
wire    ap_block_state32_pp0_stage2_iter7;
wire    ap_block_state36_pp0_stage2_iter8;
reg    ap_block_state36_io;
reg    ap_block_pp0_stage2_11001;
reg   [0:0] p_Result_2_reg_920_pp0_iter1_reg;
reg   [0:0] p_Result_2_reg_920_pp0_iter2_reg;
reg   [0:0] p_Result_2_reg_920_pp0_iter3_reg;
reg   [0:0] p_Result_2_reg_920_pp0_iter4_reg;
reg   [0:0] p_Result_2_reg_920_pp0_iter5_reg;
reg   [0:0] p_Result_2_reg_920_pp0_iter6_reg;
reg   [0:0] p_Result_2_reg_920_pp0_iter7_reg;
wire   [4:0] select_ln14_fu_706_p3;
reg   [4:0] select_ln14_reg_924;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state5_pp0_stage3_iter0;
wire    ap_block_state9_pp0_stage3_iter1;
wire    ap_block_state13_pp0_stage3_iter2;
wire    ap_block_state17_pp0_stage3_iter3;
wire    ap_block_state21_pp0_stage3_iter4;
wire    ap_block_state25_pp0_stage3_iter5;
wire    ap_block_state29_pp0_stage3_iter6;
wire    ap_block_state33_pp0_stage3_iter7;
wire    ap_block_pp0_stage3_11001;
wire   [4:0] select_ln17_fu_712_p3;
reg   [4:0] select_ln17_reg_929;
wire   [0:0] p_Result_3_fu_737_p2;
reg   [0:0] p_Result_3_reg_934;
reg   [0:0] p_Result_3_reg_934_pp0_iter1_reg;
reg   [0:0] p_Result_3_reg_934_pp0_iter2_reg;
reg   [0:0] p_Result_3_reg_934_pp0_iter3_reg;
reg   [0:0] p_Result_3_reg_934_pp0_iter4_reg;
reg   [0:0] p_Result_3_reg_934_pp0_iter5_reg;
reg   [0:0] p_Result_3_reg_934_pp0_iter6_reg;
reg   [0:0] p_Result_3_reg_934_pp0_iter7_reg;
wire   [3:0] input_ch_idx_fu_743_p2;
reg   [3:0] input_ch_idx_reg_938;
wire   [8:0] select_ln17_1_fu_748_p3;
reg   [8:0] select_ln17_1_reg_943;
wire   [15:0] grp_logistic_activate_fu_303_ap_return;
reg   [15:0] op_V_assign_reg_948;
reg    ap_enable_reg_pp0_iter7;
reg   [15:0] op_V_assign_1_reg_953;
reg   [15:0] op_V_assign_2_reg_958;
reg   [15:0] op_V_assign_3_reg_963;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
wire    grp_logistic_activate_fu_303_ap_start;
wire    grp_logistic_activate_fu_303_ap_done;
wire    grp_logistic_activate_fu_303_ap_idle;
wire    grp_logistic_activate_fu_303_ap_ready;
reg    grp_logistic_activate_fu_303_ap_ce;
reg   [15:0] grp_logistic_activate_fu_303_val_in_V;
reg    ap_predicate_op130_call_state3;
reg    ap_predicate_op138_call_state4;
reg    ap_predicate_op149_call_state5;
reg    ap_predicate_op161_call_state6;
reg    ap_block_state3_pp0_stage1_iter0_ignore_call0;
wire    ap_block_state7_pp0_stage1_iter1_ignore_call0;
wire    ap_block_state11_pp0_stage1_iter2_ignore_call0;
wire    ap_block_state15_pp0_stage1_iter3_ignore_call0;
wire    ap_block_state19_pp0_stage1_iter4_ignore_call0;
wire    ap_block_state23_pp0_stage1_iter5_ignore_call0;
wire    ap_block_state27_pp0_stage1_iter6_ignore_call0;
wire    ap_block_state31_pp0_stage1_iter7_ignore_call0;
wire    ap_block_state35_pp0_stage1_iter8_ignore_call0;
reg    ap_block_pp0_stage1_11001_ignoreCallOp130;
wire    ap_block_state4_pp0_stage2_iter0_ignore_call0;
wire    ap_block_state8_pp0_stage2_iter1_ignore_call0;
wire    ap_block_state12_pp0_stage2_iter2_ignore_call0;
wire    ap_block_state16_pp0_stage2_iter3_ignore_call0;
wire    ap_block_state20_pp0_stage2_iter4_ignore_call0;
wire    ap_block_state24_pp0_stage2_iter5_ignore_call0;
wire    ap_block_state28_pp0_stage2_iter6_ignore_call0;
wire    ap_block_state32_pp0_stage2_iter7_ignore_call0;
wire    ap_block_state36_pp0_stage2_iter8_ignore_call0;
reg    ap_block_pp0_stage2_11001_ignoreCallOp137;
wire    ap_block_state5_pp0_stage3_iter0_ignore_call0;
wire    ap_block_state9_pp0_stage3_iter1_ignore_call0;
wire    ap_block_state13_pp0_stage3_iter2_ignore_call0;
wire    ap_block_state17_pp0_stage3_iter3_ignore_call0;
wire    ap_block_state21_pp0_stage3_iter4_ignore_call0;
wire    ap_block_state25_pp0_stage3_iter5_ignore_call0;
wire    ap_block_state29_pp0_stage3_iter6_ignore_call0;
wire    ap_block_state33_pp0_stage3_iter7_ignore_call0;
wire    ap_block_pp0_stage3_11001_ignoreCallOp147;
wire    ap_block_state2_pp0_stage0_iter0_ignore_call0;
wire    ap_block_state6_pp0_stage0_iter1_ignore_call0;
wire    ap_block_state10_pp0_stage0_iter2_ignore_call0;
wire    ap_block_state14_pp0_stage0_iter3_ignore_call0;
wire    ap_block_state18_pp0_stage0_iter4_ignore_call0;
wire    ap_block_state22_pp0_stage0_iter5_ignore_call0;
wire    ap_block_state26_pp0_stage0_iter6_ignore_call0;
wire    ap_block_state30_pp0_stage0_iter7_ignore_call0;
wire    ap_block_state34_pp0_stage0_iter8_ignore_call0;
wire    ap_block_pp0_stage0_11001_ignoreCallOp158;
reg   [12:0] ap_phi_mux_indvar_flatten17_phi_fu_213_p4;
wire    ap_block_pp0_stage0;
reg   [4:0] ap_phi_mux_i_op_assign_phi_fu_224_p4;
reg   [8:0] ap_phi_mux_indvar_flatten_phi_fu_236_p4;
reg   [4:0] ap_phi_mux_i_op_assign_1_phi_fu_247_p4;
reg   [3:0] ap_phi_mux_input_ch_idx_0_phi_fu_258_p4;
reg   [15:0] ap_phi_reg_pp0_iter0_tmp_data_sub_data_0_s_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_data_sub_data_0_s_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter3_tmp_data_sub_data_0_s_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter4_tmp_data_sub_data_0_s_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter5_tmp_data_sub_data_0_s_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter6_tmp_data_sub_data_0_s_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter7_tmp_data_sub_data_0_s_reg_265;
reg   [15:0] ap_phi_reg_pp0_iter0_tmp_data_sub_data_1_s_reg_275;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_data_sub_data_1_s_reg_275;
reg   [15:0] ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_275;
reg   [15:0] ap_phi_reg_pp0_iter3_tmp_data_sub_data_1_s_reg_275;
reg   [15:0] ap_phi_reg_pp0_iter4_tmp_data_sub_data_1_s_reg_275;
reg   [15:0] ap_phi_reg_pp0_iter5_tmp_data_sub_data_1_s_reg_275;
reg   [15:0] ap_phi_reg_pp0_iter6_tmp_data_sub_data_1_s_reg_275;
reg   [15:0] ap_phi_reg_pp0_iter7_tmp_data_sub_data_1_s_reg_275;
reg   [15:0] ap_phi_reg_pp0_iter8_tmp_data_sub_data_1_s_reg_275;
reg   [15:0] ap_phi_reg_pp0_iter0_tmp_data_sub_data_2_s_reg_285;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_data_sub_data_2_s_reg_285;
reg   [15:0] ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_285;
reg   [15:0] ap_phi_reg_pp0_iter3_tmp_data_sub_data_2_s_reg_285;
reg   [15:0] ap_phi_reg_pp0_iter4_tmp_data_sub_data_2_s_reg_285;
reg   [15:0] ap_phi_reg_pp0_iter5_tmp_data_sub_data_2_s_reg_285;
reg   [15:0] ap_phi_reg_pp0_iter6_tmp_data_sub_data_2_s_reg_285;
reg   [15:0] ap_phi_reg_pp0_iter7_tmp_data_sub_data_2_s_reg_285;
reg   [15:0] ap_phi_reg_pp0_iter8_tmp_data_sub_data_2_s_reg_285;
reg   [15:0] ap_phi_mux_tmp_data_sub_data_3_s_phi_fu_297_p4;
reg   [15:0] ap_phi_reg_pp0_iter8_tmp_data_sub_data_3_s_reg_294;
wire   [15:0] ap_phi_reg_pp0_iter0_tmp_data_sub_data_3_s_reg_294;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_data_sub_data_3_s_reg_294;
reg   [15:0] ap_phi_reg_pp0_iter2_tmp_data_sub_data_3_s_reg_294;
reg   [15:0] ap_phi_reg_pp0_iter3_tmp_data_sub_data_3_s_reg_294;
reg   [15:0] ap_phi_reg_pp0_iter4_tmp_data_sub_data_3_s_reg_294;
reg   [15:0] ap_phi_reg_pp0_iter5_tmp_data_sub_data_3_s_reg_294;
reg   [15:0] ap_phi_reg_pp0_iter6_tmp_data_sub_data_3_s_reg_294;
reg   [15:0] ap_phi_reg_pp0_iter7_tmp_data_sub_data_3_s_reg_294;
reg    grp_logistic_activate_fu_303_ap_start_reg;
reg    ap_predicate_op130_call_state3_state2;
reg    ap_predicate_op138_call_state4_state3;
reg    ap_predicate_op149_call_state5_state4;
reg    ap_predicate_op161_call_state6_state5;
wire    ap_block_pp0_stage3;
reg    ap_block_pp0_stage1_01001;
wire   [5:0] zext_ln1354_fu_337_p1;
wire   [5:0] zext_ln1354_1_fu_347_p1;
wire   [7:0] tmp_fu_361_p3;
wire   [7:0] bound4_fu_381_p0;
wire   [4:0] bound4_fu_381_p1;
wire   [5:0] zext_ln17_fu_393_p1;
wire   [5:0] zext_ln20_fu_402_p1;
wire   [0:0] icmp_ln56_1_fu_406_p2;
wire   [0:0] icmp_ln56_2_fu_397_p2;
wire   [5:0] zext_ln17_1_fu_447_p1;
wire   [0:0] icmp_ln56_4_fu_451_p2;
wire   [0:0] or_ln56_2_fu_464_p2;
wire   [0:0] or_ln56_fu_411_p2;
wire   [0:0] icmp_ln20_fu_483_p2;
wire   [0:0] xor_ln1598_fu_477_p2;
wire   [0:0] or_ln1598_fu_501_p2;
wire   [5:0] zext_ln20_1_fu_515_p1;
wire   [0:0] icmp_ln56_5_fu_519_p2;
wire   [0:0] select_ln1598_1_fu_456_p3;
wire   [0:0] or_ln56_3_fu_524_p2;
wire   [0:0] select_ln1598_2_fu_469_p3;
wire   [2:0] trunc_ln31_fu_538_p1;
wire   [28:0] zext_ln31_fu_550_p1;
wire   [28:0] shl_ln791_fu_554_p2;
wire   [28:0] and_ln791_fu_560_p2;
wire   [0:0] select_ln1598_4_fu_530_p3;
wire   [0:0] icmp_ln56_fu_571_p2;
wire   [0:0] or_ln56_1_fu_577_p2;
wire   [4:0] bvh_d_index_1_fu_654_p2;
wire   [31:0] zext_ln36_fu_659_p1;
wire   [31:0] shl_ln791_1_fu_663_p2;
wire   [31:0] and_ln791_1_fu_669_p2;
wire   [4:0] bvh_d_index_2_fu_680_p2;
wire   [31:0] zext_ln41_fu_685_p1;
wire   [31:0] shl_ln791_2_fu_689_p2;
wire   [31:0] and_ln791_2_fu_695_p2;
wire   [4:0] bvh_d_index_3_fu_717_p2;
wire   [31:0] zext_ln46_fu_722_p1;
wire   [31:0] shl_ln791_3_fu_726_p2;
wire   [31:0] and_ln791_3_fu_732_p2;
wire    ap_CS_fsm_state37;
wire    regslice_both_outStream_V_data_U_apdone_blk;
reg   [5:0] ap_NS_fsm;
reg    ap_block_pp0_stage1_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_inStream_V_data_U_apdone_blk;
wire   [63:0] inStream_TDATA_int;
wire    inStream_TVALID_int;
reg    inStream_TREADY_int;
wire    regslice_both_inStream_V_data_U_ack_in;
wire    regslice_both_inStream_V_keep_V_U_apdone_blk;
wire   [7:0] inStream_TKEEP_int;
wire    regslice_both_inStream_V_keep_V_U_vld_out;
wire    regslice_both_inStream_V_keep_V_U_ack_in;
wire    regslice_both_inStream_V_strb_V_U_apdone_blk;
wire   [7:0] inStream_TSTRB_int;
wire    regslice_both_inStream_V_strb_V_U_vld_out;
wire    regslice_both_inStream_V_strb_V_U_ack_in;
wire    regslice_both_inStream_V_user_V_U_apdone_blk;
wire   [1:0] inStream_TUSER_int;
wire    regslice_both_inStream_V_user_V_U_vld_out;
wire    regslice_both_inStream_V_user_V_U_ack_in;
wire    regslice_both_inStream_V_last_V_U_apdone_blk;
wire   [0:0] inStream_TLAST_int;
wire    regslice_both_inStream_V_last_V_U_vld_out;
wire    regslice_both_inStream_V_last_V_U_ack_in;
wire    regslice_both_inStream_V_id_V_U_apdone_blk;
wire   [4:0] inStream_TID_int;
wire    regslice_both_inStream_V_id_V_U_vld_out;
wire    regslice_both_inStream_V_id_V_U_ack_in;
wire    regslice_both_inStream_V_dest_V_U_apdone_blk;
wire   [5:0] inStream_TDEST_int;
wire    regslice_both_inStream_V_dest_V_U_vld_out;
wire    regslice_both_inStream_V_dest_V_U_ack_in;
wire   [63:0] outStream_TDATA_int;
reg    outStream_TVALID_int;
wire    outStream_TREADY_int;
wire    regslice_both_outStream_V_data_U_vld_out;
wire    regslice_both_outStream_V_keep_V_U_apdone_blk;
wire    regslice_both_outStream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_keep_V_U_vld_out;
wire    regslice_both_outStream_V_strb_V_U_apdone_blk;
wire    regslice_both_outStream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_strb_V_U_vld_out;
wire    regslice_both_outStream_V_user_V_U_apdone_blk;
wire    regslice_both_outStream_V_user_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_user_V_U_vld_out;
wire    regslice_both_outStream_V_last_V_U_apdone_blk;
wire    regslice_both_outStream_V_last_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_last_V_U_vld_out;
wire    regslice_both_outStream_V_id_V_U_apdone_blk;
wire    regslice_both_outStream_V_id_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_id_V_U_vld_out;
wire    regslice_both_outStream_V_dest_V_U_apdone_blk;
wire    regslice_both_outStream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_dest_V_U_vld_out;
wire   [12:0] bound4_fu_381_p00;
wire   [12:0] bound4_fu_381_p10;
reg    ap_condition_371;
reg    ap_condition_409;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 grp_logistic_activate_fu_303_ap_start_reg = 1'b0;
end

yolo_yolo_top_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
yolo_yolo_top_CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .activate_en_V(activate_en_V),
    .input_h_V(input_h_V),
    .input_w_V(input_w_V)
);

logistic_activate grp_logistic_activate_fu_303(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_logistic_activate_fu_303_ap_start),
    .ap_done(grp_logistic_activate_fu_303_ap_done),
    .ap_idle(grp_logistic_activate_fu_303_ap_idle),
    .ap_ready(grp_logistic_activate_fu_303_ap_ready),
    .ap_ce(grp_logistic_activate_fu_303_ap_ce),
    .val_in_V(grp_logistic_activate_fu_303_val_in_V),
    .ap_return(grp_logistic_activate_fu_303_ap_return)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_inStream_V_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TDATA),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_data_U_ack_in),
    .data_out(inStream_TDATA_int),
    .vld_out(inStream_TVALID_int),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_data_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_inStream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TKEEP),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_keep_V_U_ack_in),
    .data_out(inStream_TKEEP_int),
    .vld_out(regslice_both_inStream_V_keep_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_inStream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TSTRB),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_strb_V_U_ack_in),
    .data_out(inStream_TSTRB_int),
    .vld_out(regslice_both_inStream_V_strb_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 2 ))
regslice_both_inStream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TUSER),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_user_V_U_ack_in),
    .data_out(inStream_TUSER_int),
    .vld_out(regslice_both_inStream_V_user_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TLAST),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_last_V_U_ack_in),
    .data_out(inStream_TLAST_int),
    .vld_out(regslice_both_inStream_V_last_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 5 ))
regslice_both_inStream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TID),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_id_V_U_ack_in),
    .data_out(inStream_TID_int),
    .vld_out(regslice_both_inStream_V_id_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 6 ))
regslice_both_inStream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TDEST),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_dest_V_U_ack_in),
    .data_out(inStream_TDEST_int),
    .vld_out(regslice_both_inStream_V_dest_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_dest_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_outStream_V_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(outStream_TDATA_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(outStream_TREADY_int),
    .data_out(outStream_TDATA),
    .vld_out(regslice_both_outStream_V_data_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_data_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_outStream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_keep_V_reg_867_pp0_iter7_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_keep_V_U_ack_in_dummy),
    .data_out(outStream_TKEEP),
    .vld_out(regslice_both_outStream_V_keep_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_outStream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_strb_V_reg_872_pp0_iter7_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_strb_V_U_ack_in_dummy),
    .data_out(outStream_TSTRB),
    .vld_out(regslice_both_outStream_V_strb_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 2 ))
regslice_both_outStream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_user_V_reg_877_pp0_iter7_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_user_V_U_ack_in_dummy),
    .data_out(outStream_TUSER),
    .vld_out(regslice_both_outStream_V_user_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_outStream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_last_V_reg_857_pp0_iter8_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_last_V_U_ack_in_dummy),
    .data_out(outStream_TLAST),
    .vld_out(regslice_both_outStream_V_last_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 5 ))
regslice_both_outStream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_id_V_reg_882_pp0_iter7_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_id_V_U_ack_in_dummy),
    .data_out(outStream_TID),
    .vld_out(regslice_both_outStream_V_id_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 6 ))
regslice_both_outStream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_dest_V_reg_887_pp0_iter7_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_dest_V_U_ack_in_dummy),
    .data_out(outStream_TDEST),
    .vld_out(regslice_both_outStream_V_dest_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter8 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_logistic_activate_fu_303_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op149_call_state5_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op161_call_state6_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_predicate_op130_call_state3_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op138_call_state4_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            grp_logistic_activate_fu_303_ap_start_reg <= 1'b1;
        end else if ((grp_logistic_activate_fu_303_ap_ready == 1'b1)) begin
            grp_logistic_activate_fu_303_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_371)) begin
        if (((icmp_ln14_reg_806 == 1'd0) & (p_Result_3_fu_737_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_tmp_data_sub_data_3_s_reg_294 <= p_0_new_reg_910;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_data_sub_data_3_s_reg_294 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_3_s_reg_294;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_s_reg_853_pp0_iter7_reg == 1'd0) & (icmp_ln14_reg_806_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_phi_reg_pp0_iter7_tmp_data_sub_data_0_s_reg_265 <= op_V_assign_reg_948;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter7_tmp_data_sub_data_0_s_reg_265 <= ap_phi_reg_pp0_iter6_tmp_data_sub_data_0_s_reg_265;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_409)) begin
        if (((p_Result_1_reg_916_pp0_iter7_reg == 1'd0) & (icmp_ln14_reg_806_pp0_iter7_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter8_tmp_data_sub_data_1_s_reg_275 <= op_V_assign_1_reg_953;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter8_tmp_data_sub_data_1_s_reg_275 <= ap_phi_reg_pp0_iter7_tmp_data_sub_data_1_s_reg_275;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_2_reg_920_pp0_iter7_reg == 1'd0) & (icmp_ln14_reg_806_pp0_iter7_reg == 1'd0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_tmp_data_sub_data_2_s_reg_285 <= op_V_assign_2_reg_958;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter8_tmp_data_sub_data_2_s_reg_285 <= ap_phi_reg_pp0_iter7_tmp_data_sub_data_2_s_reg_285;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_op_assign_1_reg_243 <= select_ln17_reg_929;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_op_assign_1_reg_243 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_op_assign_reg_220 <= select_ln14_reg_924;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_op_assign_reg_220 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten17_reg_209 <= add_ln14_reg_810;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten17_reg_209 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_232 <= select_ln17_1_reg_943;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_232 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_ch_idx_0_reg_254 <= input_ch_idx_reg_938;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        input_ch_idx_0_reg_254 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        activate_en_V_read_reg_767 <= activate_en_V;
        add_ln1354_1_reg_780 <= add_ln1354_1_fu_351_p2;
        add_ln1354_reg_774 <= add_ln1354_fu_341_p2;
        bound4_reg_796 <= bound4_fu_381_p2;
        bound_reg_791[7 : 3] <= bound_fu_369_p1[7 : 3];
        icmp_ln56_3_reg_801 <= icmp_ln56_3_fu_387_p2;
        trunc_ln791_reg_786 <= trunc_ln791_fu_357_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_fu_417_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln14_1_reg_826 <= add_ln14_1_fu_441_p2;
        add_ln17_reg_862 <= add_ln17_fu_589_p2;
        and_ln1598_reg_831 <= and_ln1598_fu_489_p2;
        bvh_d_index_reg_846[4 : 2] <= bvh_d_index_fu_542_p3[4 : 2];
        col_idx_reg_836 <= col_idx_fu_495_p2;
        icmp_ln17_reg_815 <= icmp_ln17_fu_428_p2;
        p_Result_s_reg_853 <= p_Result_s_fu_565_p2;
        select_ln1598_3_reg_841 <= select_ln1598_3_fu_507_p3;
        select_ln1598_reg_821 <= select_ln1598_fu_433_p3;
        tmp_last_V_reg_857 <= tmp_last_V_fu_583_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln14_reg_810 <= add_ln14_fu_422_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (p_Result_s_reg_853 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter0_tmp_data_sub_data_0_s_reg_265 <= trunc_ln203_fu_619_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (p_Result_1_fu_674_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter0_tmp_data_sub_data_1_s_reg_275 <= {{inStream_TDATA_int[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (p_Result_2_fu_700_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_phi_reg_pp0_iter0_tmp_data_sub_data_2_s_reg_285 <= p_01_new_reg_904;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter1_tmp_data_sub_data_0_s_reg_265 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_0_s_reg_265;
        ap_phi_reg_pp0_iter1_tmp_data_sub_data_1_s_reg_275 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_1_s_reg_275;
        ap_phi_reg_pp0_iter1_tmp_data_sub_data_2_s_reg_285 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_2_s_reg_285;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_265 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_0_s_reg_265;
        ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_275 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_1_s_reg_275;
        ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_285 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_2_s_reg_285;
        ap_phi_reg_pp0_iter2_tmp_data_sub_data_3_s_reg_294 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_3_s_reg_294;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter3_tmp_data_sub_data_0_s_reg_265 <= ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_265;
        ap_phi_reg_pp0_iter3_tmp_data_sub_data_1_s_reg_275 <= ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_275;
        ap_phi_reg_pp0_iter3_tmp_data_sub_data_2_s_reg_285 <= ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_285;
        ap_phi_reg_pp0_iter3_tmp_data_sub_data_3_s_reg_294 <= ap_phi_reg_pp0_iter2_tmp_data_sub_data_3_s_reg_294;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter4_tmp_data_sub_data_0_s_reg_265 <= ap_phi_reg_pp0_iter3_tmp_data_sub_data_0_s_reg_265;
        ap_phi_reg_pp0_iter4_tmp_data_sub_data_1_s_reg_275 <= ap_phi_reg_pp0_iter3_tmp_data_sub_data_1_s_reg_275;
        ap_phi_reg_pp0_iter4_tmp_data_sub_data_2_s_reg_285 <= ap_phi_reg_pp0_iter3_tmp_data_sub_data_2_s_reg_285;
        ap_phi_reg_pp0_iter4_tmp_data_sub_data_3_s_reg_294 <= ap_phi_reg_pp0_iter3_tmp_data_sub_data_3_s_reg_294;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter5_tmp_data_sub_data_0_s_reg_265 <= ap_phi_reg_pp0_iter4_tmp_data_sub_data_0_s_reg_265;
        ap_phi_reg_pp0_iter5_tmp_data_sub_data_1_s_reg_275 <= ap_phi_reg_pp0_iter4_tmp_data_sub_data_1_s_reg_275;
        ap_phi_reg_pp0_iter5_tmp_data_sub_data_2_s_reg_285 <= ap_phi_reg_pp0_iter4_tmp_data_sub_data_2_s_reg_285;
        ap_phi_reg_pp0_iter5_tmp_data_sub_data_3_s_reg_294 <= ap_phi_reg_pp0_iter4_tmp_data_sub_data_3_s_reg_294;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter6_tmp_data_sub_data_0_s_reg_265 <= ap_phi_reg_pp0_iter5_tmp_data_sub_data_0_s_reg_265;
        ap_phi_reg_pp0_iter6_tmp_data_sub_data_1_s_reg_275 <= ap_phi_reg_pp0_iter5_tmp_data_sub_data_1_s_reg_275;
        ap_phi_reg_pp0_iter6_tmp_data_sub_data_2_s_reg_285 <= ap_phi_reg_pp0_iter5_tmp_data_sub_data_2_s_reg_285;
        ap_phi_reg_pp0_iter6_tmp_data_sub_data_3_s_reg_294 <= ap_phi_reg_pp0_iter5_tmp_data_sub_data_3_s_reg_294;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter7_tmp_data_sub_data_1_s_reg_275 <= ap_phi_reg_pp0_iter6_tmp_data_sub_data_1_s_reg_275;
        ap_phi_reg_pp0_iter7_tmp_data_sub_data_2_s_reg_285 <= ap_phi_reg_pp0_iter6_tmp_data_sub_data_2_s_reg_285;
        ap_phi_reg_pp0_iter7_tmp_data_sub_data_3_s_reg_294 <= ap_phi_reg_pp0_iter6_tmp_data_sub_data_3_s_reg_294;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter8_tmp_data_sub_data_3_s_reg_294 <= ap_phi_reg_pp0_iter7_tmp_data_sub_data_3_s_reg_294;
        tmp_data_sub_data_0_s_reg_265 <= ap_phi_reg_pp0_iter7_tmp_data_sub_data_0_s_reg_265;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln14_reg_806 <= icmp_ln14_fu_417_p2;
        icmp_ln14_reg_806_pp0_iter1_reg <= icmp_ln14_reg_806;
        icmp_ln14_reg_806_pp0_iter2_reg <= icmp_ln14_reg_806_pp0_iter1_reg;
        icmp_ln14_reg_806_pp0_iter3_reg <= icmp_ln14_reg_806_pp0_iter2_reg;
        icmp_ln14_reg_806_pp0_iter4_reg <= icmp_ln14_reg_806_pp0_iter3_reg;
        icmp_ln14_reg_806_pp0_iter5_reg <= icmp_ln14_reg_806_pp0_iter4_reg;
        icmp_ln14_reg_806_pp0_iter6_reg <= icmp_ln14_reg_806_pp0_iter5_reg;
        icmp_ln14_reg_806_pp0_iter7_reg <= icmp_ln14_reg_806_pp0_iter6_reg;
        icmp_ln14_reg_806_pp0_iter8_reg <= icmp_ln14_reg_806_pp0_iter7_reg;
        p_Result_s_reg_853_pp0_iter1_reg <= p_Result_s_reg_853;
        p_Result_s_reg_853_pp0_iter2_reg <= p_Result_s_reg_853_pp0_iter1_reg;
        p_Result_s_reg_853_pp0_iter3_reg <= p_Result_s_reg_853_pp0_iter2_reg;
        p_Result_s_reg_853_pp0_iter4_reg <= p_Result_s_reg_853_pp0_iter3_reg;
        p_Result_s_reg_853_pp0_iter5_reg <= p_Result_s_reg_853_pp0_iter4_reg;
        p_Result_s_reg_853_pp0_iter6_reg <= p_Result_s_reg_853_pp0_iter5_reg;
        p_Result_s_reg_853_pp0_iter7_reg <= p_Result_s_reg_853_pp0_iter6_reg;
        tmp_last_V_reg_857_pp0_iter1_reg <= tmp_last_V_reg_857;
        tmp_last_V_reg_857_pp0_iter2_reg <= tmp_last_V_reg_857_pp0_iter1_reg;
        tmp_last_V_reg_857_pp0_iter3_reg <= tmp_last_V_reg_857_pp0_iter2_reg;
        tmp_last_V_reg_857_pp0_iter4_reg <= tmp_last_V_reg_857_pp0_iter3_reg;
        tmp_last_V_reg_857_pp0_iter5_reg <= tmp_last_V_reg_857_pp0_iter4_reg;
        tmp_last_V_reg_857_pp0_iter6_reg <= tmp_last_V_reg_857_pp0_iter5_reg;
        tmp_last_V_reg_857_pp0_iter7_reg <= tmp_last_V_reg_857_pp0_iter6_reg;
        tmp_last_V_reg_857_pp0_iter8_reg <= tmp_last_V_reg_857_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        input_ch_idx_reg_938 <= input_ch_idx_fu_743_p2;
        select_ln14_reg_924 <= select_ln14_fu_706_p3;
        select_ln17_1_reg_943 <= select_ln17_1_fu_748_p3;
        select_ln17_reg_929 <= select_ln17_fu_712_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_1_reg_916_pp0_iter7_reg == 1'd0) & (icmp_ln14_reg_806_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        op_V_assign_1_reg_953 <= grp_logistic_activate_fu_303_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_2_reg_920_pp0_iter7_reg == 1'd0) & (icmp_ln14_reg_806_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        op_V_assign_2_reg_958 <= grp_logistic_activate_fu_303_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_3_reg_934_pp0_iter7_reg == 1'd0) & (icmp_ln14_reg_806_pp0_iter7_reg == 1'd0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        op_V_assign_3_reg_963 <= grp_logistic_activate_fu_303_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_s_reg_853_pp0_iter7_reg == 1'd0) & (icmp_ln14_reg_806_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        op_V_assign_reg_948 <= grp_logistic_activate_fu_303_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_01_new_reg_904 <= {{inStream_TDATA_int[47:32]}};
        p_02_new_reg_898 <= {{inStream_TDATA_int[31:16]}};
        p_0_new_reg_910 <= {{inStream_TDATA_int[63:48]}};
        p_Result_1_reg_916 <= p_Result_1_fu_674_p2;
        tmp_dest_V_reg_887 <= inStream_TDEST_int;
        tmp_id_V_reg_882 <= inStream_TID_int;
        tmp_keep_V_reg_867 <= inStream_TKEEP_int;
        tmp_strb_V_reg_872 <= inStream_TSTRB_int;
        tmp_user_V_reg_877 <= inStream_TUSER_int;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_Result_1_reg_916_pp0_iter1_reg <= p_Result_1_reg_916;
        p_Result_1_reg_916_pp0_iter2_reg <= p_Result_1_reg_916_pp0_iter1_reg;
        p_Result_1_reg_916_pp0_iter3_reg <= p_Result_1_reg_916_pp0_iter2_reg;
        p_Result_1_reg_916_pp0_iter4_reg <= p_Result_1_reg_916_pp0_iter3_reg;
        p_Result_1_reg_916_pp0_iter5_reg <= p_Result_1_reg_916_pp0_iter4_reg;
        p_Result_1_reg_916_pp0_iter6_reg <= p_Result_1_reg_916_pp0_iter5_reg;
        p_Result_1_reg_916_pp0_iter7_reg <= p_Result_1_reg_916_pp0_iter6_reg;
        tmp_dest_V_reg_887_pp0_iter1_reg <= tmp_dest_V_reg_887;
        tmp_dest_V_reg_887_pp0_iter2_reg <= tmp_dest_V_reg_887_pp0_iter1_reg;
        tmp_dest_V_reg_887_pp0_iter3_reg <= tmp_dest_V_reg_887_pp0_iter2_reg;
        tmp_dest_V_reg_887_pp0_iter4_reg <= tmp_dest_V_reg_887_pp0_iter3_reg;
        tmp_dest_V_reg_887_pp0_iter5_reg <= tmp_dest_V_reg_887_pp0_iter4_reg;
        tmp_dest_V_reg_887_pp0_iter6_reg <= tmp_dest_V_reg_887_pp0_iter5_reg;
        tmp_dest_V_reg_887_pp0_iter7_reg <= tmp_dest_V_reg_887_pp0_iter6_reg;
        tmp_id_V_reg_882_pp0_iter1_reg <= tmp_id_V_reg_882;
        tmp_id_V_reg_882_pp0_iter2_reg <= tmp_id_V_reg_882_pp0_iter1_reg;
        tmp_id_V_reg_882_pp0_iter3_reg <= tmp_id_V_reg_882_pp0_iter2_reg;
        tmp_id_V_reg_882_pp0_iter4_reg <= tmp_id_V_reg_882_pp0_iter3_reg;
        tmp_id_V_reg_882_pp0_iter5_reg <= tmp_id_V_reg_882_pp0_iter4_reg;
        tmp_id_V_reg_882_pp0_iter6_reg <= tmp_id_V_reg_882_pp0_iter5_reg;
        tmp_id_V_reg_882_pp0_iter7_reg <= tmp_id_V_reg_882_pp0_iter6_reg;
        tmp_keep_V_reg_867_pp0_iter1_reg <= tmp_keep_V_reg_867;
        tmp_keep_V_reg_867_pp0_iter2_reg <= tmp_keep_V_reg_867_pp0_iter1_reg;
        tmp_keep_V_reg_867_pp0_iter3_reg <= tmp_keep_V_reg_867_pp0_iter2_reg;
        tmp_keep_V_reg_867_pp0_iter4_reg <= tmp_keep_V_reg_867_pp0_iter3_reg;
        tmp_keep_V_reg_867_pp0_iter5_reg <= tmp_keep_V_reg_867_pp0_iter4_reg;
        tmp_keep_V_reg_867_pp0_iter6_reg <= tmp_keep_V_reg_867_pp0_iter5_reg;
        tmp_keep_V_reg_867_pp0_iter7_reg <= tmp_keep_V_reg_867_pp0_iter6_reg;
        tmp_strb_V_reg_872_pp0_iter1_reg <= tmp_strb_V_reg_872;
        tmp_strb_V_reg_872_pp0_iter2_reg <= tmp_strb_V_reg_872_pp0_iter1_reg;
        tmp_strb_V_reg_872_pp0_iter3_reg <= tmp_strb_V_reg_872_pp0_iter2_reg;
        tmp_strb_V_reg_872_pp0_iter4_reg <= tmp_strb_V_reg_872_pp0_iter3_reg;
        tmp_strb_V_reg_872_pp0_iter5_reg <= tmp_strb_V_reg_872_pp0_iter4_reg;
        tmp_strb_V_reg_872_pp0_iter6_reg <= tmp_strb_V_reg_872_pp0_iter5_reg;
        tmp_strb_V_reg_872_pp0_iter7_reg <= tmp_strb_V_reg_872_pp0_iter6_reg;
        tmp_user_V_reg_877_pp0_iter1_reg <= tmp_user_V_reg_877;
        tmp_user_V_reg_877_pp0_iter2_reg <= tmp_user_V_reg_877_pp0_iter1_reg;
        tmp_user_V_reg_877_pp0_iter3_reg <= tmp_user_V_reg_877_pp0_iter2_reg;
        tmp_user_V_reg_877_pp0_iter4_reg <= tmp_user_V_reg_877_pp0_iter3_reg;
        tmp_user_V_reg_877_pp0_iter5_reg <= tmp_user_V_reg_877_pp0_iter4_reg;
        tmp_user_V_reg_877_pp0_iter6_reg <= tmp_user_V_reg_877_pp0_iter5_reg;
        tmp_user_V_reg_877_pp0_iter7_reg <= tmp_user_V_reg_877_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_Result_2_reg_920 <= p_Result_2_fu_700_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_Result_2_reg_920_pp0_iter1_reg <= p_Result_2_reg_920;
        p_Result_2_reg_920_pp0_iter2_reg <= p_Result_2_reg_920_pp0_iter1_reg;
        p_Result_2_reg_920_pp0_iter3_reg <= p_Result_2_reg_920_pp0_iter2_reg;
        p_Result_2_reg_920_pp0_iter4_reg <= p_Result_2_reg_920_pp0_iter3_reg;
        p_Result_2_reg_920_pp0_iter5_reg <= p_Result_2_reg_920_pp0_iter4_reg;
        p_Result_2_reg_920_pp0_iter6_reg <= p_Result_2_reg_920_pp0_iter5_reg;
        p_Result_2_reg_920_pp0_iter7_reg <= p_Result_2_reg_920_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_Result_3_reg_934 <= p_Result_3_fu_737_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_Result_3_reg_934_pp0_iter1_reg <= p_Result_3_reg_934;
        p_Result_3_reg_934_pp0_iter2_reg <= p_Result_3_reg_934_pp0_iter1_reg;
        p_Result_3_reg_934_pp0_iter3_reg <= p_Result_3_reg_934_pp0_iter2_reg;
        p_Result_3_reg_934_pp0_iter4_reg <= p_Result_3_reg_934_pp0_iter3_reg;
        p_Result_3_reg_934_pp0_iter5_reg <= p_Result_3_reg_934_pp0_iter4_reg;
        p_Result_3_reg_934_pp0_iter6_reg <= p_Result_3_reg_934_pp0_iter5_reg;
        p_Result_3_reg_934_pp0_iter7_reg <= p_Result_3_reg_934_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_sub_data_1_s_reg_275 <= ap_phi_reg_pp0_iter8_tmp_data_sub_data_1_s_reg_275;
    end
end

always @ (*) begin
    if ((icmp_ln14_fu_417_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) & (regslice_both_outStream_V_data_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_i_op_assign_1_phi_fu_247_p4 = select_ln17_reg_929;
    end else begin
        ap_phi_mux_i_op_assign_1_phi_fu_247_p4 = i_op_assign_1_reg_243;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_i_op_assign_phi_fu_224_p4 = select_ln14_reg_924;
    end else begin
        ap_phi_mux_i_op_assign_phi_fu_224_p4 = i_op_assign_reg_220;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_indvar_flatten17_phi_fu_213_p4 = add_ln14_reg_810;
    end else begin
        ap_phi_mux_indvar_flatten17_phi_fu_213_p4 = indvar_flatten17_reg_209;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_indvar_flatten_phi_fu_236_p4 = select_ln17_1_reg_943;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_236_p4 = indvar_flatten_reg_232;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln14_reg_806 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_input_ch_idx_0_phi_fu_258_p4 = input_ch_idx_reg_938;
    end else begin
        ap_phi_mux_input_ch_idx_0_phi_fu_258_p4 = input_ch_idx_0_reg_254;
    end
end

always @ (*) begin
    if (((icmp_ln14_reg_806_pp0_iter8_reg == 1'd0) & (p_Result_3_reg_934_pp0_iter7_reg == 1'd0))) begin
        ap_phi_mux_tmp_data_sub_data_3_s_phi_fu_297_p4 = op_V_assign_3_reg_963;
    end else begin
        ap_phi_mux_tmp_data_sub_data_3_s_phi_fu_297_p4 = ap_phi_reg_pp0_iter8_tmp_data_sub_data_3_s_reg_294;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) & (regslice_both_outStream_V_data_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp137) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp130) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp147) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp158) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_logistic_activate_fu_303_ap_ce = 1'b1;
    end else begin
        grp_logistic_activate_fu_303_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op161_call_state6 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_logistic_activate_fu_303_val_in_V = p_0_new_reg_910;
    end else if (((ap_predicate_op149_call_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_logistic_activate_fu_303_val_in_V = p_01_new_reg_904;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_predicate_op138_call_state4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_logistic_activate_fu_303_val_in_V = p_02_new_reg_898;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_predicate_op130_call_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_logistic_activate_fu_303_val_in_V = trunc_ln203_fu_619_p1;
    end else begin
        grp_logistic_activate_fu_303_val_in_V = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inStream_TDATA_blk_n = inStream_TVALID_int;
    end else begin
        inStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((inStream_TVALID == 1'b1) & (regslice_both_inStream_V_data_U_ack_in == 1'b1))) begin
        inStream_TREADY = 1'b1;
    end else begin
        inStream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln14_reg_806 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inStream_TREADY_int = 1'b1;
    end else begin
        inStream_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2) & (icmp_ln14_reg_806_pp0_iter8_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((icmp_ln14_reg_806_pp0_iter8_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        outStream_TDATA_blk_n = outStream_TREADY_int;
    end else begin
        outStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln14_reg_806_pp0_iter8_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        outStream_TVALID_int = 1'b1;
    end else begin
        outStream_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln14_fu_417_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln14_fu_417_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((~((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter7 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter8 == 1'b1)) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter7 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_state37 : begin
            if (((1'b1 == ap_CS_fsm_state37) & (regslice_both_outStream_V_data_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1354_1_fu_351_p2 = ($signed(6'd63) + $signed(zext_ln1354_1_fu_347_p1));

assign add_ln1354_fu_341_p2 = ($signed(6'd63) + $signed(zext_ln1354_fu_337_p1));

assign add_ln14_1_fu_441_p2 = (5'd1 + ap_phi_mux_i_op_assign_phi_fu_224_p4);

assign add_ln14_fu_422_p2 = (ap_phi_mux_indvar_flatten17_phi_fu_213_p4 + 13'd1);

assign add_ln17_fu_589_p2 = (ap_phi_mux_indvar_flatten_phi_fu_236_p4 + 9'd1);

assign and_ln1598_fu_489_p2 = (xor_ln1598_fu_477_p2 & icmp_ln20_fu_483_p2);

assign and_ln791_1_fu_669_p2 = (shl_ln791_1_fu_663_p2 & activate_en_V_read_reg_767);

assign and_ln791_2_fu_695_p2 = (shl_ln791_2_fu_689_p2 & activate_en_V_read_reg_767);

assign and_ln791_3_fu_732_p2 = (shl_ln791_3_fu_726_p2 & activate_en_V_read_reg_767);

assign and_ln791_fu_560_p2 = (trunc_ln791_reg_786 & shl_ln791_fu_554_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp158 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((icmp_ln14_reg_806 == 1'd0) & (inStream_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((1'b1 == ap_block_state35_io) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((icmp_ln14_reg_806 == 1'd0) & (inStream_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp130 = (((1'b1 == ap_block_state35_io) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((icmp_ln14_reg_806 == 1'd0) & (inStream_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b1 == ap_block_state35_io) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((icmp_ln14_reg_806 == 1'd0) & (inStream_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((1'b1 == ap_block_state36_io) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_ignoreCallOp137 = ((1'b1 == ap_block_state36_io) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((1'b1 == ap_block_state36_io) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp147 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage1_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage2_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage3_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage1_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage2_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage3_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage1_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage2_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage3_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage1_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage2_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage3_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter6_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage1_iter6_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage2_iter6_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage3_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage3_iter6_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter7_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage1_iter7_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage2_iter7_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage3_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage3_iter7_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter8_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state35_io = ((icmp_ln14_reg_806_pp0_iter8_reg == 1'd0) & (outStream_TREADY_int == 1'b0));
end

assign ap_block_state35_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage1_iter8_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state36_io = ((icmp_ln14_reg_806_pp0_iter8_reg == 1'd0) & (outStream_TREADY_int == 1'b0));
end

assign ap_block_state36_pp0_stage2_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage2_iter8_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0 = ((icmp_ln14_reg_806 == 1'd0) & (inStream_TVALID_int == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0_ignore_call0 = ((icmp_ln14_reg_806 == 1'd0) & (inStream_TVALID_int == 1'b0));
end

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage2_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage3_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_371 = ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_409 = ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_tmp_data_sub_data_3_s_reg_294 = 'bx;

always @ (*) begin
    ap_predicate_op130_call_state3 = ((p_Result_s_reg_853 == 1'd0) & (icmp_ln14_reg_806 == 1'd0));
end

always @ (*) begin
    ap_predicate_op130_call_state3_state2 = ((p_Result_s_fu_565_p2 == 1'd0) & (icmp_ln14_fu_417_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op138_call_state4 = ((p_Result_1_reg_916 == 1'd0) & (icmp_ln14_reg_806 == 1'd0));
end

always @ (*) begin
    ap_predicate_op138_call_state4_state3 = ((p_Result_1_fu_674_p2 == 1'd0) & (icmp_ln14_reg_806 == 1'd0));
end

always @ (*) begin
    ap_predicate_op149_call_state5 = ((p_Result_2_reg_920 == 1'd0) & (icmp_ln14_reg_806 == 1'd0));
end

always @ (*) begin
    ap_predicate_op149_call_state5_state4 = ((p_Result_2_fu_700_p2 == 1'd0) & (icmp_ln14_reg_806 == 1'd0));
end

always @ (*) begin
    ap_predicate_op161_call_state6 = ((p_Result_3_reg_934 == 1'd0) & (icmp_ln14_reg_806 == 1'd0));
end

always @ (*) begin
    ap_predicate_op161_call_state6_state5 = ((p_Result_3_fu_737_p2 == 1'd0) & (icmp_ln14_reg_806 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bound4_fu_381_p0 = bound4_fu_381_p00;

assign bound4_fu_381_p00 = tmp_fu_361_p3;

assign bound4_fu_381_p1 = bound4_fu_381_p10;

assign bound4_fu_381_p10 = input_h_V;

assign bound4_fu_381_p2 = (bound4_fu_381_p0 * bound4_fu_381_p1);

assign bound_fu_369_p1 = tmp_fu_361_p3;

assign bvh_d_index_1_fu_654_p2 = (bvh_d_index_reg_846 | 5'd1);

assign bvh_d_index_2_fu_680_p2 = (bvh_d_index_reg_846 | 5'd2);

assign bvh_d_index_3_fu_717_p2 = (bvh_d_index_reg_846 | 5'd3);

assign bvh_d_index_fu_542_p3 = {{trunc_ln31_fu_538_p1}, {2'd0}};

assign col_idx_fu_495_p2 = (5'd1 + select_ln1598_fu_433_p3);

assign grp_logistic_activate_fu_303_ap_start = grp_logistic_activate_fu_303_ap_start_reg;

assign icmp_ln14_fu_417_p2 = ((ap_phi_mux_indvar_flatten17_phi_fu_213_p4 == bound4_reg_796) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_428_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_236_p4 == bound_reg_791) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_483_p2 = ((ap_phi_mux_input_ch_idx_0_phi_fu_258_p4 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln56_1_fu_406_p2 = ((zext_ln20_fu_402_p1 != add_ln1354_reg_774) ? 1'b1 : 1'b0);

assign icmp_ln56_2_fu_397_p2 = ((zext_ln17_fu_393_p1 != add_ln1354_1_reg_780) ? 1'b1 : 1'b0);

assign icmp_ln56_3_fu_387_p2 = ((add_ln1354_fu_341_p2 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln56_4_fu_451_p2 = ((zext_ln17_1_fu_447_p1 != add_ln1354_1_reg_780) ? 1'b1 : 1'b0);

assign icmp_ln56_5_fu_519_p2 = ((zext_ln20_1_fu_515_p1 != add_ln1354_reg_774) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_571_p2 = ((select_ln1598_3_fu_507_p3 != 4'd7) ? 1'b1 : 1'b0);

assign input_ch_idx_fu_743_p2 = (select_ln1598_3_reg_841 + 4'd1);

assign or_ln1598_fu_501_p2 = (icmp_ln17_fu_428_p2 | and_ln1598_fu_489_p2);

assign or_ln56_1_fu_577_p2 = (select_ln1598_4_fu_530_p3 | icmp_ln56_fu_571_p2);

assign or_ln56_2_fu_464_p2 = (icmp_ln56_4_fu_451_p2 | icmp_ln56_3_reg_801);

assign or_ln56_3_fu_524_p2 = (select_ln1598_1_fu_456_p3 | icmp_ln56_5_fu_519_p2);

assign or_ln56_fu_411_p2 = (icmp_ln56_2_fu_397_p2 | icmp_ln56_1_fu_406_p2);

assign outStream_TDATA_int = {{{{ap_phi_mux_tmp_data_sub_data_3_s_phi_fu_297_p4}, {ap_phi_reg_pp0_iter8_tmp_data_sub_data_2_s_reg_285}}, {tmp_data_sub_data_1_s_reg_275}}, {tmp_data_sub_data_0_s_reg_265}};

assign outStream_TVALID = regslice_both_outStream_V_data_U_vld_out;

assign p_Result_1_fu_674_p2 = ((and_ln791_1_fu_669_p2 == 32'd0) ? 1'b1 : 1'b0);

assign p_Result_2_fu_700_p2 = ((and_ln791_2_fu_695_p2 == 32'd0) ? 1'b1 : 1'b0);

assign p_Result_3_fu_737_p2 = ((and_ln791_3_fu_732_p2 == 32'd0) ? 1'b1 : 1'b0);

assign p_Result_s_fu_565_p2 = ((and_ln791_fu_560_p2 == 29'd0) ? 1'b1 : 1'b0);

assign select_ln14_fu_706_p3 = ((icmp_ln17_reg_815[0:0] === 1'b1) ? add_ln14_1_reg_826 : i_op_assign_reg_220);

assign select_ln1598_1_fu_456_p3 = ((icmp_ln17_fu_428_p2[0:0] === 1'b1) ? icmp_ln56_4_fu_451_p2 : icmp_ln56_2_fu_397_p2);

assign select_ln1598_2_fu_469_p3 = ((icmp_ln17_fu_428_p2[0:0] === 1'b1) ? or_ln56_2_fu_464_p2 : or_ln56_fu_411_p2);

assign select_ln1598_3_fu_507_p3 = ((or_ln1598_fu_501_p2[0:0] === 1'b1) ? 4'd0 : ap_phi_mux_input_ch_idx_0_phi_fu_258_p4);

assign select_ln1598_4_fu_530_p3 = ((and_ln1598_fu_489_p2[0:0] === 1'b1) ? or_ln56_3_fu_524_p2 : select_ln1598_2_fu_469_p3);

assign select_ln1598_fu_433_p3 = ((icmp_ln17_fu_428_p2[0:0] === 1'b1) ? 5'd0 : ap_phi_mux_i_op_assign_1_phi_fu_247_p4);

assign select_ln17_1_fu_748_p3 = ((icmp_ln17_reg_815[0:0] === 1'b1) ? 9'd1 : add_ln17_reg_862);

assign select_ln17_fu_712_p3 = ((and_ln1598_reg_831[0:0] === 1'b1) ? col_idx_reg_836 : select_ln1598_reg_821);

assign shl_ln791_1_fu_663_p2 = 32'd1 << zext_ln36_fu_659_p1;

assign shl_ln791_2_fu_689_p2 = 32'd1 << zext_ln41_fu_685_p1;

assign shl_ln791_3_fu_726_p2 = 32'd1 << zext_ln46_fu_722_p1;

assign shl_ln791_fu_554_p2 = 29'd1 << zext_ln31_fu_550_p1;

assign tmp_fu_361_p3 = {{input_w_V}, {3'd0}};

assign tmp_last_V_fu_583_p2 = (or_ln56_1_fu_577_p2 ^ 1'd1);

assign trunc_ln203_fu_619_p1 = inStream_TDATA_int[15:0];

assign trunc_ln31_fu_538_p1 = select_ln1598_3_fu_507_p3[2:0];

assign trunc_ln791_fu_357_p1 = activate_en_V[28:0];

assign xor_ln1598_fu_477_p2 = (icmp_ln17_fu_428_p2 ^ 1'd1);

assign zext_ln1354_1_fu_347_p1 = input_h_V;

assign zext_ln1354_fu_337_p1 = input_w_V;

assign zext_ln17_1_fu_447_p1 = add_ln14_1_fu_441_p2;

assign zext_ln17_fu_393_p1 = ap_phi_mux_i_op_assign_phi_fu_224_p4;

assign zext_ln20_1_fu_515_p1 = col_idx_fu_495_p2;

assign zext_ln20_fu_402_p1 = ap_phi_mux_i_op_assign_1_phi_fu_247_p4;

assign zext_ln31_fu_550_p1 = bvh_d_index_fu_542_p3;

assign zext_ln36_fu_659_p1 = bvh_d_index_1_fu_654_p2;

assign zext_ln41_fu_685_p1 = bvh_d_index_2_fu_680_p2;

assign zext_ln46_fu_722_p1 = bvh_d_index_3_fu_717_p2;

always @ (posedge ap_clk) begin
    bound_reg_791[2:0] <= 3'b000;
    bound_reg_791[8] <= 1'b0;
    bvh_d_index_reg_846[1:0] <= 2'b00;
end

endmodule //yolo_yolo_top
