// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _window_max_pool_HH_
#define _window_max_pool_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct window_max_pool : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<16> > p_read;
    sc_in< sc_lv<16> > p_read1;
    sc_in< sc_lv<16> > p_read2;
    sc_in< sc_lv<16> > p_read3;
    sc_out< sc_lv<16> > ap_return;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    window_max_pool(sc_module_name name);
    SC_HAS_PROCESS(window_max_pool);

    ~window_max_pool();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<16> > p_read_1_reg_72;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<16> > select_ln160_1_fu_54_p3;
    sc_signal< sc_lv<16> > select_ln160_1_reg_78;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln1494_fu_34_p2;
    sc_signal< sc_lv<16> > select_ln160_fu_40_p3;
    sc_signal< sc_lv<1> > icmp_ln1494_1_fu_48_p2;
    sc_signal< sc_lv<1> > icmp_ln1494_2_fu_62_p2;
    sc_signal< sc_lv<16> > select_ln160_2_fu_66_p3;
    sc_signal< sc_logic > ap_ce_reg;
    sc_signal< sc_lv<16> > ap_return_int_reg;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_return();
    void thread_icmp_ln1494_1_fu_48_p2();
    void thread_icmp_ln1494_2_fu_62_p2();
    void thread_icmp_ln1494_fu_34_p2();
    void thread_select_ln160_1_fu_54_p3();
    void thread_select_ln160_2_fu_66_p3();
    void thread_select_ln160_fu_40_p3();
};

}

using namespace ap_rtl;

#endif
