#include <stdio.h>
#include "group_0_input.h" // This is the file generated by your runall.py

int main() {
    // group_0_input.h contains: short layer_input[...]
    int element_count = sizeof(layer_input) / sizeof(short);
    
    FILE *fp = fopen("input.bin", "wb");
    if (!fp) {
        printf("❌ Error: Could not create input.bin\n");
        return 1;
    }

    // Write the raw shorts directly to binary
    size_t written = fwrite(layer_input, sizeof(short), element_count, fp);
    
    if (written == element_count) {
        printf("✅ Successfully converted group_0_input.h to input.bin (%d elements)\n", element_count);
    }
    
    fclose(fp);
    return 0;
}
