-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yolo_upsamp_top is
generic (
    C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    inStream_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    inStream_TVALID : IN STD_LOGIC;
    inStream_TREADY : OUT STD_LOGIC;
    inStream_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    inStream_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    inStream_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    inStream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    inStream_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    inStream_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    outStream_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    outStream_TVALID : OUT STD_LOGIC;
    outStream_TREADY : IN STD_LOGIC;
    outStream_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
    outStream_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    outStream_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    outStream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    outStream_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    outStream_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0);
    s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of yolo_upsamp_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "yolo_upsamp_top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.211500,HLS_SYN_LAT=5444,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=2,HLS_SYN_FF=541,HLS_SYN_LUT=1022,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv7_D : STD_LOGIC_VECTOR (6 downto 0) := "0001101";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv13_1520 : STD_LOGIC_VECTOR (12 downto 0) := "1010100100000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv10_1A0 : STD_LOGIC_VECTOR (9 downto 0) := "0110100000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv9_D0 : STD_LOGIC_VECTOR (8 downto 0) := "011010000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_D : STD_LOGIC_VECTOR (7 downto 0) := "00001101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal inStream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln15_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_1_fu_956_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal outStream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln15_reg_1311 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_1311_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal icmp_ln15_reg_1311_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten136_reg_387 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_idx_0_reg_398 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten72_reg_409 : STD_LOGIC_VECTOR (9 downto 0);
    signal row_stride_0_reg_420 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten27_reg_431 : STD_LOGIC_VECTOR (8 downto 0);
    signal col_assign_reg_442 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_reg_453 : STD_LOGIC_VECTOR (5 downto 0);
    signal col_stride_0_reg_464 : STD_LOGIC_VECTOR (1 downto 0);
    signal input_ch_idx_0_reg_475 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln9_fu_526_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln627_fu_532_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln10_fu_544_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln627_1_fu_550_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln11_fu_562_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln627_2_fu_568_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln12_fu_580_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln627_3_fu_586_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln12_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op151_read_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state8_io : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state9_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln15_fu_642_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln52_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln52_reg_1320 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_5_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_5_reg_1325 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln15_fu_754_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln17_2_fu_806_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln17_2_reg_1335 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln17_1_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln17_1_reg_1340 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln17_3_fu_846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln17_3_reg_1345 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln17_4_fu_852_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_idx_fu_860_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal col_idx_reg_1355 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln52_4_fu_886_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln52_4_reg_1360 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln21_fu_938_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln21_reg_1366 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln21_1_reg_1372 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_1_reg_1372_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_2_fu_970_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_2_reg_1376 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln21_3_fu_978_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_keep_V_4_reg_1386 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_strb_V_4_reg_1391 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_user_V_4_reg_1396 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_id_V_4_reg_1401 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_dest_V_4_reg_1406 : STD_LOGIC_VECTOR (5 downto 0);
    signal curr_input_data_sub_s_fu_1010_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal curr_input_data_sub_s_reg_1411 : STD_LOGIC_VECTOR (15 downto 0);
    signal curr_input_data_sub_1_reg_1417 : STD_LOGIC_VECTOR (15 downto 0);
    signal curr_input_data_sub_2_reg_1423 : STD_LOGIC_VECTOR (15 downto 0);
    signal curr_input_data_sub_3_reg_1429 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln52_4_fu_1044_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_4_reg_1435 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_ch_idx_fu_1050_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln21_4_fu_1062_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln19_fu_1076_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln17_5_fu_1090_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal curr_output_last_V_fu_1172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal curr_output_last_V_reg_1480 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state6 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal line_buff_group_0_va_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buff_group_0_va_ce0 : STD_LOGIC;
    signal line_buff_group_0_va_we0 : STD_LOGIC;
    signal line_buff_group_0_va_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buff_group_1_va_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buff_group_1_va_ce0 : STD_LOGIC;
    signal line_buff_group_1_va_we0 : STD_LOGIC;
    signal line_buff_group_1_va_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buff_group_2_va_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buff_group_2_va_ce0 : STD_LOGIC;
    signal line_buff_group_2_va_we0 : STD_LOGIC;
    signal line_buff_group_2_va_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buff_group_3_va_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buff_group_3_va_ce0 : STD_LOGIC;
    signal line_buff_group_3_va_we0 : STD_LOGIC;
    signal line_buff_group_3_va_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal phi_ln9_reg_299 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln9_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_mul_reg_310 : STD_LOGIC_VECTOR (6 downto 0);
    signal phi_ln10_reg_321 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln10_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_mul153_reg_332 : STD_LOGIC_VECTOR (6 downto 0);
    signal phi_ln11_reg_343 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln11_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_mul155_reg_354 : STD_LOGIC_VECTOR (6 downto 0);
    signal phi_ln12_reg_365 : STD_LOGIC_VECTOR (2 downto 0);
    signal phi_mul157_reg_376 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_phi_mux_col_assign_phi_fu_446_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_tmp_data_sub_data_0_s_phi_fu_489_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_data_sub_data_0_s_reg_486 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_data_sub_data_0_s_reg_486 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tmp_data_sub_data_1_s_phi_fu_499_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_data_sub_data_1_s_reg_496 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_data_sub_data_1_s_reg_496 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tmp_data_sub_data_2_s_phi_fu_509_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_data_sub_data_2_s_reg_506 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_data_sub_data_2_s_reg_506 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_curr_output_data_sub_3_phi_fu_519_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_curr_output_data_sub_3_reg_516 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_curr_output_data_sub_3_reg_516 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln203_1_fu_1125_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln203_fu_1155_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_dest_V_fu_160 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_keep_V_fu_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_strb_V_fu_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_user_V_fu_172 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_id_V_fu_176 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln52_fu_598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_fu_608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln21_fu_620_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln17_fu_604_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal row_idx_fu_648_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln52_3_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_fu_614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_2_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln23_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln19_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_fu_660_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln52_10_fu_748_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln17_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal row_stride_fu_762_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln17_1_fu_782_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_3_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_1_fu_674_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_6_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_11_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_4_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln17_fu_814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_6_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_7_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_8_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_9_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln17_fu_774_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln52_fu_866_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln52_1_fu_872_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln17_1_fu_786_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln17_3_fu_826_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln17_1_fu_834_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln52_1_fu_902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln17_2_fu_840_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_2_fu_878_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln52_13_fu_914_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln21_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln21_1_fu_932_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_stride_fu_920_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln21_1_fu_946_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_1_fu_950_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_5_fu_894_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_8_fu_964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_12_fu_908_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln21_1_fu_1056_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln19_1_fu_1070_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln17_1_fu_1084_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln52_5_fu_1098_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_7_fu_1107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln17_fu_1102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_1210_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1219_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln52_1_fu_1162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_3_fu_1112_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_2_fu_1166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_1210_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_1210_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_1210_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln52_fu_1119_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1219_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_1219_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_1219_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal regslice_both_outStream_V_data_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_inStream_V_data_U_apdone_blk : STD_LOGIC;
    signal inStream_TDATA_int : STD_LOGIC_VECTOR (63 downto 0);
    signal inStream_TVALID_int : STD_LOGIC;
    signal inStream_TREADY_int : STD_LOGIC;
    signal regslice_both_inStream_V_data_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TKEEP_int : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_inStream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TSTRB_int : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_inStream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TUSER_int : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_inStream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_inStream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TID_int : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_inStream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_inStream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal inStream_TDEST_int : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_inStream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_inStream_V_dest_V_U_ack_in : STD_LOGIC;
    signal outStream_TDATA_int : STD_LOGIC_VECTOR (63 downto 0);
    signal outStream_TVALID_int : STD_LOGIC;
    signal outStream_TREADY_int : STD_LOGIC;
    signal regslice_both_outStream_V_data_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_outStream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_outStream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_outStream_V_dest_V_U_vld_out : STD_LOGIC;
    signal grp_fu_1210_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1219_p00 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_400 : BOOLEAN;
    signal ap_condition_404 : BOOLEAN;

    component yolo_upsamp_top_mfYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component yolo_upsamp_top_mg8j IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component yolo_upsamp_top_lbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component yolo_upsamp_top_CTRL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    yolo_upsamp_top_CTRL_BUS_s_axi_U : component yolo_upsamp_top_CTRL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_BUS_AWVALID,
        AWREADY => s_axi_CTRL_BUS_AWREADY,
        AWADDR => s_axi_CTRL_BUS_AWADDR,
        WVALID => s_axi_CTRL_BUS_WVALID,
        WREADY => s_axi_CTRL_BUS_WREADY,
        WDATA => s_axi_CTRL_BUS_WDATA,
        WSTRB => s_axi_CTRL_BUS_WSTRB,
        ARVALID => s_axi_CTRL_BUS_ARVALID,
        ARREADY => s_axi_CTRL_BUS_ARREADY,
        ARADDR => s_axi_CTRL_BUS_ARADDR,
        RVALID => s_axi_CTRL_BUS_RVALID,
        RREADY => s_axi_CTRL_BUS_RREADY,
        RDATA => s_axi_CTRL_BUS_RDATA,
        RRESP => s_axi_CTRL_BUS_RRESP,
        BVALID => s_axi_CTRL_BUS_BVALID,
        BREADY => s_axi_CTRL_BUS_BREADY,
        BRESP => s_axi_CTRL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    line_buff_group_0_va_U : component yolo_upsamp_top_lbkb
    generic map (
        DataWidth => 16,
        AddressRange => 104,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buff_group_0_va_address0,
        ce0 => line_buff_group_0_va_ce0,
        we0 => line_buff_group_0_va_we0,
        d0 => curr_input_data_sub_s_reg_1411,
        q0 => line_buff_group_0_va_q0);

    line_buff_group_1_va_U : component yolo_upsamp_top_lbkb
    generic map (
        DataWidth => 16,
        AddressRange => 104,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buff_group_1_va_address0,
        ce0 => line_buff_group_1_va_ce0,
        we0 => line_buff_group_1_va_we0,
        d0 => curr_input_data_sub_1_reg_1417,
        q0 => line_buff_group_1_va_q0);

    line_buff_group_2_va_U : component yolo_upsamp_top_lbkb
    generic map (
        DataWidth => 16,
        AddressRange => 104,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buff_group_2_va_address0,
        ce0 => line_buff_group_2_va_ce0,
        we0 => line_buff_group_2_va_we0,
        d0 => curr_input_data_sub_2_reg_1423,
        q0 => line_buff_group_2_va_q0);

    line_buff_group_3_va_U : component yolo_upsamp_top_lbkb
    generic map (
        DataWidth => 16,
        AddressRange => 104,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buff_group_3_va_address0,
        ce0 => line_buff_group_3_va_ce0,
        we0 => line_buff_group_3_va_we0,
        d0 => curr_input_data_sub_3_reg_1429,
        q0 => line_buff_group_3_va_q0);

    yolo_upsamp_top_mfYi_U1 : component yolo_upsamp_top_mfYi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => grp_fu_1210_p0,
        din1 => grp_fu_1210_p1,
        din2 => grp_fu_1210_p2,
        dout => grp_fu_1210_p3);

    yolo_upsamp_top_mg8j_U2 : component yolo_upsamp_top_mg8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 5,
        din2_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => grp_fu_1219_p0,
        din1 => grp_fu_1219_p1,
        din2 => grp_fu_1219_p2,
        dout => grp_fu_1219_p3);

    regslice_both_inStream_V_data_U : component regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TDATA,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_data_U_ack_in,
        data_out => inStream_TDATA_int,
        vld_out => inStream_TVALID_int,
        ack_out => inStream_TREADY_int,
        apdone_blk => regslice_both_inStream_V_data_U_apdone_blk);

    regslice_both_inStream_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TKEEP,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_keep_V_U_ack_in,
        data_out => inStream_TKEEP_int,
        vld_out => regslice_both_inStream_V_keep_V_U_vld_out,
        ack_out => inStream_TREADY_int,
        apdone_blk => regslice_both_inStream_V_keep_V_U_apdone_blk);

    regslice_both_inStream_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TSTRB,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_strb_V_U_ack_in,
        data_out => inStream_TSTRB_int,
        vld_out => regslice_both_inStream_V_strb_V_U_vld_out,
        ack_out => inStream_TREADY_int,
        apdone_blk => regslice_both_inStream_V_strb_V_U_apdone_blk);

    regslice_both_inStream_V_user_V_U : component regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TUSER,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_user_V_U_ack_in,
        data_out => inStream_TUSER_int,
        vld_out => regslice_both_inStream_V_user_V_U_vld_out,
        ack_out => inStream_TREADY_int,
        apdone_blk => regslice_both_inStream_V_user_V_U_apdone_blk);

    regslice_both_inStream_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TLAST,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_last_V_U_ack_in,
        data_out => inStream_TLAST_int,
        vld_out => regslice_both_inStream_V_last_V_U_vld_out,
        ack_out => inStream_TREADY_int,
        apdone_blk => regslice_both_inStream_V_last_V_U_apdone_blk);

    regslice_both_inStream_V_id_V_U : component regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TID,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_id_V_U_ack_in,
        data_out => inStream_TID_int,
        vld_out => regslice_both_inStream_V_id_V_U_vld_out,
        ack_out => inStream_TREADY_int,
        apdone_blk => regslice_both_inStream_V_id_V_U_apdone_blk);

    regslice_both_inStream_V_dest_V_U : component regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => inStream_TDEST,
        vld_in => inStream_TVALID,
        ack_in => regslice_both_inStream_V_dest_V_U_ack_in,
        data_out => inStream_TDEST_int,
        vld_out => regslice_both_inStream_V_dest_V_U_vld_out,
        ack_out => inStream_TREADY_int,
        apdone_blk => regslice_both_inStream_V_dest_V_U_apdone_blk);

    regslice_both_outStream_V_data_U : component regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => outStream_TDATA_int,
        vld_in => outStream_TVALID_int,
        ack_in => outStream_TREADY_int,
        data_out => outStream_TDATA,
        vld_out => regslice_both_outStream_V_data_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_data_U_apdone_blk);

    regslice_both_outStream_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_keep_V_fu_164,
        vld_in => outStream_TVALID_int,
        ack_in => regslice_both_outStream_V_keep_V_U_ack_in_dummy,
        data_out => outStream_TKEEP,
        vld_out => regslice_both_outStream_V_keep_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_keep_V_U_apdone_blk);

    regslice_both_outStream_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_strb_V_fu_168,
        vld_in => outStream_TVALID_int,
        ack_in => regslice_both_outStream_V_strb_V_U_ack_in_dummy,
        data_out => outStream_TSTRB,
        vld_out => regslice_both_outStream_V_strb_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_strb_V_U_apdone_blk);

    regslice_both_outStream_V_user_V_U : component regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_user_V_fu_172,
        vld_in => outStream_TVALID_int,
        ack_in => regslice_both_outStream_V_user_V_U_ack_in_dummy,
        data_out => outStream_TUSER,
        vld_out => regslice_both_outStream_V_user_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_user_V_U_apdone_blk);

    regslice_both_outStream_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => curr_output_last_V_reg_1480,
        vld_in => outStream_TVALID_int,
        ack_in => regslice_both_outStream_V_last_V_U_ack_in_dummy,
        data_out => outStream_TLAST,
        vld_out => regslice_both_outStream_V_last_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_last_V_U_apdone_blk);

    regslice_both_outStream_V_id_V_U : component regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_id_V_fu_176,
        vld_in => outStream_TVALID_int,
        ack_in => regslice_both_outStream_V_id_V_U_ack_in_dummy,
        data_out => outStream_TID,
        vld_out => regslice_both_outStream_V_id_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_id_V_U_apdone_blk);

    regslice_both_outStream_V_dest_V_U : component regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_dest_V_fu_160,
        vld_in => outStream_TVALID_int,
        ack_in => regslice_both_outStream_V_dest_V_U_ack_in_dummy,
        data_out => outStream_TDEST,
        vld_out => regslice_both_outStream_V_dest_V_U_vld_out,
        ack_out => outStream_TREADY,
        apdone_blk => regslice_both_outStream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state6))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state6)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state6);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_400)) then
                if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516 <= curr_input_data_sub_3_reg_1429;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516 <= ap_phi_reg_pp0_iter1_curr_output_data_sub_3_reg_516;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_400)) then
                if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486 <= curr_input_data_sub_s_reg_1411;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_0_s_reg_486;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_400)) then
                if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496 <= curr_input_data_sub_1_reg_1417;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_1_s_reg_496;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_400)) then
                if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506 <= curr_input_data_sub_2_reg_1423;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_2_s_reg_506;
                end if;
            end if; 
        end if;
    end process;

    col_assign_reg_442_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                col_assign_reg_442 <= ap_const_lv4_0;
            elsif (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                col_assign_reg_442 <= select_ln52_4_reg_1360;
            end if; 
        end if;
    end process;

    col_stride_0_reg_464_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                col_stride_0_reg_464 <= ap_const_lv2_0;
            elsif (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                col_stride_0_reg_464 <= select_ln21_3_fu_978_p3;
            end if; 
        end if;
    end process;

    indvar_flatten136_reg_387_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                indvar_flatten136_reg_387 <= ap_const_lv13_0;
            elsif (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten136_reg_387 <= add_ln15_fu_642_p2;
            end if; 
        end if;
    end process;

    indvar_flatten27_reg_431_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                indvar_flatten27_reg_431 <= ap_const_lv9_0;
            elsif (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten27_reg_431 <= select_ln19_fu_1076_p3;
            end if; 
        end if;
    end process;

    indvar_flatten72_reg_409_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                indvar_flatten72_reg_409 <= ap_const_lv10_0;
            elsif (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten72_reg_409 <= select_ln17_5_fu_1090_p3;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_453_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                indvar_flatten_reg_453 <= ap_const_lv6_0;
            elsif (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_reg_453 <= select_ln21_4_fu_1062_p3;
            end if; 
        end if;
    end process;

    input_ch_idx_0_reg_475_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                input_ch_idx_0_reg_475 <= ap_const_lv4_0;
            elsif (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                input_ch_idx_0_reg_475 <= input_ch_idx_fu_1050_p2;
            end if; 
        end if;
    end process;

    phi_ln10_reg_321_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln9_fu_538_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                phi_ln10_reg_321 <= ap_const_lv3_0;
            elsif (((icmp_ln10_fu_556_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                phi_ln10_reg_321 <= add_ln10_fu_544_p2;
            end if; 
        end if;
    end process;

    phi_ln11_reg_343_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln10_fu_556_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                phi_ln11_reg_343 <= ap_const_lv3_0;
            elsif (((icmp_ln11_fu_574_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                phi_ln11_reg_343 <= add_ln11_fu_562_p2;
            end if; 
        end if;
    end process;

    phi_ln12_reg_365_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln11_fu_574_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                phi_ln12_reg_365 <= ap_const_lv3_0;
            elsif (((icmp_ln12_fu_592_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                phi_ln12_reg_365 <= add_ln12_fu_580_p2;
            end if; 
        end if;
    end process;

    phi_ln9_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln9_fu_538_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                phi_ln9_reg_299 <= add_ln9_fu_526_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                phi_ln9_reg_299 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    phi_mul153_reg_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln9_fu_538_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                phi_mul153_reg_332 <= ap_const_lv7_0;
            elsif (((icmp_ln10_fu_556_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                phi_mul153_reg_332 <= add_ln627_1_fu_550_p2;
            end if; 
        end if;
    end process;

    phi_mul155_reg_354_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln10_fu_556_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                phi_mul155_reg_354 <= ap_const_lv7_0;
            elsif (((icmp_ln11_fu_574_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                phi_mul155_reg_354 <= add_ln627_2_fu_568_p2;
            end if; 
        end if;
    end process;

    phi_mul157_reg_376_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln11_fu_574_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                phi_mul157_reg_376 <= ap_const_lv7_0;
            elsif (((icmp_ln12_fu_592_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                phi_mul157_reg_376 <= add_ln627_3_fu_586_p2;
            end if; 
        end if;
    end process;

    phi_mul_reg_310_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln9_fu_538_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                phi_mul_reg_310 <= add_ln627_fu_532_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                phi_mul_reg_310 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    row_idx_0_reg_398_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                row_idx_0_reg_398 <= ap_const_lv4_0;
            elsif (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                row_idx_0_reg_398 <= select_ln15_fu_754_p3;
            end if; 
        end if;
    end process;

    row_stride_0_reg_420_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then 
                row_stride_0_reg_420 <= ap_const_lv2_0;
            elsif (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                row_stride_0_reg_420 <= select_ln17_4_fu_852_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln17_3_reg_1345 <= and_ln17_3_fu_846_p2;
                col_idx_reg_1355 <= col_idx_fu_860_p2;
                icmp_ln52_4_reg_1435 <= icmp_ln52_4_fu_1044_p2;
                icmp_ln52_5_reg_1325 <= icmp_ln52_5_fu_700_p2;
                or_ln17_1_reg_1340 <= or_ln17_1_fu_820_p2;
                select_ln17_2_reg_1335 <= select_ln17_2_fu_806_p3;
                select_ln21_1_reg_1372 <= select_ln21_1_fu_956_p3;
                select_ln21_2_reg_1376 <= select_ln21_2_fu_970_p3;
                select_ln21_reg_1366 <= select_ln21_fu_938_p3;
                xor_ln52_reg_1320 <= xor_ln52_fu_682_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_curr_output_data_sub_3_reg_516 <= ap_phi_reg_pp0_iter0_curr_output_data_sub_3_reg_516;
                ap_phi_reg_pp0_iter1_tmp_data_sub_data_0_s_reg_486 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_0_s_reg_486;
                ap_phi_reg_pp0_iter1_tmp_data_sub_data_1_s_reg_496 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_1_s_reg_496;
                ap_phi_reg_pp0_iter1_tmp_data_sub_data_2_s_reg_506 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_2_s_reg_506;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln21_1_fu_956_p3 = ap_const_lv1_0) and (icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                curr_input_data_sub_1_reg_1417 <= inStream_TDATA_int(31 downto 16);
                curr_input_data_sub_2_reg_1423 <= inStream_TDATA_int(47 downto 32);
                curr_input_data_sub_3_reg_1429 <= inStream_TDATA_int(63 downto 48);
                curr_input_data_sub_s_reg_1411 <= curr_input_data_sub_s_fu_1010_p1;
                tmp_dest_V_4_reg_1406 <= inStream_TDEST_int;
                tmp_id_V_4_reg_1401 <= inStream_TID_int;
                tmp_keep_V_4_reg_1386 <= inStream_TKEEP_int;
                tmp_strb_V_4_reg_1391 <= inStream_TSTRB_int;
                tmp_user_V_4_reg_1396 <= inStream_TUSER_int;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                curr_output_last_V_reg_1480 <= curr_output_last_V_fu_1172_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln15_reg_1311 <= icmp_ln15_fu_636_p2;
                icmp_ln15_reg_1311_pp0_iter1_reg <= icmp_ln15_reg_1311;
                select_ln21_1_reg_1372_pp0_iter1_reg <= select_ln21_1_reg_1372;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln15_reg_1311_pp0_iter2_reg <= icmp_ln15_reg_1311_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln52_4_reg_1360 <= select_ln52_4_fu_886_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                tmp_dest_V_fu_160 <= tmp_dest_V_4_reg_1406;
                tmp_id_V_fu_176 <= tmp_id_V_4_reg_1401;
                tmp_keep_V_fu_164 <= tmp_keep_V_4_reg_1386;
                tmp_strb_V_fu_168 <= tmp_strb_V_4_reg_1391;
                tmp_user_V_fu_172 <= tmp_user_V_4_reg_1396;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, icmp_ln15_fu_636_p2, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, icmp_ln12_fu_592_p2, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, icmp_ln9_fu_538_p2, icmp_ln10_fu_556_p2, icmp_ln11_fu_574_p2, ap_CS_fsm_state10, regslice_both_outStream_V_data_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln9_fu_538_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln10_fu_556_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln11_fu_574_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln12_fu_592_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln15_fu_636_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((icmp_ln15_fu_636_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state10 => 
                if (((regslice_both_outStream_V_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln10_fu_544_p2 <= std_logic_vector(unsigned(phi_ln10_reg_321) + unsigned(ap_const_lv3_1));
    add_ln11_fu_562_p2 <= std_logic_vector(unsigned(phi_ln11_reg_343) + unsigned(ap_const_lv3_1));
    add_ln12_fu_580_p2 <= std_logic_vector(unsigned(phi_ln12_reg_365) + unsigned(ap_const_lv3_1));
    add_ln15_fu_642_p2 <= std_logic_vector(unsigned(ap_const_lv13_1) + unsigned(indvar_flatten136_reg_387));
    add_ln17_1_fu_1084_p2 <= std_logic_vector(unsigned(indvar_flatten72_reg_409) + unsigned(ap_const_lv10_1));
    add_ln19_1_fu_1070_p2 <= std_logic_vector(unsigned(indvar_flatten27_reg_431) + unsigned(ap_const_lv9_1));
    add_ln21_1_fu_1056_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_453) + unsigned(ap_const_lv6_1));
    add_ln627_1_fu_550_p2 <= std_logic_vector(unsigned(phi_mul153_reg_332) + unsigned(ap_const_lv7_D));
    add_ln627_2_fu_568_p2 <= std_logic_vector(unsigned(phi_mul155_reg_354) + unsigned(ap_const_lv7_D));
    add_ln627_3_fu_586_p2 <= std_logic_vector(unsigned(phi_mul157_reg_376) + unsigned(ap_const_lv7_D));
    add_ln627_fu_532_p2 <= std_logic_vector(unsigned(phi_mul_reg_310) + unsigned(ap_const_lv7_D));
    add_ln9_fu_526_p2 <= std_logic_vector(unsigned(phi_ln9_reg_299) + unsigned(ap_const_lv3_1));
    and_ln17_1_fu_834_p2 <= (or_ln17_1_fu_820_p2 and and_ln52_7_fu_712_p2);
    and_ln17_2_fu_840_p2 <= (or_ln17_1_fu_820_p2 and and_ln52_8_fu_724_p2);
    and_ln17_3_fu_846_p2 <= (or_ln17_1_fu_820_p2 and and_ln52_9_fu_736_p2);
    and_ln17_fu_1102_p2 <= (or_ln17_1_reg_1340 and and_ln52_5_fu_1098_p2);
    and_ln52_10_fu_748_p2 <= (xor_ln52_fu_682_p2 and icmp_ln19_fu_742_p2);
    and_ln52_11_fu_800_p2 <= (select_ln52_1_fu_674_p3 and icmp_ln52_6_fu_794_p2);
    and_ln52_12_fu_908_p2 <= (xor_ln52_1_fu_902_p2 and and_ln17_1_fu_834_p2);
    and_ln52_13_fu_914_p2 <= (xor_ln52_1_fu_902_p2 and and_ln17_2_fu_840_p2);
    and_ln52_1_fu_1162_p2 <= (select_ln21_2_reg_1376 and icmp_ln52_4_reg_1435);
    and_ln52_2_fu_1166_p2 <= (select_ln52_3_fu_1112_p3 and and_ln52_1_fu_1162_p2);
    and_ln52_3_fu_688_p2 <= (xor_ln52_fu_682_p2 and trunc_ln17_fu_604_p1);
    and_ln52_4_fu_694_p2 <= (xor_ln52_fu_682_p2 and and_ln52_fu_614_p2);
    and_ln52_5_fu_1098_p2 <= (xor_ln52_reg_1320 and icmp_ln52_5_reg_1325);
    and_ln52_6_fu_706_p2 <= (xor_ln52_fu_682_p2 and or_ln26_fu_624_p2);
    and_ln52_7_fu_712_p2 <= (xor_ln52_fu_682_p2 and icmp_ln52_2_fu_630_p2);
    and_ln52_8_fu_724_p2 <= (xor_ln52_fu_682_p2 and icmp_ln23_fu_718_p2);
    and_ln52_9_fu_736_p2 <= (xor_ln52_fu_682_p2 and icmp_ln21_fu_730_p2);
    and_ln52_fu_614_p2 <= (icmp_ln52_fu_598_p2 and icmp_ln52_1_fu_608_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(5);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(6);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_predicate_op151_read_state6, inStream_TVALID_int)
    begin
                ap_block_pp0_stage0_01001 <= ((inStream_TVALID_int = ap_const_logic_0) and (ap_predicate_op151_read_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_predicate_op151_read_state6, ap_block_state8_io, ap_block_state9_io, inStream_TVALID_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state9_io) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state8_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((inStream_TVALID_int = ap_const_logic_0) and (ap_predicate_op151_read_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_predicate_op151_read_state6, ap_block_state8_io, ap_block_state9_io, inStream_TVALID_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state9_io) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state8_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((inStream_TVALID_int = ap_const_logic_0) and (ap_predicate_op151_read_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_state6_pp0_stage0_iter0_assign_proc : process(ap_predicate_op151_read_state6, inStream_TVALID_int)
    begin
                ap_block_state6_pp0_stage0_iter0 <= ((inStream_TVALID_int = ap_const_logic_0) and (ap_predicate_op151_read_state6 = ap_const_boolean_1));
    end process;

        ap_block_state7_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_io_assign_proc : process(icmp_ln15_reg_1311_pp0_iter1_reg, outStream_TREADY_int)
    begin
                ap_block_state8_io <= ((icmp_ln15_reg_1311_pp0_iter1_reg = ap_const_lv1_0) and (outStream_TREADY_int = ap_const_logic_0));
    end process;

        ap_block_state8_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_io_assign_proc : process(icmp_ln15_reg_1311_pp0_iter2_reg, outStream_TREADY_int)
    begin
                ap_block_state9_io <= ((icmp_ln15_reg_1311_pp0_iter2_reg = ap_const_lv1_0) and (outStream_TREADY_int = ap_const_logic_0));
    end process;

        ap_block_state9_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_400_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
                ap_condition_400 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_404_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, icmp_ln15_reg_1311, ap_enable_reg_pp0_iter1)
    begin
                ap_condition_404 <= ((icmp_ln15_reg_1311 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_pp0_exit_iter0_state6_assign_proc : process(icmp_ln15_fu_636_p2)
    begin
        if ((icmp_ln15_fu_636_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state6 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state10, regslice_both_outStream_V_data_U_apdone_blk)
    begin
        if (((regslice_both_outStream_V_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_col_assign_phi_fu_446_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, icmp_ln15_reg_1311, col_assign_reg_442, select_ln52_4_reg_1360, ap_enable_reg_pp0_iter1)
    begin
        if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_col_assign_phi_fu_446_p4 <= select_ln52_4_reg_1360;
        else 
            ap_phi_mux_col_assign_phi_fu_446_p4 <= col_assign_reg_442;
        end if; 
    end process;


    ap_phi_mux_curr_output_data_sub_3_phi_fu_519_p4_assign_proc : process(icmp_ln15_reg_1311_pp0_iter1_reg, select_ln21_1_reg_1372_pp0_iter1_reg, line_buff_group_3_va_q0, ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516)
    begin
        if (((icmp_ln15_reg_1311_pp0_iter1_reg = ap_const_lv1_0) and (select_ln21_1_reg_1372_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_phi_mux_curr_output_data_sub_3_phi_fu_519_p4 <= line_buff_group_3_va_q0;
        else 
            ap_phi_mux_curr_output_data_sub_3_phi_fu_519_p4 <= ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516;
        end if; 
    end process;


    ap_phi_mux_tmp_data_sub_data_0_s_phi_fu_489_p4_assign_proc : process(icmp_ln15_reg_1311_pp0_iter1_reg, select_ln21_1_reg_1372_pp0_iter1_reg, line_buff_group_0_va_q0, ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486)
    begin
        if (((icmp_ln15_reg_1311_pp0_iter1_reg = ap_const_lv1_0) and (select_ln21_1_reg_1372_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_phi_mux_tmp_data_sub_data_0_s_phi_fu_489_p4 <= line_buff_group_0_va_q0;
        else 
            ap_phi_mux_tmp_data_sub_data_0_s_phi_fu_489_p4 <= ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486;
        end if; 
    end process;


    ap_phi_mux_tmp_data_sub_data_1_s_phi_fu_499_p4_assign_proc : process(icmp_ln15_reg_1311_pp0_iter1_reg, select_ln21_1_reg_1372_pp0_iter1_reg, line_buff_group_1_va_q0, ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496)
    begin
        if (((icmp_ln15_reg_1311_pp0_iter1_reg = ap_const_lv1_0) and (select_ln21_1_reg_1372_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_phi_mux_tmp_data_sub_data_1_s_phi_fu_499_p4 <= line_buff_group_1_va_q0;
        else 
            ap_phi_mux_tmp_data_sub_data_1_s_phi_fu_499_p4 <= ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496;
        end if; 
    end process;


    ap_phi_mux_tmp_data_sub_data_2_s_phi_fu_509_p4_assign_proc : process(icmp_ln15_reg_1311_pp0_iter1_reg, select_ln21_1_reg_1372_pp0_iter1_reg, line_buff_group_2_va_q0, ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506)
    begin
        if (((icmp_ln15_reg_1311_pp0_iter1_reg = ap_const_lv1_0) and (select_ln21_1_reg_1372_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_phi_mux_tmp_data_sub_data_2_s_phi_fu_509_p4 <= line_buff_group_2_va_q0;
        else 
            ap_phi_mux_tmp_data_sub_data_2_s_phi_fu_509_p4 <= ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_curr_output_data_sub_3_reg_516 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tmp_data_sub_data_0_s_reg_486 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tmp_data_sub_data_1_s_reg_496 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tmp_data_sub_data_2_s_reg_506 <= "XXXXXXXXXXXXXXXX";

    ap_predicate_op151_read_state6_assign_proc : process(icmp_ln15_fu_636_p2, select_ln21_1_fu_956_p3)
    begin
                ap_predicate_op151_read_state6 <= ((select_ln21_1_fu_956_p3 = ap_const_lv1_0) and (icmp_ln15_fu_636_p2 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state10, regslice_both_outStream_V_data_U_apdone_blk)
    begin
        if (((regslice_both_outStream_V_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    col_idx_fu_860_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(select_ln17_fu_774_p3));
    col_stride_fu_920_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(select_ln52_2_fu_878_p3));
    curr_input_data_sub_s_fu_1010_p1 <= inStream_TDATA_int(16 - 1 downto 0);
    curr_output_last_V_fu_1172_p2 <= (select_ln17_2_reg_1335 and and_ln52_2_fu_1166_p2);
    grp_fu_1210_p0 <= ap_const_lv8_D(5 - 1 downto 0);
    grp_fu_1210_p1 <= grp_fu_1210_p10(4 - 1 downto 0);
    grp_fu_1210_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln21_reg_1366),8));
    grp_fu_1210_p2 <= zext_ln52_fu_1119_p1(4 - 1 downto 0);
    grp_fu_1219_p0 <= grp_fu_1219_p00(4 - 1 downto 0);
    grp_fu_1219_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln21_reg_1366),8));
    grp_fu_1219_p1 <= ap_const_lv8_D(5 - 1 downto 0);
    grp_fu_1219_p2 <= zext_ln52_fu_1119_p1(4 - 1 downto 0);
    icmp_ln10_fu_556_p2 <= "1" when (phi_ln10_reg_321 = ap_const_lv3_7) else "0";
    icmp_ln11_fu_574_p2 <= "1" when (phi_ln11_reg_343 = ap_const_lv3_7) else "0";
    icmp_ln12_fu_592_p2 <= "1" when (phi_ln12_reg_365 = ap_const_lv3_7) else "0";
    icmp_ln15_fu_636_p2 <= "1" when (indvar_flatten136_reg_387 = ap_const_lv13_1520) else "0";
    icmp_ln17_fu_654_p2 <= "1" when (indvar_flatten72_reg_409 = ap_const_lv10_1A0) else "0";
    icmp_ln19_fu_742_p2 <= "1" when (indvar_flatten27_reg_431 = ap_const_lv9_D0) else "0";
    icmp_ln21_fu_730_p2 <= "1" when (indvar_flatten_reg_453 = ap_const_lv6_10) else "0";
    icmp_ln23_fu_718_p2 <= "1" when (input_ch_idx_0_reg_475 = ap_const_lv4_8) else "0";
    icmp_ln52_1_fu_608_p2 <= "1" when (row_stride_0_reg_420 = ap_const_lv2_1) else "0";
    icmp_ln52_2_fu_630_p2 <= "1" when (col_stride_0_reg_464 = ap_const_lv2_1) else "0";
    icmp_ln52_3_fu_668_p2 <= "1" when (row_idx_fu_648_p2 = ap_const_lv4_C) else "0";
    icmp_ln52_4_fu_1044_p2 <= "1" when (select_ln21_fu_938_p3 = ap_const_lv4_7) else "0";
    icmp_ln52_5_fu_700_p2 <= "1" when (ap_phi_mux_col_assign_phi_fu_446_p4 = ap_const_lv4_C) else "0";
    icmp_ln52_6_fu_794_p2 <= "1" when (select_ln52_fu_660_p3 = ap_const_lv2_0) else "0";
    icmp_ln52_7_fu_1107_p2 <= "1" when (col_idx_reg_1355 = ap_const_lv4_C) else "0";
    icmp_ln52_8_fu_964_p2 <= "1" when (select_ln52_2_fu_878_p3 = ap_const_lv2_0) else "0";
    icmp_ln52_fu_598_p2 <= "1" when (row_idx_0_reg_398 = ap_const_lv4_C) else "0";
    icmp_ln9_fu_538_p2 <= "1" when (phi_ln9_reg_299 = ap_const_lv3_7) else "0";

    inStream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln15_fu_636_p2, select_ln21_1_fu_956_p3, inStream_TVALID_int)
    begin
        if (((select_ln21_1_fu_956_p3 = ap_const_lv1_0) and (icmp_ln15_fu_636_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            inStream_TDATA_blk_n <= inStream_TVALID_int;
        else 
            inStream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    inStream_TREADY_assign_proc : process(inStream_TVALID, regslice_both_inStream_V_data_U_ack_in)
    begin
        if (((regslice_both_inStream_V_data_U_ack_in = ap_const_logic_1) and (inStream_TVALID = ap_const_logic_1))) then 
            inStream_TREADY <= ap_const_logic_1;
        else 
            inStream_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    inStream_TREADY_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_predicate_op151_read_state6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op151_read_state6 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            inStream_TREADY_int <= ap_const_logic_1;
        else 
            inStream_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;

    input_ch_idx_fu_1050_p2 <= std_logic_vector(unsigned(select_ln21_fu_938_p3) + unsigned(ap_const_lv4_1));

    line_buff_group_0_va_address0_assign_proc : process(select_ln21_1_reg_1372, sext_ln203_1_fu_1125_p1, sext_ln203_fu_1155_p1, ap_condition_404)
    begin
        if ((ap_const_boolean_1 = ap_condition_404)) then
            if ((select_ln21_1_reg_1372 = ap_const_lv1_1)) then 
                line_buff_group_0_va_address0 <= sext_ln203_fu_1155_p1(7 - 1 downto 0);
            elsif ((select_ln21_1_reg_1372 = ap_const_lv1_0)) then 
                line_buff_group_0_va_address0 <= sext_ln203_1_fu_1125_p1(7 - 1 downto 0);
            else 
                line_buff_group_0_va_address0 <= "XXXXXXX";
            end if;
        else 
            line_buff_group_0_va_address0 <= "XXXXXXX";
        end if; 
    end process;


    line_buff_group_0_va_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln15_reg_1311, ap_block_pp0_stage0_11001, select_ln21_1_reg_1372, ap_enable_reg_pp0_iter1)
    begin
        if ((((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)))) then 
            line_buff_group_0_va_ce0 <= ap_const_logic_1;
        else 
            line_buff_group_0_va_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buff_group_0_va_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln15_reg_1311, ap_block_pp0_stage0_11001, select_ln21_1_reg_1372, ap_enable_reg_pp0_iter1)
    begin
        if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line_buff_group_0_va_we0 <= ap_const_logic_1;
        else 
            line_buff_group_0_va_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buff_group_1_va_address0_assign_proc : process(select_ln21_1_reg_1372, sext_ln203_1_fu_1125_p1, sext_ln203_fu_1155_p1, ap_condition_404)
    begin
        if ((ap_const_boolean_1 = ap_condition_404)) then
            if ((select_ln21_1_reg_1372 = ap_const_lv1_1)) then 
                line_buff_group_1_va_address0 <= sext_ln203_fu_1155_p1(7 - 1 downto 0);
            elsif ((select_ln21_1_reg_1372 = ap_const_lv1_0)) then 
                line_buff_group_1_va_address0 <= sext_ln203_1_fu_1125_p1(7 - 1 downto 0);
            else 
                line_buff_group_1_va_address0 <= "XXXXXXX";
            end if;
        else 
            line_buff_group_1_va_address0 <= "XXXXXXX";
        end if; 
    end process;


    line_buff_group_1_va_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln15_reg_1311, ap_block_pp0_stage0_11001, select_ln21_1_reg_1372, ap_enable_reg_pp0_iter1)
    begin
        if ((((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)))) then 
            line_buff_group_1_va_ce0 <= ap_const_logic_1;
        else 
            line_buff_group_1_va_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buff_group_1_va_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln15_reg_1311, ap_block_pp0_stage0_11001, select_ln21_1_reg_1372, ap_enable_reg_pp0_iter1)
    begin
        if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line_buff_group_1_va_we0 <= ap_const_logic_1;
        else 
            line_buff_group_1_va_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buff_group_2_va_address0_assign_proc : process(select_ln21_1_reg_1372, sext_ln203_1_fu_1125_p1, sext_ln203_fu_1155_p1, ap_condition_404)
    begin
        if ((ap_const_boolean_1 = ap_condition_404)) then
            if ((select_ln21_1_reg_1372 = ap_const_lv1_1)) then 
                line_buff_group_2_va_address0 <= sext_ln203_fu_1155_p1(7 - 1 downto 0);
            elsif ((select_ln21_1_reg_1372 = ap_const_lv1_0)) then 
                line_buff_group_2_va_address0 <= sext_ln203_1_fu_1125_p1(7 - 1 downto 0);
            else 
                line_buff_group_2_va_address0 <= "XXXXXXX";
            end if;
        else 
            line_buff_group_2_va_address0 <= "XXXXXXX";
        end if; 
    end process;


    line_buff_group_2_va_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln15_reg_1311, ap_block_pp0_stage0_11001, select_ln21_1_reg_1372, ap_enable_reg_pp0_iter1)
    begin
        if ((((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)))) then 
            line_buff_group_2_va_ce0 <= ap_const_logic_1;
        else 
            line_buff_group_2_va_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buff_group_2_va_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln15_reg_1311, ap_block_pp0_stage0_11001, select_ln21_1_reg_1372, ap_enable_reg_pp0_iter1)
    begin
        if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line_buff_group_2_va_we0 <= ap_const_logic_1;
        else 
            line_buff_group_2_va_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buff_group_3_va_address0_assign_proc : process(select_ln21_1_reg_1372, sext_ln203_1_fu_1125_p1, sext_ln203_fu_1155_p1, ap_condition_404)
    begin
        if ((ap_const_boolean_1 = ap_condition_404)) then
            if ((select_ln21_1_reg_1372 = ap_const_lv1_1)) then 
                line_buff_group_3_va_address0 <= sext_ln203_fu_1155_p1(7 - 1 downto 0);
            elsif ((select_ln21_1_reg_1372 = ap_const_lv1_0)) then 
                line_buff_group_3_va_address0 <= sext_ln203_1_fu_1125_p1(7 - 1 downto 0);
            else 
                line_buff_group_3_va_address0 <= "XXXXXXX";
            end if;
        else 
            line_buff_group_3_va_address0 <= "XXXXXXX";
        end if; 
    end process;


    line_buff_group_3_va_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln15_reg_1311, ap_block_pp0_stage0_11001, select_ln21_1_reg_1372, ap_enable_reg_pp0_iter1)
    begin
        if ((((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)))) then 
            line_buff_group_3_va_ce0 <= ap_const_logic_1;
        else 
            line_buff_group_3_va_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buff_group_3_va_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln15_reg_1311, ap_block_pp0_stage0_11001, select_ln21_1_reg_1372, ap_enable_reg_pp0_iter1)
    begin
        if (((icmp_ln15_reg_1311 = ap_const_lv1_0) and (select_ln21_1_reg_1372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line_buff_group_3_va_we0 <= ap_const_logic_1;
        else 
            line_buff_group_3_va_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln17_1_fu_820_p2 <= (xor_ln17_fu_814_p2 or icmp_ln17_fu_654_p2);
    or_ln17_fu_768_p2 <= (icmp_ln17_fu_654_p2 or and_ln52_10_fu_748_p2);
    or_ln21_1_fu_932_p2 <= (or_ln21_fu_926_p2 or or_ln17_fu_768_p2);
    or_ln21_fu_926_p2 <= (and_ln52_13_fu_914_p2 or and_ln17_3_fu_846_p2);
    or_ln26_1_fu_950_p2 <= (trunc_ln21_1_fu_946_p1 or select_ln17_1_fu_786_p3);
    or_ln26_fu_624_p2 <= (trunc_ln21_fu_620_p1 or trunc_ln17_fu_604_p1);
    or_ln52_1_fu_872_p2 <= (or_ln52_fu_866_p2 or icmp_ln17_fu_654_p2);
    or_ln52_fu_866_p2 <= (and_ln52_10_fu_748_p2 or and_ln17_3_fu_846_p2);

    outStream_TDATA_blk_n_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln15_reg_1311_pp0_iter1_reg, ap_enable_reg_pp0_iter3, icmp_ln15_reg_1311_pp0_iter2_reg, outStream_TREADY_int)
    begin
        if ((((icmp_ln15_reg_1311_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((icmp_ln15_reg_1311_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            outStream_TDATA_blk_n <= outStream_TREADY_int;
        else 
            outStream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outStream_TDATA_int <= (((ap_phi_mux_curr_output_data_sub_3_phi_fu_519_p4 & ap_phi_mux_tmp_data_sub_data_2_s_phi_fu_509_p4) & ap_phi_mux_tmp_data_sub_data_1_s_phi_fu_499_p4) & ap_phi_mux_tmp_data_sub_data_0_s_phi_fu_489_p4);
    outStream_TVALID <= regslice_both_outStream_V_data_U_vld_out;

    outStream_TVALID_int_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln15_reg_1311_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln15_reg_1311_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            outStream_TVALID_int <= ap_const_logic_1;
        else 
            outStream_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    row_idx_fu_648_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(row_idx_0_reg_398));
    row_stride_fu_762_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(select_ln52_fu_660_p3));
    select_ln15_fu_754_p3 <= 
        row_idx_fu_648_p2 when (icmp_ln17_fu_654_p2(0) = '1') else 
        row_idx_0_reg_398;
    select_ln17_1_fu_786_p3 <= 
        trunc_ln17_1_fu_782_p1 when (and_ln52_10_fu_748_p2(0) = '1') else 
        and_ln52_3_fu_688_p2;
    select_ln17_2_fu_806_p3 <= 
        and_ln52_11_fu_800_p2 when (and_ln52_10_fu_748_p2(0) = '1') else 
        and_ln52_4_fu_694_p2;
    select_ln17_3_fu_826_p3 <= 
        trunc_ln17_1_fu_782_p1 when (and_ln52_10_fu_748_p2(0) = '1') else 
        and_ln52_6_fu_706_p2;
    select_ln17_4_fu_852_p3 <= 
        row_stride_fu_762_p2 when (and_ln52_10_fu_748_p2(0) = '1') else 
        select_ln52_fu_660_p3;
    select_ln17_5_fu_1090_p3 <= 
        ap_const_lv10_1 when (icmp_ln17_fu_654_p2(0) = '1') else 
        add_ln17_1_fu_1084_p2;
    select_ln17_fu_774_p3 <= 
        ap_const_lv4_0 when (or_ln17_fu_768_p2(0) = '1') else 
        ap_phi_mux_col_assign_phi_fu_446_p4;
    select_ln19_fu_1076_p3 <= 
        ap_const_lv9_1 when (or_ln17_fu_768_p2(0) = '1') else 
        add_ln19_1_fu_1070_p2;
    select_ln21_1_fu_956_p3 <= 
        or_ln26_1_fu_950_p2 when (and_ln52_13_fu_914_p2(0) = '1') else 
        select_ln52_5_fu_894_p3;
    select_ln21_2_fu_970_p3 <= 
        icmp_ln52_8_fu_964_p2 when (and_ln52_13_fu_914_p2(0) = '1') else 
        and_ln52_12_fu_908_p2;
    select_ln21_3_fu_978_p3 <= 
        col_stride_fu_920_p2 when (and_ln52_13_fu_914_p2(0) = '1') else 
        select_ln52_2_fu_878_p3;
    select_ln21_4_fu_1062_p3 <= 
        ap_const_lv6_1 when (or_ln52_1_fu_872_p2(0) = '1') else 
        add_ln21_1_fu_1056_p2;
    select_ln21_fu_938_p3 <= 
        ap_const_lv4_0 when (or_ln21_1_fu_932_p2(0) = '1') else 
        input_ch_idx_0_reg_475;
    select_ln52_1_fu_674_p3 <= 
        icmp_ln52_3_fu_668_p2 when (icmp_ln17_fu_654_p2(0) = '1') else 
        icmp_ln52_fu_598_p2;
    select_ln52_2_fu_878_p3 <= 
        ap_const_lv2_0 when (or_ln52_1_fu_872_p2(0) = '1') else 
        col_stride_0_reg_464;
    select_ln52_3_fu_1112_p3 <= 
        icmp_ln52_7_fu_1107_p2 when (and_ln17_3_reg_1345(0) = '1') else 
        and_ln17_fu_1102_p2;
    select_ln52_4_fu_886_p3 <= 
        col_idx_fu_860_p2 when (and_ln17_3_fu_846_p2(0) = '1') else 
        select_ln17_fu_774_p3;
    select_ln52_5_fu_894_p3 <= 
        select_ln17_1_fu_786_p3 when (and_ln17_3_fu_846_p2(0) = '1') else 
        select_ln17_3_fu_826_p3;
    select_ln52_fu_660_p3 <= 
        ap_const_lv2_0 when (icmp_ln17_fu_654_p2(0) = '1') else 
        row_stride_0_reg_420;
        sext_ln203_1_fu_1125_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_1210_p3),64));

        sext_ln203_fu_1155_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_1219_p3),64));

    trunc_ln17_1_fu_782_p1 <= row_stride_fu_762_p2(1 - 1 downto 0);
    trunc_ln17_fu_604_p1 <= row_stride_0_reg_420(1 - 1 downto 0);
    trunc_ln21_1_fu_946_p1 <= col_stride_fu_920_p2(1 - 1 downto 0);
    trunc_ln21_fu_620_p1 <= col_stride_0_reg_464(1 - 1 downto 0);
    xor_ln17_fu_814_p2 <= (icmp_ln19_fu_742_p2 xor ap_const_lv1_1);
    xor_ln52_1_fu_902_p2 <= (ap_const_lv1_1 xor and_ln17_3_fu_846_p2);
    xor_ln52_fu_682_p2 <= (icmp_ln17_fu_654_p2 xor ap_const_lv1_1);
    zext_ln52_fu_1119_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_4_reg_1360),8));
end behav;
