// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="yolo_acc_top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.631750,HLS_SYN_LAT=1384465,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=3,HLS_SYN_FF=1237,HLS_SYN_LUT=1930,HLS_VERSION=2019_2}" *)

module yolo_acc_top (
        ap_clk,
        ap_rst_n,
        inStream_a_TDATA,
        inStream_a_TVALID,
        inStream_a_TREADY,
        inStream_a_TKEEP,
        inStream_a_TSTRB,
        inStream_a_TUSER,
        inStream_a_TLAST,
        inStream_a_TID,
        inStream_a_TDEST,
        inStream_b_TDATA,
        inStream_b_TVALID,
        inStream_b_TREADY,
        inStream_b_TKEEP,
        inStream_b_TSTRB,
        inStream_b_TUSER,
        inStream_b_TLAST,
        inStream_b_TID,
        inStream_b_TDEST,
        outStream_TDATA,
        outStream_TVALID,
        outStream_TREADY,
        outStream_TKEEP,
        outStream_TSTRB,
        outStream_TUSER,
        outStream_TLAST,
        outStream_TID,
        outStream_TDEST,
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_pp0_stage0 = 8'd2;
parameter    ap_ST_fsm_pp0_stage1 = 8'd4;
parameter    ap_ST_fsm_state5 = 8'd8;
parameter    ap_ST_fsm_state6 = 8'd16;
parameter    ap_ST_fsm_pp1_stage0 = 8'd32;
parameter    ap_ST_fsm_pp1_stage1 = 8'd64;
parameter    ap_ST_fsm_state14 = 8'd128;
parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] inStream_a_TDATA;
input   inStream_a_TVALID;
output   inStream_a_TREADY;
input  [7:0] inStream_a_TKEEP;
input  [7:0] inStream_a_TSTRB;
input  [1:0] inStream_a_TUSER;
input  [0:0] inStream_a_TLAST;
input  [4:0] inStream_a_TID;
input  [5:0] inStream_a_TDEST;
input  [63:0] inStream_b_TDATA;
input   inStream_b_TVALID;
output   inStream_b_TREADY;
input  [7:0] inStream_b_TKEEP;
input  [7:0] inStream_b_TSTRB;
input  [1:0] inStream_b_TUSER;
input  [0:0] inStream_b_TLAST;
input  [4:0] inStream_b_TID;
input  [5:0] inStream_b_TDEST;
output  [63:0] outStream_TDATA;
output   outStream_TVALID;
input   outStream_TREADY;
output  [7:0] outStream_TKEEP;
output  [7:0] outStream_TSTRB;
output  [1:0] outStream_TUSER;
output  [0:0] outStream_TLAST;
output  [4:0] outStream_TID;
output  [5:0] outStream_TDEST;
input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
output   interrupt;

reg inStream_a_TREADY;
reg inStream_b_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [8:0] input_h_V;
wire   [8:0] input_w_V;
wire   [3:0] fold_input_ch_V;
wire   [0:0] leaky_V;
wire   [0:0] bias_en_V;
reg    inStream_a_TDATA_blk_n;
wire    ap_CS_fsm_pp1_stage1;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage1;
reg   [0:0] icmp_ln42_reg_1315;
reg    inStream_b_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] bias_en_V_read_reg_1223;
reg    outStream_TDATA_blk_n;
reg    ap_enable_reg_pp1_iter2;
reg   [0:0] icmp_ln42_reg_1315_pp1_iter2_reg;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter3;
wire    ap_block_pp1_stage0;
reg   [3:0] t_V_reg_328;
reg   [21:0] indvar_flatten17_reg_339;
reg   [8:0] i_op_assign_reg_350;
reg   [12:0] indvar_flatten_reg_362;
reg   [8:0] i_op_assign_1_reg_373;
reg   [3:0] i_op_assign_2_reg_384;
reg   [0:0] leaky_V_read_reg_1229;
reg   [3:0] fold_input_ch_V_read_reg_1235;
reg   [8:0] input_w_V_read_reg_1243;
reg   [8:0] input_h_V_read_reg_1249;
wire   [0:0] icmp_ln25_fu_448_p2;
reg   [0:0] icmp_ln25_reg_1255;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] i_V_fu_453_p2;
reg   [3:0] i_V_reg_1259;
wire   [5:0] ret_V_fu_459_p3;
reg   [5:0] ret_V_reg_1264;
wire   [15:0] grp_fu_428_p4;
reg   [15:0] tmp_data_sub_data_2_s_reg_1272;
reg    ap_block_state4_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_11001;
wire   [15:0] grp_fu_438_p4;
reg   [15:0] tmp_data_sub_data_3_s_reg_1277;
wire   [12:0] mul_ln1354_fu_512_p2;
reg   [12:0] mul_ln1354_reg_1282;
wire    ap_CS_fsm_state5;
wire   [9:0] add_ln1354_fu_521_p2;
reg   [9:0] add_ln1354_reg_1288;
wire    ap_CS_fsm_state6;
wire   [9:0] add_ln1354_1_fu_530_p2;
reg   [9:0] add_ln1354_1_reg_1294;
wire   [21:0] mul_ln1354_1_fu_1217_p2;
reg   [21:0] mul_ln1354_1_reg_1300;
wire   [0:0] icmp_ln75_3_fu_542_p2;
reg   [0:0] icmp_ln75_3_reg_1305;
wire   [0:0] icmp_ln48_fu_548_p2;
reg   [0:0] icmp_ln48_reg_1310;
wire   [0:0] icmp_ln42_fu_577_p2;
wire    ap_block_state7_pp1_stage0_iter0;
wire    ap_block_state9_pp1_stage0_iter1;
wire    ap_block_state11_pp1_stage0_iter2;
wire    ap_block_state13_pp1_stage0_iter3;
reg    ap_block_state13_io;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] icmp_ln42_reg_1315_pp1_iter1_reg;
wire   [21:0] add_ln42_fu_582_p2;
reg   [21:0] add_ln42_reg_1319;
wire   [0:0] icmp_ln45_fu_588_p2;
reg   [0:0] icmp_ln45_reg_1324;
wire   [8:0] select_ln1598_fu_593_p3;
reg   [8:0] select_ln1598_reg_1330;
wire   [8:0] add_ln42_1_fu_601_p2;
reg   [8:0] add_ln42_1_reg_1335;
wire   [0:0] select_ln1598_3_fu_642_p3;
reg   [0:0] select_ln1598_3_reg_1340;
wire   [8:0] col_idx_fu_649_p2;
reg   [8:0] col_idx_reg_1345;
wire   [3:0] select_ln1598_4_fu_661_p3;
reg   [3:0] select_ln1598_4_reg_1350;
wire   [5:0] shl_ln_fu_692_p3;
reg   [5:0] shl_ln_reg_1355;
wire   [0:0] tmp_last_V_fu_728_p2;
reg   [0:0] tmp_last_V_reg_1371;
reg   [0:0] tmp_last_V_reg_1371_pp1_iter1_reg;
reg   [0:0] tmp_last_V_reg_1371_pp1_iter2_reg;
wire   [12:0] add_ln45_1_fu_734_p2;
reg   [12:0] add_ln45_1_reg_1376;
wire   [8:0] select_ln42_fu_740_p3;
reg   [8:0] select_ln42_reg_1381;
reg    ap_block_state8_pp1_stage1_iter0;
wire    ap_block_state10_pp1_stage1_iter1;
wire    ap_block_state12_pp1_stage1_iter2;
reg    ap_block_state12_io;
reg    ap_block_pp1_stage1_11001;
wire   [8:0] select_ln45_fu_746_p3;
reg   [8:0] select_ln45_reg_1386;
reg   [7:0] tmp_keep_V_reg_1391;
reg   [7:0] tmp_keep_V_reg_1391_pp1_iter1_reg;
reg   [7:0] tmp_strb_V_reg_1396;
reg   [7:0] tmp_strb_V_reg_1396_pp1_iter1_reg;
reg   [1:0] tmp_user_V_reg_1401;
reg   [1:0] tmp_user_V_reg_1401_pp1_iter1_reg;
reg   [4:0] tmp_id_V_reg_1406;
reg   [4:0] tmp_id_V_reg_1406_pp1_iter1_reg;
reg   [5:0] tmp_dest_V_reg_1411;
reg   [5:0] tmp_dest_V_reg_1411_pp1_iter1_reg;
wire   [15:0] output_acc_0_V_fu_895_p3;
wire   [15:0] output_acc_1_V_fu_986_p3;
wire   [15:0] output_acc_2_V_fu_1077_p3;
reg   [15:0] output_acc_2_V_reg_1426;
wire   [15:0] output_acc_3_V_fu_1167_p3;
reg   [15:0] output_acc_3_V_reg_1431;
wire   [15:0] kernel_bias_fp_V_q0;
wire   [15:0] kernel_bias_fp_V_q1;
wire   [3:0] input_ch_idx_fu_1195_p2;
reg   [3:0] input_ch_idx_reg_1456;
wire   [12:0] select_ln45_1_fu_1200_p3;
reg   [12:0] select_ln45_1_reg_1461;
reg    ap_enable_reg_pp1_iter1;
wire   [15:0] grp_post_process_unit_fu_395_ap_return;
reg   [15:0] tmp_data_sub_data_0_s_reg_1476;
wire   [15:0] grp_post_process_unit_fu_404_ap_return;
reg   [15:0] tmp_data_sub_data_1_1_reg_1481;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state7;
reg    ap_block_pp1_stage1_subdone;
reg   [4:0] kernel_bias_fp_V_address0;
reg    kernel_bias_fp_V_ce0;
reg    kernel_bias_fp_V_we0;
reg   [15:0] kernel_bias_fp_V_d0;
reg   [4:0] kernel_bias_fp_V_address1;
reg    kernel_bias_fp_V_ce1;
reg    kernel_bias_fp_V_we1;
reg   [15:0] kernel_bias_fp_V_d1;
reg   [15:0] grp_post_process_unit_fu_395_data_in_V;
reg    grp_post_process_unit_fu_395_ap_ce;
reg    ap_block_state8_pp1_stage1_iter0_ignore_call99;
wire    ap_block_state10_pp1_stage1_iter1_ignore_call99;
wire    ap_block_state12_pp1_stage1_iter2_ignore_call99;
reg    ap_block_pp1_stage1_11001_ignoreCallOp222;
wire    ap_block_state7_pp1_stage0_iter0_ignore_call99;
wire    ap_block_state9_pp1_stage0_iter1_ignore_call99;
wire    ap_block_state11_pp1_stage0_iter2_ignore_call99;
wire    ap_block_state13_pp1_stage0_iter3_ignore_call99;
reg    ap_block_pp1_stage0_11001_ignoreCallOp235;
reg   [15:0] grp_post_process_unit_fu_404_data_in_V;
reg    grp_post_process_unit_fu_404_ap_ce;
reg    ap_block_state8_pp1_stage1_iter0_ignore_call104;
wire    ap_block_state10_pp1_stage1_iter1_ignore_call104;
wire    ap_block_state12_pp1_stage1_iter2_ignore_call104;
reg    ap_block_pp1_stage1_11001_ignoreCallOp224;
wire    ap_block_state7_pp1_stage0_iter0_ignore_call104;
wire    ap_block_state9_pp1_stage0_iter1_ignore_call104;
wire    ap_block_state11_pp1_stage0_iter2_ignore_call104;
wire    ap_block_state13_pp1_stage0_iter3_ignore_call104;
reg    ap_block_pp1_stage0_11001_ignoreCallOp236;
reg   [3:0] ap_phi_mux_t_V_phi_fu_332_p4;
wire    ap_block_pp0_stage0;
reg   [21:0] ap_phi_mux_indvar_flatten17_phi_fu_343_p4;
reg   [8:0] ap_phi_mux_i_op_assign_phi_fu_354_p4;
reg   [12:0] ap_phi_mux_indvar_flatten_phi_fu_366_p4;
reg   [8:0] ap_phi_mux_i_op_assign_1_phi_fu_377_p4;
reg   [3:0] ap_phi_mux_i_op_assign_2_phi_fu_388_p4;
wire   [63:0] zext_ln544_2_fu_472_p1;
wire   [63:0] zext_ln544_3_fu_482_p1;
wire   [63:0] zext_ln544_fu_492_p1;
wire   [63:0] zext_ln544_1_fu_501_p1;
wire   [63:0] zext_ln65_fu_700_p1;
wire   [63:0] zext_ln66_fu_711_p1;
wire   [63:0] zext_ln67_fu_1180_p1;
wire   [63:0] zext_ln68_fu_1190_p1;
reg    ap_block_pp1_stage1_01001;
wire   [15:0] trunc_ln203_fu_487_p1;
wire   [15:0] grp_fu_417_p4;
wire   [5:0] ret_V_2_fu_467_p2;
wire   [5:0] ret_V_3_fu_477_p2;
wire   [5:0] ret_V_1_fu_496_p2;
wire   [3:0] mul_ln1354_fu_512_p0;
wire   [8:0] mul_ln1354_fu_512_p1;
wire   [9:0] zext_ln1354_fu_518_p1;
wire   [9:0] zext_ln1354_1_fu_527_p1;
wire   [9:0] zext_ln45_fu_553_p1;
wire   [9:0] zext_ln48_fu_562_p1;
wire   [0:0] icmp_ln75_1_fu_566_p2;
wire   [0:0] icmp_ln75_2_fu_557_p2;
wire   [9:0] zext_ln45_1_fu_607_p1;
wire   [0:0] icmp_ln75_4_fu_611_p2;
wire   [0:0] or_ln75_2_fu_624_p2;
wire   [0:0] or_ln75_fu_571_p2;
wire   [0:0] icmp_ln48_1_fu_637_p2;
wire   [0:0] or_ln1598_fu_655_p2;
wire   [9:0] zext_ln48_1_fu_669_p1;
wire   [0:0] icmp_ln75_5_fu_673_p2;
wire   [0:0] select_ln1598_1_fu_616_p3;
wire   [0:0] or_ln75_3_fu_678_p2;
wire   [0:0] select_ln1598_2_fu_629_p3;
wire   [5:0] or_ln66_fu_705_p2;
wire   [0:0] select_ln1598_5_fu_684_p3;
wire   [0:0] icmp_ln75_fu_716_p2;
wire   [0:0] or_ln75_1_fu_722_p2;
wire  signed [15:0] p_Val2_s_fu_775_p1;
wire  signed [15:0] p_Val2_1_fu_809_p1;
wire  signed [16:0] rhs_V_fu_817_p1;
wire  signed [16:0] lhs_V_fu_813_p1;
wire   [16:0] ret_V_8_fu_821_p2;
wire   [15:0] p_Val2_6_fu_835_p2;
wire   [0:0] p_Result_1_fu_841_p3;
wire   [0:0] p_Result_s_fu_827_p3;
wire   [0:0] xor_ln786_fu_849_p2;
wire   [0:0] xor_ln340_fu_867_p2;
wire   [0:0] xor_ln340_4_fu_861_p2;
wire   [0:0] underflow_fu_855_p2;
wire   [0:0] or_ln340_fu_873_p2;
wire   [15:0] select_ln340_fu_879_p3;
wire   [15:0] select_ln388_fu_887_p3;
wire  signed [15:0] p_Val2_4_fu_779_p4;
wire  signed [15:0] rhs_V_1_fu_908_p0;
wire  signed [16:0] rhs_V_1_fu_908_p1;
wire  signed [16:0] lhs_V_1_fu_904_p1;
wire   [16:0] ret_V_9_fu_912_p2;
wire  signed [15:0] p_Val2_10_fu_926_p1;
wire   [15:0] p_Val2_10_fu_926_p2;
wire   [0:0] p_Result_3_fu_932_p3;
wire   [0:0] p_Result_2_fu_918_p3;
wire   [0:0] xor_ln786_1_fu_940_p2;
wire   [0:0] xor_ln340_1_fu_958_p2;
wire   [0:0] xor_ln340_5_fu_952_p2;
wire   [0:0] underflow_1_fu_946_p2;
wire   [0:0] or_ln340_1_fu_964_p2;
wire   [15:0] select_ln340_1_fu_970_p3;
wire   [15:0] select_ln388_1_fu_978_p3;
wire  signed [15:0] p_Val2_8_fu_789_p4;
wire  signed [15:0] rhs_V_2_fu_999_p0;
wire  signed [16:0] rhs_V_2_fu_999_p1;
wire  signed [16:0] lhs_V_2_fu_995_p1;
wire   [16:0] ret_V_10_fu_1003_p2;
wire  signed [15:0] p_Val2_12_fu_1017_p1;
wire   [15:0] p_Val2_12_fu_1017_p2;
wire   [0:0] p_Result_5_fu_1023_p3;
wire   [0:0] p_Result_4_fu_1009_p3;
wire   [0:0] xor_ln786_2_fu_1031_p2;
wire   [0:0] xor_ln340_2_fu_1049_p2;
wire   [0:0] xor_ln340_6_fu_1043_p2;
wire   [0:0] underflow_2_fu_1037_p2;
wire   [0:0] or_ln340_2_fu_1055_p2;
wire   [15:0] select_ln340_2_fu_1061_p3;
wire   [15:0] select_ln388_2_fu_1069_p3;
wire  signed [15:0] p_Val2_13_fu_799_p4;
wire  signed [15:0] rhs_V_3_fu_1089_p0;
wire  signed [16:0] rhs_V_3_fu_1089_p1;
wire  signed [16:0] lhs_V_3_fu_1085_p1;
wire   [16:0] ret_V_11_fu_1093_p2;
wire  signed [15:0] p_Val2_15_fu_1107_p1;
wire   [15:0] p_Val2_15_fu_1107_p2;
wire   [0:0] p_Result_7_fu_1113_p3;
wire   [0:0] p_Result_6_fu_1099_p3;
wire   [0:0] xor_ln786_3_fu_1121_p2;
wire   [0:0] xor_ln340_3_fu_1139_p2;
wire   [0:0] xor_ln340_7_fu_1133_p2;
wire   [0:0] underflow_3_fu_1127_p2;
wire   [0:0] or_ln340_3_fu_1145_p2;
wire   [15:0] select_ln340_3_fu_1151_p3;
wire   [15:0] select_ln388_3_fu_1159_p3;
wire   [5:0] or_ln67_fu_1175_p2;
wire   [5:0] or_ln68_fu_1185_p2;
wire   [12:0] mul_ln1354_1_fu_1217_p0;
wire   [8:0] mul_ln1354_1_fu_1217_p1;
wire    ap_CS_fsm_state14;
wire    regslice_both_outStream_V_data_U_apdone_blk;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire    regslice_both_inStream_a_V_data_U_apdone_blk;
wire   [63:0] inStream_a_TDATA_int;
wire    inStream_a_TVALID_int;
reg    inStream_a_TREADY_int;
wire    regslice_both_inStream_a_V_data_U_ack_in;
wire    regslice_both_inStream_a_V_keep_V_U_apdone_blk;
wire   [7:0] inStream_a_TKEEP_int;
wire    regslice_both_inStream_a_V_keep_V_U_vld_out;
wire    regslice_both_inStream_a_V_keep_V_U_ack_in;
wire    regslice_both_inStream_a_V_strb_V_U_apdone_blk;
wire   [7:0] inStream_a_TSTRB_int;
wire    regslice_both_inStream_a_V_strb_V_U_vld_out;
wire    regslice_both_inStream_a_V_strb_V_U_ack_in;
wire    regslice_both_inStream_a_V_user_V_U_apdone_blk;
wire   [1:0] inStream_a_TUSER_int;
wire    regslice_both_inStream_a_V_user_V_U_vld_out;
wire    regslice_both_inStream_a_V_user_V_U_ack_in;
wire    regslice_both_inStream_a_V_last_V_U_apdone_blk;
wire   [0:0] inStream_a_TLAST_int;
wire    regslice_both_inStream_a_V_last_V_U_vld_out;
wire    regslice_both_inStream_a_V_last_V_U_ack_in;
wire    regslice_both_inStream_a_V_id_V_U_apdone_blk;
wire   [4:0] inStream_a_TID_int;
wire    regslice_both_inStream_a_V_id_V_U_vld_out;
wire    regslice_both_inStream_a_V_id_V_U_ack_in;
wire    regslice_both_inStream_a_V_dest_V_U_apdone_blk;
wire   [5:0] inStream_a_TDEST_int;
wire    regslice_both_inStream_a_V_dest_V_U_vld_out;
wire    regslice_both_inStream_a_V_dest_V_U_ack_in;
wire    regslice_both_inStream_b_V_data_U_apdone_blk;
wire   [63:0] inStream_b_TDATA_int;
wire    inStream_b_TVALID_int;
reg    inStream_b_TREADY_int;
wire    regslice_both_inStream_b_V_data_U_ack_in;
wire    regslice_both_inStream_b_V_keep_V_U_apdone_blk;
wire   [7:0] inStream_b_TKEEP_int;
wire    regslice_both_inStream_b_V_keep_V_U_vld_out;
wire    regslice_both_inStream_b_V_keep_V_U_ack_in;
wire    regslice_both_inStream_b_V_strb_V_U_apdone_blk;
wire   [7:0] inStream_b_TSTRB_int;
wire    regslice_both_inStream_b_V_strb_V_U_vld_out;
wire    regslice_both_inStream_b_V_strb_V_U_ack_in;
wire    regslice_both_inStream_b_V_user_V_U_apdone_blk;
wire   [1:0] inStream_b_TUSER_int;
wire    regslice_both_inStream_b_V_user_V_U_vld_out;
wire    regslice_both_inStream_b_V_user_V_U_ack_in;
wire    regslice_both_inStream_b_V_last_V_U_apdone_blk;
wire   [0:0] inStream_b_TLAST_int;
wire    regslice_both_inStream_b_V_last_V_U_vld_out;
wire    regslice_both_inStream_b_V_last_V_U_ack_in;
wire    regslice_both_inStream_b_V_id_V_U_apdone_blk;
wire   [4:0] inStream_b_TID_int;
wire    regslice_both_inStream_b_V_id_V_U_vld_out;
wire    regslice_both_inStream_b_V_id_V_U_ack_in;
wire    regslice_both_inStream_b_V_dest_V_U_apdone_blk;
wire   [5:0] inStream_b_TDEST_int;
wire    regslice_both_inStream_b_V_dest_V_U_vld_out;
wire    regslice_both_inStream_b_V_dest_V_U_ack_in;
wire   [63:0] outStream_TDATA_int;
reg    outStream_TVALID_int;
wire    outStream_TREADY_int;
wire    regslice_both_outStream_V_data_U_vld_out;
wire    regslice_both_outStream_V_keep_V_U_apdone_blk;
wire    regslice_both_outStream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_keep_V_U_vld_out;
wire    regslice_both_outStream_V_strb_V_U_apdone_blk;
wire    regslice_both_outStream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_strb_V_U_vld_out;
wire    regslice_both_outStream_V_user_V_U_apdone_blk;
wire    regslice_both_outStream_V_user_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_user_V_U_vld_out;
wire    regslice_both_outStream_V_last_V_U_apdone_blk;
wire    regslice_both_outStream_V_last_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_last_V_U_vld_out;
wire    regslice_both_outStream_V_id_V_U_apdone_blk;
wire    regslice_both_outStream_V_id_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_id_V_U_vld_out;
wire    regslice_both_outStream_V_dest_V_U_apdone_blk;
wire    regslice_both_outStream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_dest_V_U_vld_out;
wire   [21:0] mul_ln1354_1_fu_1217_p00;
wire   [21:0] mul_ln1354_1_fu_1217_p10;
wire   [12:0] mul_ln1354_fu_512_p00;
wire   [12:0] mul_ln1354_fu_512_p10;
reg    ap_condition_75;
reg    ap_condition_488;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

yolo_acc_top_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
yolo_acc_top_CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .input_h_V(input_h_V),
    .input_w_V(input_w_V),
    .fold_input_ch_V(fold_input_ch_V),
    .leaky_V(leaky_V),
    .bias_en_V(bias_en_V)
);

yolo_acc_top_kerncud #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
kernel_bias_fp_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(kernel_bias_fp_V_address0),
    .ce0(kernel_bias_fp_V_ce0),
    .we0(kernel_bias_fp_V_we0),
    .d0(kernel_bias_fp_V_d0),
    .q0(kernel_bias_fp_V_q0),
    .address1(kernel_bias_fp_V_address1),
    .ce1(kernel_bias_fp_V_ce1),
    .we1(kernel_bias_fp_V_we1),
    .d1(kernel_bias_fp_V_d1),
    .q1(kernel_bias_fp_V_q1)
);

post_process_unit grp_post_process_unit_fu_395(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in_V(grp_post_process_unit_fu_395_data_in_V),
    .bias_V(kernel_bias_fp_V_q0),
    .bias_en_V(bias_en_V_read_reg_1223),
    .leaky_V(leaky_V_read_reg_1229),
    .ap_return(grp_post_process_unit_fu_395_ap_return),
    .ap_ce(grp_post_process_unit_fu_395_ap_ce)
);

post_process_unit grp_post_process_unit_fu_404(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in_V(grp_post_process_unit_fu_404_data_in_V),
    .bias_V(kernel_bias_fp_V_q1),
    .bias_en_V(bias_en_V_read_reg_1223),
    .leaky_V(leaky_V_read_reg_1229),
    .ap_return(grp_post_process_unit_fu_404_ap_return),
    .ap_ce(grp_post_process_unit_fu_404_ap_ce)
);

yolo_acc_top_mul_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 22 ))
yolo_acc_top_mul_dEe_U7(
    .din0(mul_ln1354_1_fu_1217_p0),
    .din1(mul_ln1354_1_fu_1217_p1),
    .dout(mul_ln1354_1_fu_1217_p2)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_inStream_a_V_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_a_TDATA),
    .vld_in(inStream_a_TVALID),
    .ack_in(regslice_both_inStream_a_V_data_U_ack_in),
    .data_out(inStream_a_TDATA_int),
    .vld_out(inStream_a_TVALID_int),
    .ack_out(inStream_a_TREADY_int),
    .apdone_blk(regslice_both_inStream_a_V_data_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_inStream_a_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_a_TKEEP),
    .vld_in(inStream_a_TVALID),
    .ack_in(regslice_both_inStream_a_V_keep_V_U_ack_in),
    .data_out(inStream_a_TKEEP_int),
    .vld_out(regslice_both_inStream_a_V_keep_V_U_vld_out),
    .ack_out(inStream_a_TREADY_int),
    .apdone_blk(regslice_both_inStream_a_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_inStream_a_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_a_TSTRB),
    .vld_in(inStream_a_TVALID),
    .ack_in(regslice_both_inStream_a_V_strb_V_U_ack_in),
    .data_out(inStream_a_TSTRB_int),
    .vld_out(regslice_both_inStream_a_V_strb_V_U_vld_out),
    .ack_out(inStream_a_TREADY_int),
    .apdone_blk(regslice_both_inStream_a_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 2 ))
regslice_both_inStream_a_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_a_TUSER),
    .vld_in(inStream_a_TVALID),
    .ack_in(regslice_both_inStream_a_V_user_V_U_ack_in),
    .data_out(inStream_a_TUSER_int),
    .vld_out(regslice_both_inStream_a_V_user_V_U_vld_out),
    .ack_out(inStream_a_TREADY_int),
    .apdone_blk(regslice_both_inStream_a_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream_a_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_a_TLAST),
    .vld_in(inStream_a_TVALID),
    .ack_in(regslice_both_inStream_a_V_last_V_U_ack_in),
    .data_out(inStream_a_TLAST_int),
    .vld_out(regslice_both_inStream_a_V_last_V_U_vld_out),
    .ack_out(inStream_a_TREADY_int),
    .apdone_blk(regslice_both_inStream_a_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 5 ))
regslice_both_inStream_a_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_a_TID),
    .vld_in(inStream_a_TVALID),
    .ack_in(regslice_both_inStream_a_V_id_V_U_ack_in),
    .data_out(inStream_a_TID_int),
    .vld_out(regslice_both_inStream_a_V_id_V_U_vld_out),
    .ack_out(inStream_a_TREADY_int),
    .apdone_blk(regslice_both_inStream_a_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 6 ))
regslice_both_inStream_a_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_a_TDEST),
    .vld_in(inStream_a_TVALID),
    .ack_in(regslice_both_inStream_a_V_dest_V_U_ack_in),
    .data_out(inStream_a_TDEST_int),
    .vld_out(regslice_both_inStream_a_V_dest_V_U_vld_out),
    .ack_out(inStream_a_TREADY_int),
    .apdone_blk(regslice_both_inStream_a_V_dest_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_inStream_b_V_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_b_TDATA),
    .vld_in(inStream_b_TVALID),
    .ack_in(regslice_both_inStream_b_V_data_U_ack_in),
    .data_out(inStream_b_TDATA_int),
    .vld_out(inStream_b_TVALID_int),
    .ack_out(inStream_b_TREADY_int),
    .apdone_blk(regslice_both_inStream_b_V_data_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_inStream_b_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_b_TKEEP),
    .vld_in(inStream_b_TVALID),
    .ack_in(regslice_both_inStream_b_V_keep_V_U_ack_in),
    .data_out(inStream_b_TKEEP_int),
    .vld_out(regslice_both_inStream_b_V_keep_V_U_vld_out),
    .ack_out(inStream_b_TREADY_int),
    .apdone_blk(regslice_both_inStream_b_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_inStream_b_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_b_TSTRB),
    .vld_in(inStream_b_TVALID),
    .ack_in(regslice_both_inStream_b_V_strb_V_U_ack_in),
    .data_out(inStream_b_TSTRB_int),
    .vld_out(regslice_both_inStream_b_V_strb_V_U_vld_out),
    .ack_out(inStream_b_TREADY_int),
    .apdone_blk(regslice_both_inStream_b_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 2 ))
regslice_both_inStream_b_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_b_TUSER),
    .vld_in(inStream_b_TVALID),
    .ack_in(regslice_both_inStream_b_V_user_V_U_ack_in),
    .data_out(inStream_b_TUSER_int),
    .vld_out(regslice_both_inStream_b_V_user_V_U_vld_out),
    .ack_out(inStream_b_TREADY_int),
    .apdone_blk(regslice_both_inStream_b_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream_b_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_b_TLAST),
    .vld_in(inStream_b_TVALID),
    .ack_in(regslice_both_inStream_b_V_last_V_U_ack_in),
    .data_out(inStream_b_TLAST_int),
    .vld_out(regslice_both_inStream_b_V_last_V_U_vld_out),
    .ack_out(inStream_b_TREADY_int),
    .apdone_blk(regslice_both_inStream_b_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 5 ))
regslice_both_inStream_b_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_b_TID),
    .vld_in(inStream_b_TVALID),
    .ack_in(regslice_both_inStream_b_V_id_V_U_ack_in),
    .data_out(inStream_b_TID_int),
    .vld_out(regslice_both_inStream_b_V_id_V_U_vld_out),
    .ack_out(inStream_b_TREADY_int),
    .apdone_blk(regslice_both_inStream_b_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 6 ))
regslice_both_inStream_b_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_b_TDEST),
    .vld_in(inStream_b_TVALID),
    .ack_in(regslice_both_inStream_b_V_dest_V_U_ack_in),
    .data_out(inStream_b_TDEST_int),
    .vld_out(regslice_both_inStream_b_V_dest_V_U_vld_out),
    .ack_out(inStream_b_TREADY_int),
    .apdone_blk(regslice_both_inStream_b_V_dest_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_outStream_V_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(outStream_TDATA_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(outStream_TREADY_int),
    .data_out(outStream_TDATA),
    .vld_out(regslice_both_outStream_V_data_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_data_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_outStream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_keep_V_reg_1391_pp1_iter1_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_keep_V_U_ack_in_dummy),
    .data_out(outStream_TKEEP),
    .vld_out(regslice_both_outStream_V_keep_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_outStream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_strb_V_reg_1396_pp1_iter1_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_strb_V_U_ack_in_dummy),
    .data_out(outStream_TSTRB),
    .vld_out(regslice_both_outStream_V_strb_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 2 ))
regslice_both_outStream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_user_V_reg_1401_pp1_iter1_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_user_V_U_ack_in_dummy),
    .data_out(outStream_TUSER),
    .vld_out(regslice_both_outStream_V_user_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_outStream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_last_V_reg_1371_pp1_iter2_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_last_V_U_ack_in_dummy),
    .data_out(outStream_TLAST),
    .vld_out(regslice_both_outStream_V_last_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 5 ))
regslice_both_outStream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_id_V_reg_1406_pp1_iter1_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_id_V_U_ack_in_dummy),
    .data_out(outStream_TID),
    .vld_out(regslice_both_outStream_V_id_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 6 ))
regslice_both_outStream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_dest_V_reg_1411_pp1_iter1_reg),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_dest_V_U_ack_in_dummy),
    .data_out(outStream_TDEST),
    .vld_out(regslice_both_outStream_V_dest_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state7) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage1_subdone) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage1_subdone) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp1_stage1_subdone) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp1_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_op_assign_1_reg_373 <= select_ln45_reg_1386;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_op_assign_1_reg_373 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_op_assign_2_reg_384 <= input_ch_idx_reg_1456;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_op_assign_2_reg_384 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_op_assign_reg_350 <= select_ln42_reg_1381;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_op_assign_reg_350 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        indvar_flatten17_reg_339 <= add_ln42_reg_1319;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        indvar_flatten17_reg_339 <= 22'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        indvar_flatten_reg_362 <= select_ln45_1_reg_1461;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        indvar_flatten_reg_362 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln25_reg_1255 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_reg_328 <= i_V_reg_1259;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t_V_reg_328 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln1354_1_reg_1294 <= add_ln1354_1_fu_530_p2;
        add_ln1354_reg_1288 <= add_ln1354_fu_521_p2;
        icmp_ln48_reg_1310 <= icmp_ln48_fu_548_p2;
        icmp_ln75_3_reg_1305 <= icmp_ln75_3_fu_542_p2;
        mul_ln1354_1_reg_1300 <= mul_ln1354_1_fu_1217_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_fu_577_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        add_ln42_1_reg_1335 <= add_ln42_1_fu_601_p2;
        add_ln45_1_reg_1376 <= add_ln45_1_fu_734_p2;
        col_idx_reg_1345 <= col_idx_fu_649_p2;
        icmp_ln45_reg_1324 <= icmp_ln45_fu_588_p2;
        select_ln1598_3_reg_1340 <= select_ln1598_3_fu_642_p3;
        select_ln1598_4_reg_1350 <= select_ln1598_4_fu_661_p3;
        select_ln1598_reg_1330 <= select_ln1598_fu_593_p3;
        shl_ln_reg_1355[5 : 2] <= shl_ln_fu_692_p3[5 : 2];
        tmp_last_V_reg_1371 <= tmp_last_V_fu_728_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        add_ln42_reg_1319 <= add_ln42_fu_582_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        bias_en_V_read_reg_1223 <= bias_en_V;
        fold_input_ch_V_read_reg_1235 <= fold_input_ch_V;
        input_h_V_read_reg_1249 <= input_h_V;
        input_w_V_read_reg_1243 <= input_w_V;
        leaky_V_read_reg_1229 <= leaky_V;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_V_reg_1259 <= i_V_fu_453_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln25_reg_1255 <= icmp_ln25_fu_448_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln42_reg_1315 <= icmp_ln42_fu_577_p2;
        icmp_ln42_reg_1315_pp1_iter1_reg <= icmp_ln42_reg_1315;
        icmp_ln42_reg_1315_pp1_iter2_reg <= icmp_ln42_reg_1315_pp1_iter1_reg;
        tmp_last_V_reg_1371_pp1_iter1_reg <= tmp_last_V_reg_1371;
        tmp_last_V_reg_1371_pp1_iter2_reg <= tmp_last_V_reg_1371_pp1_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        input_ch_idx_reg_1456 <= input_ch_idx_fu_1195_p2;
        select_ln42_reg_1381 <= select_ln42_fu_740_p3;
        select_ln45_1_reg_1461 <= select_ln45_1_fu_1200_p3;
        select_ln45_reg_1386 <= select_ln45_fu_746_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mul_ln1354_reg_1282 <= mul_ln1354_fu_512_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        output_acc_2_V_reg_1426 <= output_acc_2_V_fu_1077_p3;
        output_acc_3_V_reg_1431 <= output_acc_3_V_fu_1167_p3;
        tmp_dest_V_reg_1411 <= inStream_a_TDEST_int;
        tmp_id_V_reg_1406 <= inStream_a_TID_int;
        tmp_keep_V_reg_1391 <= inStream_a_TKEEP_int;
        tmp_strb_V_reg_1396 <= inStream_a_TSTRB_int;
        tmp_user_V_reg_1401 <= inStream_a_TUSER_int;
    end
end

always @ (posedge ap_clk) begin
    if (((bias_en_V_read_reg_1223 == 1'd1) & (icmp_ln25_fu_448_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ret_V_reg_1264[5 : 2] <= ret_V_fu_459_p3[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_1315_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        tmp_data_sub_data_0_s_reg_1476 <= grp_post_process_unit_fu_395_ap_return;
        tmp_data_sub_data_1_1_reg_1481 <= grp_post_process_unit_fu_404_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((bias_en_V_read_reg_1223 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_data_sub_data_2_s_reg_1272 <= {{inStream_b_TDATA_int[47:32]}};
        tmp_data_sub_data_3_s_reg_1277 <= {{inStream_b_TDATA_int[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        tmp_dest_V_reg_1411_pp1_iter1_reg <= tmp_dest_V_reg_1411;
        tmp_id_V_reg_1406_pp1_iter1_reg <= tmp_id_V_reg_1406;
        tmp_keep_V_reg_1391_pp1_iter1_reg <= tmp_keep_V_reg_1391;
        tmp_strb_V_reg_1396_pp1_iter1_reg <= tmp_strb_V_reg_1396;
        tmp_user_V_reg_1401_pp1_iter1_reg <= tmp_user_V_reg_1401;
    end
end

always @ (*) begin
    if ((icmp_ln25_fu_448_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln42_fu_577_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (regslice_both_outStream_V_data_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_i_op_assign_1_phi_fu_377_p4 = select_ln45_reg_1386;
    end else begin
        ap_phi_mux_i_op_assign_1_phi_fu_377_p4 = i_op_assign_1_reg_373;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_i_op_assign_2_phi_fu_388_p4 = input_ch_idx_reg_1456;
    end else begin
        ap_phi_mux_i_op_assign_2_phi_fu_388_p4 = i_op_assign_2_reg_384;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_i_op_assign_phi_fu_354_p4 = select_ln42_reg_1381;
    end else begin
        ap_phi_mux_i_op_assign_phi_fu_354_p4 = i_op_assign_reg_350;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_indvar_flatten17_phi_fu_343_p4 = add_ln42_reg_1319;
    end else begin
        ap_phi_mux_indvar_flatten17_phi_fu_343_p4 = indvar_flatten17_reg_339;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_indvar_flatten_phi_fu_366_p4 = select_ln45_1_reg_1461;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_366_p4 = indvar_flatten_reg_362;
    end
end

always @ (*) begin
    if (((icmp_ln25_reg_1255 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_t_V_phi_fu_332_p4 = i_V_reg_1259;
    end else begin
        ap_phi_mux_t_V_phi_fu_332_p4 = t_V_reg_328;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (regslice_both_outStream_V_data_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001_ignoreCallOp222) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage0_11001_ignoreCallOp235) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        grp_post_process_unit_fu_395_ap_ce = 1'b1;
    end else begin
        grp_post_process_unit_fu_395_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln42_reg_1315 == 1'd0)) begin
        if ((1'b1 == ap_condition_488)) begin
            grp_post_process_unit_fu_395_data_in_V = output_acc_2_V_reg_1426;
        end else if ((1'b1 == ap_condition_75)) begin
            grp_post_process_unit_fu_395_data_in_V = output_acc_0_V_fu_895_p3;
        end else begin
            grp_post_process_unit_fu_395_data_in_V = 'bx;
        end
    end else begin
        grp_post_process_unit_fu_395_data_in_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage1_11001_ignoreCallOp224) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage0_11001_ignoreCallOp236) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        grp_post_process_unit_fu_404_ap_ce = 1'b1;
    end else begin
        grp_post_process_unit_fu_404_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln42_reg_1315 == 1'd0)) begin
        if ((1'b1 == ap_condition_488)) begin
            grp_post_process_unit_fu_404_data_in_V = output_acc_3_V_reg_1431;
        end else if ((1'b1 == ap_condition_75)) begin
            grp_post_process_unit_fu_404_data_in_V = output_acc_1_V_fu_986_p3;
        end else begin
            grp_post_process_unit_fu_404_data_in_V = 'bx;
        end
    end else begin
        grp_post_process_unit_fu_404_data_in_V = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        inStream_a_TDATA_blk_n = inStream_a_TVALID_int;
    end else begin
        inStream_a_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((inStream_a_TVALID == 1'b1) & (regslice_both_inStream_a_V_data_U_ack_in == 1'b1))) begin
        inStream_a_TREADY = 1'b1;
    end else begin
        inStream_a_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        inStream_a_TREADY_int = 1'b1;
    end else begin
        inStream_a_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((((bias_en_V_read_reg_1223 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)))) begin
        inStream_b_TDATA_blk_n = inStream_b_TVALID_int;
    end else begin
        inStream_b_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((inStream_b_TVALID == 1'b1) & (regslice_both_inStream_b_V_data_U_ack_in == 1'b1))) begin
        inStream_b_TREADY = 1'b1;
    end else begin
        inStream_b_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((bias_en_V_read_reg_1223 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((icmp_ln42_reg_1315 == 1'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)))) begin
        inStream_b_TREADY_int = 1'b1;
    end else begin
        inStream_b_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        kernel_bias_fp_V_address0 = zext_ln67_fu_1180_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        kernel_bias_fp_V_address0 = zext_ln65_fu_700_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        kernel_bias_fp_V_address0 = zext_ln544_fu_492_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_fp_V_address0 = zext_ln544_2_fu_472_p1;
    end else begin
        kernel_bias_fp_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        kernel_bias_fp_V_address1 = zext_ln68_fu_1190_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        kernel_bias_fp_V_address1 = zext_ln66_fu_711_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        kernel_bias_fp_V_address1 = zext_ln544_1_fu_501_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_fp_V_address1 = zext_ln544_3_fu_482_p1;
    end else begin
        kernel_bias_fp_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        kernel_bias_fp_V_ce0 = 1'b1;
    end else begin
        kernel_bias_fp_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        kernel_bias_fp_V_ce1 = 1'b1;
    end else begin
        kernel_bias_fp_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        kernel_bias_fp_V_d0 = trunc_ln203_fu_487_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_fp_V_d0 = tmp_data_sub_data_2_s_reg_1272;
    end else begin
        kernel_bias_fp_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        kernel_bias_fp_V_d1 = {{inStream_b_TDATA_int[31:16]}};
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_bias_fp_V_d1 = tmp_data_sub_data_3_s_reg_1277;
    end else begin
        kernel_bias_fp_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((bias_en_V_read_reg_1223 == 1'd1) & (icmp_ln25_reg_1255 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((bias_en_V_read_reg_1223 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        kernel_bias_fp_V_we0 = 1'b1;
    end else begin
        kernel_bias_fp_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((bias_en_V_read_reg_1223 == 1'd1) & (icmp_ln25_reg_1255 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((bias_en_V_read_reg_1223 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        kernel_bias_fp_V_we1 = 1'b1;
    end else begin
        kernel_bias_fp_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln42_reg_1315_pp1_iter2_reg == 1'd0) & (1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((icmp_ln42_reg_1315_pp1_iter2_reg == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0)))) begin
        outStream_TDATA_blk_n = outStream_TREADY_int;
    end else begin
        outStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_1315_pp1_iter2_reg == 1'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        outStream_TVALID_int = 1'b1;
    end else begin
        outStream_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln25_fu_448_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((icmp_ln25_fu_448_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((icmp_ln42_fu_577_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((ap_enable_reg_pp1_iter2 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if ((((icmp_ln42_fu_577_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter2 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((1'b0 == ap_block_pp1_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (regslice_both_outStream_V_data_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1354_1_fu_530_p2 = ($signed(zext_ln1354_1_fu_527_p1) + $signed(10'd1023));

assign add_ln1354_fu_521_p2 = ($signed(zext_ln1354_fu_518_p1) + $signed(10'd1023));

assign add_ln42_1_fu_601_p2 = (9'd1 + ap_phi_mux_i_op_assign_phi_fu_354_p4);

assign add_ln42_fu_582_p2 = (ap_phi_mux_indvar_flatten17_phi_fu_343_p4 + 22'd1);

assign add_ln45_1_fu_734_p2 = (13'd1 + ap_phi_mux_indvar_flatten_phi_fu_366_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((bias_en_V_read_reg_1223 == 1'd1) & (inStream_b_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((bias_en_V_read_reg_1223 == 1'd1) & (inStream_b_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((1'b1 == ap_block_state13_io) & (ap_enable_reg_pp1_iter3 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_11001_ignoreCallOp235 = ((1'b1 == ap_block_state13_io) & (ap_enable_reg_pp1_iter3 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_11001_ignoreCallOp236 = ((1'b1 == ap_block_state13_io) & (ap_enable_reg_pp1_iter3 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((1'b1 == ap_block_state13_io) & (ap_enable_reg_pp1_iter3 == 1'b1));
end

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage1_01001 = ((ap_enable_reg_pp1_iter0 == 1'b1) & (((icmp_ln42_reg_1315 == 1'd0) & (inStream_b_TVALID_int == 1'b0)) | ((icmp_ln42_reg_1315 == 1'd0) & (inStream_a_TVALID_int == 1'b0))));
end

always @ (*) begin
    ap_block_pp1_stage1_11001 = (((ap_enable_reg_pp1_iter0 == 1'b1) & (((icmp_ln42_reg_1315 == 1'd0) & (inStream_b_TVALID_int == 1'b0)) | ((icmp_ln42_reg_1315 == 1'd0) & (inStream_a_TVALID_int == 1'b0)))) | ((1'b1 == ap_block_state12_io) & (ap_enable_reg_pp1_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage1_11001_ignoreCallOp222 = (((ap_enable_reg_pp1_iter0 == 1'b1) & (((icmp_ln42_reg_1315 == 1'd0) & (inStream_b_TVALID_int == 1'b0)) | ((icmp_ln42_reg_1315 == 1'd0) & (inStream_a_TVALID_int == 1'b0)))) | ((1'b1 == ap_block_state12_io) & (ap_enable_reg_pp1_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage1_11001_ignoreCallOp224 = (((ap_enable_reg_pp1_iter0 == 1'b1) & (((icmp_ln42_reg_1315 == 1'd0) & (inStream_b_TVALID_int == 1'b0)) | ((icmp_ln42_reg_1315 == 1'd0) & (inStream_a_TVALID_int == 1'b0)))) | ((1'b1 == ap_block_state12_io) & (ap_enable_reg_pp1_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage1_subdone = (((ap_enable_reg_pp1_iter0 == 1'b1) & (((icmp_ln42_reg_1315 == 1'd0) & (inStream_b_TVALID_int == 1'b0)) | ((icmp_ln42_reg_1315 == 1'd0) & (inStream_a_TVALID_int == 1'b0)))) | ((1'b1 == ap_block_state12_io) & (ap_enable_reg_pp1_iter2 == 1'b1)));
end

assign ap_block_state10_pp1_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp1_stage1_iter1_ignore_call104 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp1_stage1_iter1_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter2_ignore_call104 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter2_ignore_call99 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_io = ((icmp_ln42_reg_1315_pp1_iter2_reg == 1'd0) & (outStream_TREADY_int == 1'b0));
end

assign ap_block_state12_pp1_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage1_iter2_ignore_call104 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage1_iter2_ignore_call99 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_io = ((icmp_ln42_reg_1315_pp1_iter2_reg == 1'd0) & (outStream_TREADY_int == 1'b0));
end

assign ap_block_state13_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter3_ignore_call104 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter3_ignore_call99 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage1_iter0 = ((bias_en_V_read_reg_1223 == 1'd1) & (inStream_b_TVALID_int == 1'b0));
end

assign ap_block_state7_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter0_ignore_call104 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter0_ignore_call99 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp1_stage1_iter0 = (((icmp_ln42_reg_1315 == 1'd0) & (inStream_b_TVALID_int == 1'b0)) | ((icmp_ln42_reg_1315 == 1'd0) & (inStream_a_TVALID_int == 1'b0)));
end

always @ (*) begin
    ap_block_state8_pp1_stage1_iter0_ignore_call104 = (((icmp_ln42_reg_1315 == 1'd0) & (inStream_b_TVALID_int == 1'b0)) | ((icmp_ln42_reg_1315 == 1'd0) & (inStream_a_TVALID_int == 1'b0)));
end

always @ (*) begin
    ap_block_state8_pp1_stage1_iter0_ignore_call99 = (((icmp_ln42_reg_1315 == 1'd0) & (inStream_b_TVALID_int == 1'b0)) | ((icmp_ln42_reg_1315 == 1'd0) & (inStream_a_TVALID_int == 1'b0)));
end

assign ap_block_state9_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter1_ignore_call104 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter1_ignore_call99 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_488 = ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0));
end

always @ (*) begin
    ap_condition_75 = ((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign col_idx_fu_649_p2 = (9'd1 + select_ln1598_fu_593_p3);

assign grp_fu_417_p4 = {{inStream_b_TDATA_int[31:16]}};

assign grp_fu_428_p4 = {{inStream_b_TDATA_int[47:32]}};

assign grp_fu_438_p4 = {{inStream_b_TDATA_int[63:48]}};

assign i_V_fu_453_p2 = (ap_phi_mux_t_V_phi_fu_332_p4 + 4'd1);

assign icmp_ln25_fu_448_p2 = ((ap_phi_mux_t_V_phi_fu_332_p4 == fold_input_ch_V_read_reg_1235) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_577_p2 = ((ap_phi_mux_indvar_flatten17_phi_fu_343_p4 == mul_ln1354_1_reg_1300) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_588_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_366_p4 == mul_ln1354_reg_1282) ? 1'b1 : 1'b0);

assign icmp_ln48_1_fu_637_p2 = ((ap_phi_mux_i_op_assign_2_phi_fu_388_p4 == fold_input_ch_V_read_reg_1235) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_548_p2 = ((fold_input_ch_V_read_reg_1235 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln75_1_fu_566_p2 = ((zext_ln48_fu_562_p1 != add_ln1354_reg_1288) ? 1'b1 : 1'b0);

assign icmp_ln75_2_fu_557_p2 = ((zext_ln45_fu_553_p1 != add_ln1354_1_reg_1294) ? 1'b1 : 1'b0);

assign icmp_ln75_3_fu_542_p2 = ((add_ln1354_fu_521_p2 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln75_4_fu_611_p2 = ((zext_ln45_1_fu_607_p1 != add_ln1354_1_reg_1294) ? 1'b1 : 1'b0);

assign icmp_ln75_5_fu_673_p2 = ((zext_ln48_1_fu_669_p1 != add_ln1354_reg_1288) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_716_p2 = ((select_ln1598_4_fu_661_p3 != 4'd7) ? 1'b1 : 1'b0);

assign input_ch_idx_fu_1195_p2 = (4'd1 + select_ln1598_4_reg_1350);

assign lhs_V_1_fu_904_p1 = p_Val2_4_fu_779_p4;

assign lhs_V_2_fu_995_p1 = p_Val2_8_fu_789_p4;

assign lhs_V_3_fu_1085_p1 = p_Val2_13_fu_799_p4;

assign lhs_V_fu_813_p1 = p_Val2_s_fu_775_p1;

assign mul_ln1354_1_fu_1217_p0 = mul_ln1354_1_fu_1217_p00;

assign mul_ln1354_1_fu_1217_p00 = mul_ln1354_reg_1282;

assign mul_ln1354_1_fu_1217_p1 = mul_ln1354_1_fu_1217_p10;

assign mul_ln1354_1_fu_1217_p10 = input_h_V_read_reg_1249;

assign mul_ln1354_fu_512_p0 = mul_ln1354_fu_512_p00;

assign mul_ln1354_fu_512_p00 = fold_input_ch_V_read_reg_1235;

assign mul_ln1354_fu_512_p1 = mul_ln1354_fu_512_p10;

assign mul_ln1354_fu_512_p10 = input_w_V_read_reg_1243;

assign mul_ln1354_fu_512_p2 = (mul_ln1354_fu_512_p0 * mul_ln1354_fu_512_p1);

assign or_ln1598_fu_655_p2 = (select_ln1598_3_fu_642_p3 | icmp_ln45_fu_588_p2);

assign or_ln340_1_fu_964_p2 = (xor_ln340_1_fu_958_p2 | p_Result_3_fu_932_p3);

assign or_ln340_2_fu_1055_p2 = (xor_ln340_2_fu_1049_p2 | p_Result_5_fu_1023_p3);

assign or_ln340_3_fu_1145_p2 = (xor_ln340_3_fu_1139_p2 | p_Result_7_fu_1113_p3);

assign or_ln340_fu_873_p2 = (xor_ln340_fu_867_p2 | p_Result_1_fu_841_p3);

assign or_ln66_fu_705_p2 = (shl_ln_fu_692_p3 | 6'd1);

assign or_ln67_fu_1175_p2 = (shl_ln_reg_1355 | 6'd2);

assign or_ln68_fu_1185_p2 = (shl_ln_reg_1355 | 6'd3);

assign or_ln75_1_fu_722_p2 = (select_ln1598_5_fu_684_p3 | icmp_ln75_fu_716_p2);

assign or_ln75_2_fu_624_p2 = (icmp_ln75_4_fu_611_p2 | icmp_ln75_3_reg_1305);

assign or_ln75_3_fu_678_p2 = (select_ln1598_1_fu_616_p3 | icmp_ln75_5_fu_673_p2);

assign or_ln75_fu_571_p2 = (icmp_ln75_2_fu_557_p2 | icmp_ln75_1_fu_566_p2);

assign outStream_TDATA_int = {{{{grp_post_process_unit_fu_404_ap_return}, {grp_post_process_unit_fu_395_ap_return}}, {tmp_data_sub_data_1_1_reg_1481}}, {tmp_data_sub_data_0_s_reg_1476}};

assign outStream_TVALID = regslice_both_outStream_V_data_U_vld_out;

assign output_acc_0_V_fu_895_p3 = ((or_ln340_fu_873_p2[0:0] === 1'b1) ? select_ln340_fu_879_p3 : select_ln388_fu_887_p3);

assign output_acc_1_V_fu_986_p3 = ((or_ln340_1_fu_964_p2[0:0] === 1'b1) ? select_ln340_1_fu_970_p3 : select_ln388_1_fu_978_p3);

assign output_acc_2_V_fu_1077_p3 = ((or_ln340_2_fu_1055_p2[0:0] === 1'b1) ? select_ln340_2_fu_1061_p3 : select_ln388_2_fu_1069_p3);

assign output_acc_3_V_fu_1167_p3 = ((or_ln340_3_fu_1145_p2[0:0] === 1'b1) ? select_ln340_3_fu_1151_p3 : select_ln388_3_fu_1159_p3);

assign p_Result_1_fu_841_p3 = p_Val2_6_fu_835_p2[32'd15];

assign p_Result_2_fu_918_p3 = ret_V_9_fu_912_p2[32'd16];

assign p_Result_3_fu_932_p3 = p_Val2_10_fu_926_p2[32'd15];

assign p_Result_4_fu_1009_p3 = ret_V_10_fu_1003_p2[32'd16];

assign p_Result_5_fu_1023_p3 = p_Val2_12_fu_1017_p2[32'd15];

assign p_Result_6_fu_1099_p3 = ret_V_11_fu_1093_p2[32'd16];

assign p_Result_7_fu_1113_p3 = p_Val2_15_fu_1107_p2[32'd15];

assign p_Result_s_fu_827_p3 = ret_V_8_fu_821_p2[32'd16];

assign p_Val2_10_fu_926_p1 = grp_fu_417_p4;

assign p_Val2_10_fu_926_p2 = ($signed(p_Val2_4_fu_779_p4) + $signed(p_Val2_10_fu_926_p1));

assign p_Val2_12_fu_1017_p1 = grp_fu_428_p4;

assign p_Val2_12_fu_1017_p2 = ($signed(p_Val2_8_fu_789_p4) + $signed(p_Val2_12_fu_1017_p1));

assign p_Val2_13_fu_799_p4 = {{inStream_a_TDATA_int[63:48]}};

assign p_Val2_15_fu_1107_p1 = grp_fu_438_p4;

assign p_Val2_15_fu_1107_p2 = ($signed(p_Val2_13_fu_799_p4) + $signed(p_Val2_15_fu_1107_p1));

assign p_Val2_1_fu_809_p1 = inStream_b_TDATA_int[15:0];

assign p_Val2_4_fu_779_p4 = {{inStream_a_TDATA_int[31:16]}};

assign p_Val2_6_fu_835_p2 = ($signed(p_Val2_s_fu_775_p1) + $signed(p_Val2_1_fu_809_p1));

assign p_Val2_8_fu_789_p4 = {{inStream_a_TDATA_int[47:32]}};

assign p_Val2_s_fu_775_p1 = inStream_a_TDATA_int[15:0];

assign ret_V_10_fu_1003_p2 = ($signed(rhs_V_2_fu_999_p1) + $signed(lhs_V_2_fu_995_p1));

assign ret_V_11_fu_1093_p2 = ($signed(rhs_V_3_fu_1089_p1) + $signed(lhs_V_3_fu_1085_p1));

assign ret_V_1_fu_496_p2 = (ret_V_reg_1264 | 6'd1);

assign ret_V_2_fu_467_p2 = (ret_V_reg_1264 | 6'd2);

assign ret_V_3_fu_477_p2 = (ret_V_reg_1264 | 6'd3);

assign ret_V_8_fu_821_p2 = ($signed(rhs_V_fu_817_p1) + $signed(lhs_V_fu_813_p1));

assign ret_V_9_fu_912_p2 = ($signed(rhs_V_1_fu_908_p1) + $signed(lhs_V_1_fu_904_p1));

assign ret_V_fu_459_p3 = {{ap_phi_mux_t_V_phi_fu_332_p4}, {2'd0}};

assign rhs_V_1_fu_908_p0 = grp_fu_417_p4;

assign rhs_V_1_fu_908_p1 = rhs_V_1_fu_908_p0;

assign rhs_V_2_fu_999_p0 = grp_fu_428_p4;

assign rhs_V_2_fu_999_p1 = rhs_V_2_fu_999_p0;

assign rhs_V_3_fu_1089_p0 = grp_fu_438_p4;

assign rhs_V_3_fu_1089_p1 = rhs_V_3_fu_1089_p0;

assign rhs_V_fu_817_p1 = p_Val2_1_fu_809_p1;

assign select_ln1598_1_fu_616_p3 = ((icmp_ln45_fu_588_p2[0:0] === 1'b1) ? icmp_ln75_4_fu_611_p2 : icmp_ln75_2_fu_557_p2);

assign select_ln1598_2_fu_629_p3 = ((icmp_ln45_fu_588_p2[0:0] === 1'b1) ? or_ln75_2_fu_624_p2 : or_ln75_fu_571_p2);

assign select_ln1598_3_fu_642_p3 = ((icmp_ln45_fu_588_p2[0:0] === 1'b1) ? icmp_ln48_reg_1310 : icmp_ln48_1_fu_637_p2);

assign select_ln1598_4_fu_661_p3 = ((or_ln1598_fu_655_p2[0:0] === 1'b1) ? 4'd0 : ap_phi_mux_i_op_assign_2_phi_fu_388_p4);

assign select_ln1598_5_fu_684_p3 = ((select_ln1598_3_fu_642_p3[0:0] === 1'b1) ? or_ln75_3_fu_678_p2 : select_ln1598_2_fu_629_p3);

assign select_ln1598_fu_593_p3 = ((icmp_ln45_fu_588_p2[0:0] === 1'b1) ? 9'd0 : ap_phi_mux_i_op_assign_1_phi_fu_377_p4);

assign select_ln340_1_fu_970_p3 = ((xor_ln340_5_fu_952_p2[0:0] === 1'b1) ? 16'd32767 : p_Val2_10_fu_926_p2);

assign select_ln340_2_fu_1061_p3 = ((xor_ln340_6_fu_1043_p2[0:0] === 1'b1) ? 16'd32767 : p_Val2_12_fu_1017_p2);

assign select_ln340_3_fu_1151_p3 = ((xor_ln340_7_fu_1133_p2[0:0] === 1'b1) ? 16'd32767 : p_Val2_15_fu_1107_p2);

assign select_ln340_fu_879_p3 = ((xor_ln340_4_fu_861_p2[0:0] === 1'b1) ? 16'd32767 : p_Val2_6_fu_835_p2);

assign select_ln388_1_fu_978_p3 = ((underflow_1_fu_946_p2[0:0] === 1'b1) ? 16'd32768 : p_Val2_10_fu_926_p2);

assign select_ln388_2_fu_1069_p3 = ((underflow_2_fu_1037_p2[0:0] === 1'b1) ? 16'd32768 : p_Val2_12_fu_1017_p2);

assign select_ln388_3_fu_1159_p3 = ((underflow_3_fu_1127_p2[0:0] === 1'b1) ? 16'd32768 : p_Val2_15_fu_1107_p2);

assign select_ln388_fu_887_p3 = ((underflow_fu_855_p2[0:0] === 1'b1) ? 16'd32768 : p_Val2_6_fu_835_p2);

assign select_ln42_fu_740_p3 = ((icmp_ln45_reg_1324[0:0] === 1'b1) ? add_ln42_1_reg_1335 : i_op_assign_reg_350);

assign select_ln45_1_fu_1200_p3 = ((icmp_ln45_reg_1324[0:0] === 1'b1) ? 13'd1 : add_ln45_1_reg_1376);

assign select_ln45_fu_746_p3 = ((select_ln1598_3_reg_1340[0:0] === 1'b1) ? col_idx_reg_1345 : select_ln1598_reg_1330);

assign shl_ln_fu_692_p3 = {{select_ln1598_4_fu_661_p3}, {2'd0}};

assign tmp_last_V_fu_728_p2 = (or_ln75_1_fu_722_p2 ^ 1'd1);

assign trunc_ln203_fu_487_p1 = inStream_b_TDATA_int[15:0];

assign underflow_1_fu_946_p2 = (xor_ln786_1_fu_940_p2 & p_Result_2_fu_918_p3);

assign underflow_2_fu_1037_p2 = (xor_ln786_2_fu_1031_p2 & p_Result_4_fu_1009_p3);

assign underflow_3_fu_1127_p2 = (xor_ln786_3_fu_1121_p2 & p_Result_6_fu_1099_p3);

assign underflow_fu_855_p2 = (xor_ln786_fu_849_p2 & p_Result_s_fu_827_p3);

assign xor_ln340_1_fu_958_p2 = (p_Result_2_fu_918_p3 ^ 1'd1);

assign xor_ln340_2_fu_1049_p2 = (p_Result_4_fu_1009_p3 ^ 1'd1);

assign xor_ln340_3_fu_1139_p2 = (p_Result_6_fu_1099_p3 ^ 1'd1);

assign xor_ln340_4_fu_861_p2 = (p_Result_s_fu_827_p3 ^ p_Result_1_fu_841_p3);

assign xor_ln340_5_fu_952_p2 = (p_Result_3_fu_932_p3 ^ p_Result_2_fu_918_p3);

assign xor_ln340_6_fu_1043_p2 = (p_Result_5_fu_1023_p3 ^ p_Result_4_fu_1009_p3);

assign xor_ln340_7_fu_1133_p2 = (p_Result_7_fu_1113_p3 ^ p_Result_6_fu_1099_p3);

assign xor_ln340_fu_867_p2 = (p_Result_s_fu_827_p3 ^ 1'd1);

assign xor_ln786_1_fu_940_p2 = (p_Result_3_fu_932_p3 ^ 1'd1);

assign xor_ln786_2_fu_1031_p2 = (p_Result_5_fu_1023_p3 ^ 1'd1);

assign xor_ln786_3_fu_1121_p2 = (p_Result_7_fu_1113_p3 ^ 1'd1);

assign xor_ln786_fu_849_p2 = (p_Result_1_fu_841_p3 ^ 1'd1);

assign zext_ln1354_1_fu_527_p1 = input_h_V_read_reg_1249;

assign zext_ln1354_fu_518_p1 = input_w_V_read_reg_1243;

assign zext_ln45_1_fu_607_p1 = add_ln42_1_fu_601_p2;

assign zext_ln45_fu_553_p1 = ap_phi_mux_i_op_assign_phi_fu_354_p4;

assign zext_ln48_1_fu_669_p1 = col_idx_fu_649_p2;

assign zext_ln48_fu_562_p1 = ap_phi_mux_i_op_assign_1_phi_fu_377_p4;

assign zext_ln544_1_fu_501_p1 = ret_V_1_fu_496_p2;

assign zext_ln544_2_fu_472_p1 = ret_V_2_fu_467_p2;

assign zext_ln544_3_fu_482_p1 = ret_V_3_fu_477_p2;

assign zext_ln544_fu_492_p1 = ret_V_reg_1264;

assign zext_ln65_fu_700_p1 = shl_ln_fu_692_p3;

assign zext_ln66_fu_711_p1 = or_ln66_fu_705_p2;

assign zext_ln67_fu_1180_p1 = or_ln67_fu_1175_p2;

assign zext_ln68_fu_1190_p1 = or_ln68_fu_1185_p2;

always @ (posedge ap_clk) begin
    ret_V_reg_1264[1:0] <= 2'b00;
    shl_ln_reg_1355[1:0] <= 2'b00;
end

endmodule //yolo_acc_top
