// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="yolo_upsamp_top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.211500,HLS_SYN_LAT=5444,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=2,HLS_SYN_FF=541,HLS_SYN_LUT=1022,HLS_VERSION=2019_2}" *)

module yolo_upsamp_top (
        ap_clk,
        ap_rst_n,
        inStream_TDATA,
        inStream_TVALID,
        inStream_TREADY,
        inStream_TKEEP,
        inStream_TSTRB,
        inStream_TUSER,
        inStream_TLAST,
        inStream_TID,
        inStream_TDEST,
        outStream_TDATA,
        outStream_TVALID,
        outStream_TREADY,
        outStream_TKEEP,
        outStream_TSTRB,
        outStream_TUSER,
        outStream_TLAST,
        outStream_TID,
        outStream_TDEST,
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_pp0_stage0 = 7'd32;
parameter    ap_ST_fsm_state10 = 7'd64;
parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] inStream_TDATA;
input   inStream_TVALID;
output   inStream_TREADY;
input  [7:0] inStream_TKEEP;
input  [7:0] inStream_TSTRB;
input  [1:0] inStream_TUSER;
input  [0:0] inStream_TLAST;
input  [4:0] inStream_TID;
input  [5:0] inStream_TDEST;
output  [63:0] outStream_TDATA;
output   outStream_TVALID;
input   outStream_TREADY;
output  [7:0] outStream_TKEEP;
output  [7:0] outStream_TSTRB;
output  [1:0] outStream_TUSER;
output  [0:0] outStream_TLAST;
output  [4:0] outStream_TID;
output  [5:0] outStream_TDEST;
input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
output   interrupt;

reg inStream_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg    inStream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln15_fu_636_p2;
wire   [0:0] select_ln21_1_fu_956_p3;
reg    outStream_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln15_reg_1311;
reg   [0:0] icmp_ln15_reg_1311_pp0_iter1_reg;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] icmp_ln15_reg_1311_pp0_iter2_reg;
reg   [12:0] indvar_flatten136_reg_387;
reg   [3:0] row_idx_0_reg_398;
reg   [9:0] indvar_flatten72_reg_409;
reg   [1:0] row_stride_0_reg_420;
reg   [8:0] indvar_flatten27_reg_431;
reg   [3:0] col_assign_reg_442;
reg   [5:0] indvar_flatten_reg_453;
reg   [1:0] col_stride_0_reg_464;
reg   [3:0] input_ch_idx_0_reg_475;
wire   [2:0] add_ln9_fu_526_p2;
wire    ap_CS_fsm_state2;
wire   [6:0] add_ln627_fu_532_p2;
wire   [2:0] add_ln10_fu_544_p2;
wire    ap_CS_fsm_state3;
wire   [6:0] add_ln627_1_fu_550_p2;
wire   [2:0] add_ln11_fu_562_p2;
wire    ap_CS_fsm_state4;
wire   [6:0] add_ln627_2_fu_568_p2;
wire   [2:0] add_ln12_fu_580_p2;
wire    ap_CS_fsm_state5;
wire   [6:0] add_ln627_3_fu_586_p2;
wire   [0:0] icmp_ln12_fu_592_p2;
reg    ap_predicate_op151_read_state6;
reg    ap_block_state6_pp0_stage0_iter0;
wire    ap_block_state7_pp0_stage0_iter1;
wire    ap_block_state8_pp0_stage0_iter2;
reg    ap_block_state8_io;
wire    ap_block_state9_pp0_stage0_iter3;
reg    ap_block_state9_io;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] add_ln15_fu_642_p2;
wire   [0:0] xor_ln52_fu_682_p2;
reg   [0:0] xor_ln52_reg_1320;
wire   [0:0] icmp_ln52_5_fu_700_p2;
reg   [0:0] icmp_ln52_5_reg_1325;
wire   [3:0] select_ln15_fu_754_p3;
wire   [0:0] select_ln17_2_fu_806_p3;
reg   [0:0] select_ln17_2_reg_1335;
wire   [0:0] or_ln17_1_fu_820_p2;
reg   [0:0] or_ln17_1_reg_1340;
wire   [0:0] and_ln17_3_fu_846_p2;
reg   [0:0] and_ln17_3_reg_1345;
wire   [1:0] select_ln17_4_fu_852_p3;
wire   [3:0] col_idx_fu_860_p2;
reg   [3:0] col_idx_reg_1355;
wire   [3:0] select_ln52_4_fu_886_p3;
reg   [3:0] select_ln52_4_reg_1360;
wire   [3:0] select_ln21_fu_938_p3;
reg   [3:0] select_ln21_reg_1366;
reg   [0:0] select_ln21_1_reg_1372;
reg   [0:0] select_ln21_1_reg_1372_pp0_iter1_reg;
wire   [0:0] select_ln21_2_fu_970_p3;
reg   [0:0] select_ln21_2_reg_1376;
wire   [1:0] select_ln21_3_fu_978_p3;
reg   [7:0] tmp_keep_V_4_reg_1386;
reg   [7:0] tmp_strb_V_4_reg_1391;
reg   [1:0] tmp_user_V_4_reg_1396;
reg   [4:0] tmp_id_V_4_reg_1401;
reg   [5:0] tmp_dest_V_4_reg_1406;
wire   [15:0] curr_input_data_sub_s_fu_1010_p1;
reg   [15:0] curr_input_data_sub_s_reg_1411;
reg   [15:0] curr_input_data_sub_1_reg_1417;
reg   [15:0] curr_input_data_sub_2_reg_1423;
reg   [15:0] curr_input_data_sub_3_reg_1429;
wire   [0:0] icmp_ln52_4_fu_1044_p2;
reg   [0:0] icmp_ln52_4_reg_1435;
wire   [3:0] input_ch_idx_fu_1050_p2;
wire   [5:0] select_ln21_4_fu_1062_p3;
wire   [8:0] select_ln19_fu_1076_p3;
wire   [9:0] select_ln17_5_fu_1090_p3;
wire   [0:0] curr_output_last_V_fu_1172_p2;
reg   [0:0] curr_output_last_V_reg_1480;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state6;
reg    ap_enable_reg_pp0_iter1;
reg   [6:0] line_buff_group_0_va_address0;
reg    line_buff_group_0_va_ce0;
reg    line_buff_group_0_va_we0;
wire   [15:0] line_buff_group_0_va_q0;
reg   [6:0] line_buff_group_1_va_address0;
reg    line_buff_group_1_va_ce0;
reg    line_buff_group_1_va_we0;
wire   [15:0] line_buff_group_1_va_q0;
reg   [6:0] line_buff_group_2_va_address0;
reg    line_buff_group_2_va_ce0;
reg    line_buff_group_2_va_we0;
wire   [15:0] line_buff_group_2_va_q0;
reg   [6:0] line_buff_group_3_va_address0;
reg    line_buff_group_3_va_ce0;
reg    line_buff_group_3_va_we0;
wire   [15:0] line_buff_group_3_va_q0;
reg   [2:0] phi_ln9_reg_299;
wire   [0:0] icmp_ln9_fu_538_p2;
reg   [6:0] phi_mul_reg_310;
reg   [2:0] phi_ln10_reg_321;
wire   [0:0] icmp_ln10_fu_556_p2;
reg   [6:0] phi_mul153_reg_332;
reg   [2:0] phi_ln11_reg_343;
wire   [0:0] icmp_ln11_fu_574_p2;
reg   [6:0] phi_mul155_reg_354;
reg   [2:0] phi_ln12_reg_365;
reg   [6:0] phi_mul157_reg_376;
reg   [3:0] ap_phi_mux_col_assign_phi_fu_446_p4;
reg   [15:0] ap_phi_mux_tmp_data_sub_data_0_s_phi_fu_489_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_tmp_data_sub_data_0_s_reg_486;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_data_sub_data_0_s_reg_486;
reg   [15:0] ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486;
reg   [15:0] ap_phi_mux_tmp_data_sub_data_1_s_phi_fu_499_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_tmp_data_sub_data_1_s_reg_496;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_data_sub_data_1_s_reg_496;
reg   [15:0] ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496;
reg   [15:0] ap_phi_mux_tmp_data_sub_data_2_s_phi_fu_509_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_tmp_data_sub_data_2_s_reg_506;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_data_sub_data_2_s_reg_506;
reg   [15:0] ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506;
reg   [15:0] ap_phi_mux_curr_output_data_sub_3_phi_fu_519_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_curr_output_data_sub_3_reg_516;
reg   [15:0] ap_phi_reg_pp0_iter1_curr_output_data_sub_3_reg_516;
reg   [15:0] ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516;
wire  signed [63:0] sext_ln203_1_fu_1125_p1;
wire  signed [63:0] sext_ln203_fu_1155_p1;
reg   [5:0] tmp_dest_V_fu_160;
reg   [7:0] tmp_keep_V_fu_164;
reg   [7:0] tmp_strb_V_fu_168;
reg   [1:0] tmp_user_V_fu_172;
reg   [4:0] tmp_id_V_fu_176;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln52_fu_598_p2;
wire   [0:0] icmp_ln52_1_fu_608_p2;
wire   [0:0] trunc_ln21_fu_620_p1;
wire   [0:0] trunc_ln17_fu_604_p1;
wire   [0:0] icmp_ln17_fu_654_p2;
wire   [3:0] row_idx_fu_648_p2;
wire   [0:0] icmp_ln52_3_fu_668_p2;
wire   [0:0] and_ln52_fu_614_p2;
wire   [0:0] or_ln26_fu_624_p2;
wire   [0:0] icmp_ln52_2_fu_630_p2;
wire   [0:0] icmp_ln23_fu_718_p2;
wire   [0:0] icmp_ln21_fu_730_p2;
wire   [0:0] icmp_ln19_fu_742_p2;
wire   [1:0] select_ln52_fu_660_p3;
wire   [0:0] and_ln52_10_fu_748_p2;
wire   [0:0] or_ln17_fu_768_p2;
wire   [1:0] row_stride_fu_762_p2;
wire   [0:0] trunc_ln17_1_fu_782_p1;
wire   [0:0] and_ln52_3_fu_688_p2;
wire   [0:0] select_ln52_1_fu_674_p3;
wire   [0:0] icmp_ln52_6_fu_794_p2;
wire   [0:0] and_ln52_11_fu_800_p2;
wire   [0:0] and_ln52_4_fu_694_p2;
wire   [0:0] xor_ln17_fu_814_p2;
wire   [0:0] and_ln52_6_fu_706_p2;
wire   [0:0] and_ln52_7_fu_712_p2;
wire   [0:0] and_ln52_8_fu_724_p2;
wire   [0:0] and_ln52_9_fu_736_p2;
wire   [3:0] select_ln17_fu_774_p3;
wire   [0:0] or_ln52_fu_866_p2;
wire   [0:0] or_ln52_1_fu_872_p2;
wire   [0:0] select_ln17_1_fu_786_p3;
wire   [0:0] select_ln17_3_fu_826_p3;
wire   [0:0] and_ln17_1_fu_834_p2;
wire   [0:0] xor_ln52_1_fu_902_p2;
wire   [0:0] and_ln17_2_fu_840_p2;
wire   [1:0] select_ln52_2_fu_878_p3;
wire   [0:0] and_ln52_13_fu_914_p2;
wire   [0:0] or_ln21_fu_926_p2;
wire   [0:0] or_ln21_1_fu_932_p2;
wire   [1:0] col_stride_fu_920_p2;
wire   [0:0] trunc_ln21_1_fu_946_p1;
wire   [0:0] or_ln26_1_fu_950_p2;
wire   [0:0] select_ln52_5_fu_894_p3;
wire   [0:0] icmp_ln52_8_fu_964_p2;
wire   [0:0] and_ln52_12_fu_908_p2;
wire   [5:0] add_ln21_1_fu_1056_p2;
wire   [8:0] add_ln19_1_fu_1070_p2;
wire   [9:0] add_ln17_1_fu_1084_p2;
wire   [0:0] and_ln52_5_fu_1098_p2;
wire   [0:0] icmp_ln52_7_fu_1107_p2;
wire   [0:0] and_ln17_fu_1102_p2;
wire   [7:0] grp_fu_1210_p3;
wire   [7:0] grp_fu_1219_p3;
wire   [0:0] and_ln52_1_fu_1162_p2;
wire   [0:0] select_ln52_3_fu_1112_p3;
wire   [0:0] and_ln52_2_fu_1166_p2;
wire   [4:0] grp_fu_1210_p0;
wire   [3:0] grp_fu_1210_p1;
wire   [3:0] grp_fu_1210_p2;
wire   [7:0] zext_ln52_fu_1119_p1;
wire   [3:0] grp_fu_1219_p0;
wire   [4:0] grp_fu_1219_p1;
wire   [3:0] grp_fu_1219_p2;
wire    ap_CS_fsm_state10;
wire    regslice_both_outStream_V_data_U_apdone_blk;
reg   [6:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_inStream_V_data_U_apdone_blk;
wire   [63:0] inStream_TDATA_int;
wire    inStream_TVALID_int;
reg    inStream_TREADY_int;
wire    regslice_both_inStream_V_data_U_ack_in;
wire    regslice_both_inStream_V_keep_V_U_apdone_blk;
wire   [7:0] inStream_TKEEP_int;
wire    regslice_both_inStream_V_keep_V_U_vld_out;
wire    regslice_both_inStream_V_keep_V_U_ack_in;
wire    regslice_both_inStream_V_strb_V_U_apdone_blk;
wire   [7:0] inStream_TSTRB_int;
wire    regslice_both_inStream_V_strb_V_U_vld_out;
wire    regslice_both_inStream_V_strb_V_U_ack_in;
wire    regslice_both_inStream_V_user_V_U_apdone_blk;
wire   [1:0] inStream_TUSER_int;
wire    regslice_both_inStream_V_user_V_U_vld_out;
wire    regslice_both_inStream_V_user_V_U_ack_in;
wire    regslice_both_inStream_V_last_V_U_apdone_blk;
wire   [0:0] inStream_TLAST_int;
wire    regslice_both_inStream_V_last_V_U_vld_out;
wire    regslice_both_inStream_V_last_V_U_ack_in;
wire    regslice_both_inStream_V_id_V_U_apdone_blk;
wire   [4:0] inStream_TID_int;
wire    regslice_both_inStream_V_id_V_U_vld_out;
wire    regslice_both_inStream_V_id_V_U_ack_in;
wire    regslice_both_inStream_V_dest_V_U_apdone_blk;
wire   [5:0] inStream_TDEST_int;
wire    regslice_both_inStream_V_dest_V_U_vld_out;
wire    regslice_both_inStream_V_dest_V_U_ack_in;
wire   [63:0] outStream_TDATA_int;
reg    outStream_TVALID_int;
wire    outStream_TREADY_int;
wire    regslice_both_outStream_V_data_U_vld_out;
wire    regslice_both_outStream_V_keep_V_U_apdone_blk;
wire    regslice_both_outStream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_keep_V_U_vld_out;
wire    regslice_both_outStream_V_strb_V_U_apdone_blk;
wire    regslice_both_outStream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_strb_V_U_vld_out;
wire    regslice_both_outStream_V_user_V_U_apdone_blk;
wire    regslice_both_outStream_V_user_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_user_V_U_vld_out;
wire    regslice_both_outStream_V_last_V_U_apdone_blk;
wire    regslice_both_outStream_V_last_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_last_V_U_vld_out;
wire    regslice_both_outStream_V_id_V_U_apdone_blk;
wire    regslice_both_outStream_V_id_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_id_V_U_vld_out;
wire    regslice_both_outStream_V_dest_V_U_apdone_blk;
wire    regslice_both_outStream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_outStream_V_dest_V_U_vld_out;
wire   [7:0] grp_fu_1210_p10;
wire   [7:0] grp_fu_1219_p00;
reg    ap_condition_400;
reg    ap_condition_404;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

yolo_upsamp_top_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
yolo_upsamp_top_CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

yolo_upsamp_top_lbkb #(
    .DataWidth( 16 ),
    .AddressRange( 104 ),
    .AddressWidth( 7 ))
line_buff_group_0_va_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buff_group_0_va_address0),
    .ce0(line_buff_group_0_va_ce0),
    .we0(line_buff_group_0_va_we0),
    .d0(curr_input_data_sub_s_reg_1411),
    .q0(line_buff_group_0_va_q0)
);

yolo_upsamp_top_lbkb #(
    .DataWidth( 16 ),
    .AddressRange( 104 ),
    .AddressWidth( 7 ))
line_buff_group_1_va_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buff_group_1_va_address0),
    .ce0(line_buff_group_1_va_ce0),
    .we0(line_buff_group_1_va_we0),
    .d0(curr_input_data_sub_1_reg_1417),
    .q0(line_buff_group_1_va_q0)
);

yolo_upsamp_top_lbkb #(
    .DataWidth( 16 ),
    .AddressRange( 104 ),
    .AddressWidth( 7 ))
line_buff_group_2_va_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buff_group_2_va_address0),
    .ce0(line_buff_group_2_va_ce0),
    .we0(line_buff_group_2_va_we0),
    .d0(curr_input_data_sub_2_reg_1423),
    .q0(line_buff_group_2_va_q0)
);

yolo_upsamp_top_lbkb #(
    .DataWidth( 16 ),
    .AddressRange( 104 ),
    .AddressWidth( 7 ))
line_buff_group_3_va_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buff_group_3_va_address0),
    .ce0(line_buff_group_3_va_ce0),
    .we0(line_buff_group_3_va_we0),
    .d0(curr_input_data_sub_3_reg_1429),
    .q0(line_buff_group_3_va_q0)
);

yolo_upsamp_top_mfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
yolo_upsamp_top_mfYi_U1(
    .din0(grp_fu_1210_p0),
    .din1(grp_fu_1210_p1),
    .din2(grp_fu_1210_p2),
    .dout(grp_fu_1210_p3)
);

yolo_upsamp_top_mg8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
yolo_upsamp_top_mg8j_U2(
    .din0(grp_fu_1219_p0),
    .din1(grp_fu_1219_p1),
    .din2(grp_fu_1219_p2),
    .dout(grp_fu_1219_p3)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_inStream_V_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TDATA),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_data_U_ack_in),
    .data_out(inStream_TDATA_int),
    .vld_out(inStream_TVALID_int),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_data_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_inStream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TKEEP),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_keep_V_U_ack_in),
    .data_out(inStream_TKEEP_int),
    .vld_out(regslice_both_inStream_V_keep_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_inStream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TSTRB),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_strb_V_U_ack_in),
    .data_out(inStream_TSTRB_int),
    .vld_out(regslice_both_inStream_V_strb_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 2 ))
regslice_both_inStream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TUSER),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_user_V_U_ack_in),
    .data_out(inStream_TUSER_int),
    .vld_out(regslice_both_inStream_V_user_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_inStream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TLAST),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_last_V_U_ack_in),
    .data_out(inStream_TLAST_int),
    .vld_out(regslice_both_inStream_V_last_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 5 ))
regslice_both_inStream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TID),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_id_V_U_ack_in),
    .data_out(inStream_TID_int),
    .vld_out(regslice_both_inStream_V_id_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 6 ))
regslice_both_inStream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TDEST),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_V_dest_V_U_ack_in),
    .data_out(inStream_TDEST_int),
    .vld_out(regslice_both_inStream_V_dest_V_U_vld_out),
    .ack_out(inStream_TREADY_int),
    .apdone_blk(regslice_both_inStream_V_dest_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_outStream_V_data_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(outStream_TDATA_int),
    .vld_in(outStream_TVALID_int),
    .ack_in(outStream_TREADY_int),
    .data_out(outStream_TDATA),
    .vld_out(regslice_both_outStream_V_data_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_data_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_outStream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_keep_V_fu_164),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_keep_V_U_ack_in_dummy),
    .data_out(outStream_TKEEP),
    .vld_out(regslice_both_outStream_V_keep_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_outStream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_strb_V_fu_168),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_strb_V_U_ack_in_dummy),
    .data_out(outStream_TSTRB),
    .vld_out(regslice_both_outStream_V_strb_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 2 ))
regslice_both_outStream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_user_V_fu_172),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_user_V_U_ack_in_dummy),
    .data_out(outStream_TUSER),
    .vld_out(regslice_both_outStream_V_user_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_outStream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(curr_output_last_V_reg_1480),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_last_V_U_ack_in_dummy),
    .data_out(outStream_TLAST),
    .vld_out(regslice_both_outStream_V_last_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 5 ))
regslice_both_outStream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_id_V_fu_176),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_id_V_U_ack_in_dummy),
    .data_out(outStream_TID),
    .vld_out(regslice_both_outStream_V_id_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 6 ))
regslice_both_outStream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(tmp_dest_V_fu_160),
    .vld_in(outStream_TVALID_int),
    .ack_in(regslice_both_outStream_V_dest_V_U_ack_in_dummy),
    .data_out(outStream_TDEST),
    .vld_out(regslice_both_outStream_V_dest_V_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state6))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state6)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state6);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_400)) begin
        if (((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516 <= curr_input_data_sub_3_reg_1429;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516 <= ap_phi_reg_pp0_iter1_curr_output_data_sub_3_reg_516;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_400)) begin
        if (((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486 <= curr_input_data_sub_s_reg_1411;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_0_s_reg_486;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_400)) begin
        if (((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496 <= curr_input_data_sub_1_reg_1417;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_1_s_reg_496;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_400)) begin
        if (((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506 <= curr_input_data_sub_2_reg_1423;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506 <= ap_phi_reg_pp0_iter1_tmp_data_sub_data_2_s_reg_506;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
        col_assign_reg_442 <= 4'd0;
    end else if (((icmp_ln15_reg_1311 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        col_assign_reg_442 <= select_ln52_4_reg_1360;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
        col_stride_0_reg_464 <= 2'd0;
    end else if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_stride_0_reg_464 <= select_ln21_3_fu_978_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
        indvar_flatten136_reg_387 <= 13'd0;
    end else if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten136_reg_387 <= add_ln15_fu_642_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
        indvar_flatten27_reg_431 <= 9'd0;
    end else if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten27_reg_431 <= select_ln19_fu_1076_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
        indvar_flatten72_reg_409 <= 10'd0;
    end else if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten72_reg_409 <= select_ln17_5_fu_1090_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
        indvar_flatten_reg_453 <= 6'd0;
    end else if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_453 <= select_ln21_4_fu_1062_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
        input_ch_idx_0_reg_475 <= 4'd0;
    end else if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_ch_idx_0_reg_475 <= input_ch_idx_fu_1050_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln9_fu_538_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_ln10_reg_321 <= 3'd0;
    end else if (((icmp_ln10_fu_556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_ln10_reg_321 <= add_ln10_fu_544_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_fu_556_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_ln11_reg_343 <= 3'd0;
    end else if (((icmp_ln11_fu_574_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_ln11_reg_343 <= add_ln11_fu_562_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln11_fu_574_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_ln12_reg_365 <= 3'd0;
    end else if (((icmp_ln12_fu_592_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        phi_ln12_reg_365 <= add_ln12_fu_580_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln9_fu_538_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_ln9_reg_299 <= add_ln9_fu_526_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_ln9_reg_299 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln9_fu_538_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_mul153_reg_332 <= 7'd0;
    end else if (((icmp_ln10_fu_556_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_mul153_reg_332 <= add_ln627_1_fu_550_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln10_fu_556_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_mul155_reg_354 <= 7'd0;
    end else if (((icmp_ln11_fu_574_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_mul155_reg_354 <= add_ln627_2_fu_568_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln11_fu_574_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_mul157_reg_376 <= 7'd0;
    end else if (((icmp_ln12_fu_592_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        phi_mul157_reg_376 <= add_ln627_3_fu_586_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln9_fu_538_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_mul_reg_310 <= add_ln627_fu_532_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_reg_310 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
        row_idx_0_reg_398 <= 4'd0;
    end else if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_idx_0_reg_398 <= select_ln15_fu_754_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
        row_stride_0_reg_420 <= 2'd0;
    end else if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_stride_0_reg_420 <= select_ln17_4_fu_852_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln17_3_reg_1345 <= and_ln17_3_fu_846_p2;
        col_idx_reg_1355 <= col_idx_fu_860_p2;
        icmp_ln52_4_reg_1435 <= icmp_ln52_4_fu_1044_p2;
        icmp_ln52_5_reg_1325 <= icmp_ln52_5_fu_700_p2;
        or_ln17_1_reg_1340 <= or_ln17_1_fu_820_p2;
        select_ln17_2_reg_1335 <= select_ln17_2_fu_806_p3;
        select_ln21_1_reg_1372 <= select_ln21_1_fu_956_p3;
        select_ln21_2_reg_1376 <= select_ln21_2_fu_970_p3;
        select_ln21_reg_1366 <= select_ln21_fu_938_p3;
        xor_ln52_reg_1320 <= xor_ln52_fu_682_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_curr_output_data_sub_3_reg_516 <= ap_phi_reg_pp0_iter0_curr_output_data_sub_3_reg_516;
        ap_phi_reg_pp0_iter1_tmp_data_sub_data_0_s_reg_486 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_0_s_reg_486;
        ap_phi_reg_pp0_iter1_tmp_data_sub_data_1_s_reg_496 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_1_s_reg_496;
        ap_phi_reg_pp0_iter1_tmp_data_sub_data_2_s_reg_506 <= ap_phi_reg_pp0_iter0_tmp_data_sub_data_2_s_reg_506;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln21_1_fu_956_p3 == 1'd0) & (icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        curr_input_data_sub_1_reg_1417 <= {{inStream_TDATA_int[31:16]}};
        curr_input_data_sub_2_reg_1423 <= {{inStream_TDATA_int[47:32]}};
        curr_input_data_sub_3_reg_1429 <= {{inStream_TDATA_int[63:48]}};
        curr_input_data_sub_s_reg_1411 <= curr_input_data_sub_s_fu_1010_p1;
        tmp_dest_V_4_reg_1406 <= inStream_TDEST_int;
        tmp_id_V_4_reg_1401 <= inStream_TID_int;
        tmp_keep_V_4_reg_1386 <= inStream_TKEEP_int;
        tmp_strb_V_4_reg_1391 <= inStream_TSTRB_int;
        tmp_user_V_4_reg_1396 <= inStream_TUSER_int;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_reg_1311 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        curr_output_last_V_reg_1480 <= curr_output_last_V_fu_1172_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln15_reg_1311 <= icmp_ln15_fu_636_p2;
        icmp_ln15_reg_1311_pp0_iter1_reg <= icmp_ln15_reg_1311;
        select_ln21_1_reg_1372_pp0_iter1_reg <= select_ln21_1_reg_1372;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln15_reg_1311_pp0_iter2_reg <= icmp_ln15_reg_1311_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln52_4_reg_1360 <= select_ln52_4_fu_886_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        tmp_dest_V_fu_160 <= tmp_dest_V_4_reg_1406;
        tmp_id_V_fu_176 <= tmp_id_V_4_reg_1401;
        tmp_keep_V_fu_164 <= tmp_keep_V_4_reg_1386;
        tmp_strb_V_fu_168 <= tmp_strb_V_4_reg_1391;
        tmp_user_V_fu_172 <= tmp_user_V_4_reg_1396;
    end
end

always @ (*) begin
    if ((icmp_ln15_fu_636_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_outStream_V_data_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_col_assign_phi_fu_446_p4 = select_ln52_4_reg_1360;
    end else begin
        ap_phi_mux_col_assign_phi_fu_446_p4 = col_assign_reg_442;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311_pp0_iter1_reg == 1'd0) & (select_ln21_1_reg_1372_pp0_iter1_reg == 1'd1))) begin
        ap_phi_mux_curr_output_data_sub_3_phi_fu_519_p4 = line_buff_group_3_va_q0;
    end else begin
        ap_phi_mux_curr_output_data_sub_3_phi_fu_519_p4 = ap_phi_reg_pp0_iter2_curr_output_data_sub_3_reg_516;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311_pp0_iter1_reg == 1'd0) & (select_ln21_1_reg_1372_pp0_iter1_reg == 1'd1))) begin
        ap_phi_mux_tmp_data_sub_data_0_s_phi_fu_489_p4 = line_buff_group_0_va_q0;
    end else begin
        ap_phi_mux_tmp_data_sub_data_0_s_phi_fu_489_p4 = ap_phi_reg_pp0_iter2_tmp_data_sub_data_0_s_reg_486;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311_pp0_iter1_reg == 1'd0) & (select_ln21_1_reg_1372_pp0_iter1_reg == 1'd1))) begin
        ap_phi_mux_tmp_data_sub_data_1_s_phi_fu_499_p4 = line_buff_group_1_va_q0;
    end else begin
        ap_phi_mux_tmp_data_sub_data_1_s_phi_fu_499_p4 = ap_phi_reg_pp0_iter2_tmp_data_sub_data_1_s_reg_496;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311_pp0_iter1_reg == 1'd0) & (select_ln21_1_reg_1372_pp0_iter1_reg == 1'd1))) begin
        ap_phi_mux_tmp_data_sub_data_2_s_phi_fu_509_p4 = line_buff_group_2_va_q0;
    end else begin
        ap_phi_mux_tmp_data_sub_data_2_s_phi_fu_509_p4 = ap_phi_reg_pp0_iter2_tmp_data_sub_data_2_s_reg_506;
    end
end

always @ (*) begin
    if (((regslice_both_outStream_V_data_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln21_1_fu_956_p3 == 1'd0) & (icmp_ln15_fu_636_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inStream_TDATA_blk_n = inStream_TVALID_int;
    end else begin
        inStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_both_inStream_V_data_U_ack_in == 1'b1) & (inStream_TVALID == 1'b1))) begin
        inStream_TREADY = 1'b1;
    end else begin
        inStream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op151_read_state6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inStream_TREADY_int = 1'b1;
    end else begin
        inStream_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_404)) begin
        if ((select_ln21_1_reg_1372 == 1'd1)) begin
            line_buff_group_0_va_address0 = sext_ln203_fu_1155_p1;
        end else if ((select_ln21_1_reg_1372 == 1'd0)) begin
            line_buff_group_0_va_address0 = sext_ln203_1_fu_1125_p1;
        end else begin
            line_buff_group_0_va_address0 = 'bx;
        end
    end else begin
        line_buff_group_0_va_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        line_buff_group_0_va_ce0 = 1'b1;
    end else begin
        line_buff_group_0_va_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buff_group_0_va_we0 = 1'b1;
    end else begin
        line_buff_group_0_va_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_404)) begin
        if ((select_ln21_1_reg_1372 == 1'd1)) begin
            line_buff_group_1_va_address0 = sext_ln203_fu_1155_p1;
        end else if ((select_ln21_1_reg_1372 == 1'd0)) begin
            line_buff_group_1_va_address0 = sext_ln203_1_fu_1125_p1;
        end else begin
            line_buff_group_1_va_address0 = 'bx;
        end
    end else begin
        line_buff_group_1_va_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        line_buff_group_1_va_ce0 = 1'b1;
    end else begin
        line_buff_group_1_va_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buff_group_1_va_we0 = 1'b1;
    end else begin
        line_buff_group_1_va_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_404)) begin
        if ((select_ln21_1_reg_1372 == 1'd1)) begin
            line_buff_group_2_va_address0 = sext_ln203_fu_1155_p1;
        end else if ((select_ln21_1_reg_1372 == 1'd0)) begin
            line_buff_group_2_va_address0 = sext_ln203_1_fu_1125_p1;
        end else begin
            line_buff_group_2_va_address0 = 'bx;
        end
    end else begin
        line_buff_group_2_va_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        line_buff_group_2_va_ce0 = 1'b1;
    end else begin
        line_buff_group_2_va_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buff_group_2_va_we0 = 1'b1;
    end else begin
        line_buff_group_2_va_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_404)) begin
        if ((select_ln21_1_reg_1372 == 1'd1)) begin
            line_buff_group_3_va_address0 = sext_ln203_fu_1155_p1;
        end else if ((select_ln21_1_reg_1372 == 1'd0)) begin
            line_buff_group_3_va_address0 = sext_ln203_1_fu_1125_p1;
        end else begin
            line_buff_group_3_va_address0 = 'bx;
        end
    end else begin
        line_buff_group_3_va_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        line_buff_group_3_va_ce0 = 1'b1;
    end else begin
        line_buff_group_3_va_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311 == 1'd0) & (select_ln21_1_reg_1372 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buff_group_3_va_we0 = 1'b1;
    end else begin
        line_buff_group_3_va_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln15_reg_1311_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((icmp_ln15_reg_1311_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        outStream_TDATA_blk_n = outStream_TREADY_int;
    end else begin
        outStream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_1311_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        outStream_TVALID_int = 1'b1;
    end else begin
        outStream_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln9_fu_538_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln10_fu_556_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln11_fu_574_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln12_fu_592_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln15_fu_636_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((icmp_ln15_fu_636_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((regslice_both_outStream_V_data_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_fu_544_p2 = (phi_ln10_reg_321 + 3'd1);

assign add_ln11_fu_562_p2 = (phi_ln11_reg_343 + 3'd1);

assign add_ln12_fu_580_p2 = (phi_ln12_reg_365 + 3'd1);

assign add_ln15_fu_642_p2 = (13'd1 + indvar_flatten136_reg_387);

assign add_ln17_1_fu_1084_p2 = (indvar_flatten72_reg_409 + 10'd1);

assign add_ln19_1_fu_1070_p2 = (indvar_flatten27_reg_431 + 9'd1);

assign add_ln21_1_fu_1056_p2 = (indvar_flatten_reg_453 + 6'd1);

assign add_ln627_1_fu_550_p2 = (phi_mul153_reg_332 + 7'd13);

assign add_ln627_2_fu_568_p2 = (phi_mul155_reg_354 + 7'd13);

assign add_ln627_3_fu_586_p2 = (phi_mul157_reg_376 + 7'd13);

assign add_ln627_fu_532_p2 = (phi_mul_reg_310 + 7'd13);

assign add_ln9_fu_526_p2 = (phi_ln9_reg_299 + 3'd1);

assign and_ln17_1_fu_834_p2 = (or_ln17_1_fu_820_p2 & and_ln52_7_fu_712_p2);

assign and_ln17_2_fu_840_p2 = (or_ln17_1_fu_820_p2 & and_ln52_8_fu_724_p2);

assign and_ln17_3_fu_846_p2 = (or_ln17_1_fu_820_p2 & and_ln52_9_fu_736_p2);

assign and_ln17_fu_1102_p2 = (or_ln17_1_reg_1340 & and_ln52_5_fu_1098_p2);

assign and_ln52_10_fu_748_p2 = (xor_ln52_fu_682_p2 & icmp_ln19_fu_742_p2);

assign and_ln52_11_fu_800_p2 = (select_ln52_1_fu_674_p3 & icmp_ln52_6_fu_794_p2);

assign and_ln52_12_fu_908_p2 = (xor_ln52_1_fu_902_p2 & and_ln17_1_fu_834_p2);

assign and_ln52_13_fu_914_p2 = (xor_ln52_1_fu_902_p2 & and_ln17_2_fu_840_p2);

assign and_ln52_1_fu_1162_p2 = (select_ln21_2_reg_1376 & icmp_ln52_4_reg_1435);

assign and_ln52_2_fu_1166_p2 = (select_ln52_3_fu_1112_p3 & and_ln52_1_fu_1162_p2);

assign and_ln52_3_fu_688_p2 = (xor_ln52_fu_682_p2 & trunc_ln17_fu_604_p1);

assign and_ln52_4_fu_694_p2 = (xor_ln52_fu_682_p2 & and_ln52_fu_614_p2);

assign and_ln52_5_fu_1098_p2 = (xor_ln52_reg_1320 & icmp_ln52_5_reg_1325);

assign and_ln52_6_fu_706_p2 = (xor_ln52_fu_682_p2 & or_ln26_fu_624_p2);

assign and_ln52_7_fu_712_p2 = (xor_ln52_fu_682_p2 & icmp_ln52_2_fu_630_p2);

assign and_ln52_8_fu_724_p2 = (xor_ln52_fu_682_p2 & icmp_ln23_fu_718_p2);

assign and_ln52_9_fu_736_p2 = (xor_ln52_fu_682_p2 & icmp_ln21_fu_730_p2);

assign and_ln52_fu_614_p2 = (icmp_ln52_fu_598_p2 & icmp_ln52_1_fu_608_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((inStream_TVALID_int == 1'b0) & (ap_predicate_op151_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((inStream_TVALID_int == 1'b0) & (ap_predicate_op151_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((inStream_TVALID_int == 1'b0) & (ap_predicate_op151_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter0 = ((inStream_TVALID_int == 1'b0) & (ap_predicate_op151_read_state6 == 1'b1));
end

assign ap_block_state7_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((icmp_ln15_reg_1311_pp0_iter1_reg == 1'd0) & (outStream_TREADY_int == 1'b0));
end

assign ap_block_state8_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((icmp_ln15_reg_1311_pp0_iter2_reg == 1'd0) & (outStream_TREADY_int == 1'b0));
end

assign ap_block_state9_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_400 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_404 = ((icmp_ln15_reg_1311 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_curr_output_data_sub_3_reg_516 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_data_sub_data_0_s_reg_486 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_data_sub_data_1_s_reg_496 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_data_sub_data_2_s_reg_506 = 'bx;

always @ (*) begin
    ap_predicate_op151_read_state6 = ((select_ln21_1_fu_956_p3 == 1'd0) & (icmp_ln15_fu_636_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign col_idx_fu_860_p2 = (4'd1 + select_ln17_fu_774_p3);

assign col_stride_fu_920_p2 = (2'd1 + select_ln52_2_fu_878_p3);

assign curr_input_data_sub_s_fu_1010_p1 = inStream_TDATA_int[15:0];

assign curr_output_last_V_fu_1172_p2 = (select_ln17_2_reg_1335 & and_ln52_2_fu_1166_p2);

assign grp_fu_1210_p0 = 8'd13;

assign grp_fu_1210_p1 = grp_fu_1210_p10;

assign grp_fu_1210_p10 = select_ln21_reg_1366;

assign grp_fu_1210_p2 = zext_ln52_fu_1119_p1;

assign grp_fu_1219_p0 = grp_fu_1219_p00;

assign grp_fu_1219_p00 = select_ln21_reg_1366;

assign grp_fu_1219_p1 = 8'd13;

assign grp_fu_1219_p2 = zext_ln52_fu_1119_p1;

assign icmp_ln10_fu_556_p2 = ((phi_ln10_reg_321 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln11_fu_574_p2 = ((phi_ln11_reg_343 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_592_p2 = ((phi_ln12_reg_365 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_636_p2 = ((indvar_flatten136_reg_387 == 13'd5408) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_654_p2 = ((indvar_flatten72_reg_409 == 10'd416) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_742_p2 = ((indvar_flatten27_reg_431 == 9'd208) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_730_p2 = ((indvar_flatten_reg_453 == 6'd16) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_718_p2 = ((input_ch_idx_0_reg_475 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln52_1_fu_608_p2 = ((row_stride_0_reg_420 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln52_2_fu_630_p2 = ((col_stride_0_reg_464 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln52_3_fu_668_p2 = ((row_idx_fu_648_p2 == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln52_4_fu_1044_p2 = ((select_ln21_fu_938_p3 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln52_5_fu_700_p2 = ((ap_phi_mux_col_assign_phi_fu_446_p4 == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln52_6_fu_794_p2 = ((select_ln52_fu_660_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_7_fu_1107_p2 = ((col_idx_reg_1355 == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln52_8_fu_964_p2 = ((select_ln52_2_fu_878_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_598_p2 = ((row_idx_0_reg_398 == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_538_p2 = ((phi_ln9_reg_299 == 3'd7) ? 1'b1 : 1'b0);

assign input_ch_idx_fu_1050_p2 = (select_ln21_fu_938_p3 + 4'd1);

assign or_ln17_1_fu_820_p2 = (xor_ln17_fu_814_p2 | icmp_ln17_fu_654_p2);

assign or_ln17_fu_768_p2 = (icmp_ln17_fu_654_p2 | and_ln52_10_fu_748_p2);

assign or_ln21_1_fu_932_p2 = (or_ln21_fu_926_p2 | or_ln17_fu_768_p2);

assign or_ln21_fu_926_p2 = (and_ln52_13_fu_914_p2 | and_ln17_3_fu_846_p2);

assign or_ln26_1_fu_950_p2 = (trunc_ln21_1_fu_946_p1 | select_ln17_1_fu_786_p3);

assign or_ln26_fu_624_p2 = (trunc_ln21_fu_620_p1 | trunc_ln17_fu_604_p1);

assign or_ln52_1_fu_872_p2 = (or_ln52_fu_866_p2 | icmp_ln17_fu_654_p2);

assign or_ln52_fu_866_p2 = (and_ln52_10_fu_748_p2 | and_ln17_3_fu_846_p2);

assign outStream_TDATA_int = {{{{ap_phi_mux_curr_output_data_sub_3_phi_fu_519_p4}, {ap_phi_mux_tmp_data_sub_data_2_s_phi_fu_509_p4}}, {ap_phi_mux_tmp_data_sub_data_1_s_phi_fu_499_p4}}, {ap_phi_mux_tmp_data_sub_data_0_s_phi_fu_489_p4}};

assign outStream_TVALID = regslice_both_outStream_V_data_U_vld_out;

assign row_idx_fu_648_p2 = (4'd1 + row_idx_0_reg_398);

assign row_stride_fu_762_p2 = (2'd1 + select_ln52_fu_660_p3);

assign select_ln15_fu_754_p3 = ((icmp_ln17_fu_654_p2[0:0] === 1'b1) ? row_idx_fu_648_p2 : row_idx_0_reg_398);

assign select_ln17_1_fu_786_p3 = ((and_ln52_10_fu_748_p2[0:0] === 1'b1) ? trunc_ln17_1_fu_782_p1 : and_ln52_3_fu_688_p2);

assign select_ln17_2_fu_806_p3 = ((and_ln52_10_fu_748_p2[0:0] === 1'b1) ? and_ln52_11_fu_800_p2 : and_ln52_4_fu_694_p2);

assign select_ln17_3_fu_826_p3 = ((and_ln52_10_fu_748_p2[0:0] === 1'b1) ? trunc_ln17_1_fu_782_p1 : and_ln52_6_fu_706_p2);

assign select_ln17_4_fu_852_p3 = ((and_ln52_10_fu_748_p2[0:0] === 1'b1) ? row_stride_fu_762_p2 : select_ln52_fu_660_p3);

assign select_ln17_5_fu_1090_p3 = ((icmp_ln17_fu_654_p2[0:0] === 1'b1) ? 10'd1 : add_ln17_1_fu_1084_p2);

assign select_ln17_fu_774_p3 = ((or_ln17_fu_768_p2[0:0] === 1'b1) ? 4'd0 : ap_phi_mux_col_assign_phi_fu_446_p4);

assign select_ln19_fu_1076_p3 = ((or_ln17_fu_768_p2[0:0] === 1'b1) ? 9'd1 : add_ln19_1_fu_1070_p2);

assign select_ln21_1_fu_956_p3 = ((and_ln52_13_fu_914_p2[0:0] === 1'b1) ? or_ln26_1_fu_950_p2 : select_ln52_5_fu_894_p3);

assign select_ln21_2_fu_970_p3 = ((and_ln52_13_fu_914_p2[0:0] === 1'b1) ? icmp_ln52_8_fu_964_p2 : and_ln52_12_fu_908_p2);

assign select_ln21_3_fu_978_p3 = ((and_ln52_13_fu_914_p2[0:0] === 1'b1) ? col_stride_fu_920_p2 : select_ln52_2_fu_878_p3);

assign select_ln21_4_fu_1062_p3 = ((or_ln52_1_fu_872_p2[0:0] === 1'b1) ? 6'd1 : add_ln21_1_fu_1056_p2);

assign select_ln21_fu_938_p3 = ((or_ln21_1_fu_932_p2[0:0] === 1'b1) ? 4'd0 : input_ch_idx_0_reg_475);

assign select_ln52_1_fu_674_p3 = ((icmp_ln17_fu_654_p2[0:0] === 1'b1) ? icmp_ln52_3_fu_668_p2 : icmp_ln52_fu_598_p2);

assign select_ln52_2_fu_878_p3 = ((or_ln52_1_fu_872_p2[0:0] === 1'b1) ? 2'd0 : col_stride_0_reg_464);

assign select_ln52_3_fu_1112_p3 = ((and_ln17_3_reg_1345[0:0] === 1'b1) ? icmp_ln52_7_fu_1107_p2 : and_ln17_fu_1102_p2);

assign select_ln52_4_fu_886_p3 = ((and_ln17_3_fu_846_p2[0:0] === 1'b1) ? col_idx_fu_860_p2 : select_ln17_fu_774_p3);

assign select_ln52_5_fu_894_p3 = ((and_ln17_3_fu_846_p2[0:0] === 1'b1) ? select_ln17_1_fu_786_p3 : select_ln17_3_fu_826_p3);

assign select_ln52_fu_660_p3 = ((icmp_ln17_fu_654_p2[0:0] === 1'b1) ? 2'd0 : row_stride_0_reg_420);

assign sext_ln203_1_fu_1125_p1 = $signed(grp_fu_1210_p3);

assign sext_ln203_fu_1155_p1 = $signed(grp_fu_1219_p3);

assign trunc_ln17_1_fu_782_p1 = row_stride_fu_762_p2[0:0];

assign trunc_ln17_fu_604_p1 = row_stride_0_reg_420[0:0];

assign trunc_ln21_1_fu_946_p1 = col_stride_fu_920_p2[0:0];

assign trunc_ln21_fu_620_p1 = col_stride_0_reg_464[0:0];

assign xor_ln17_fu_814_p2 = (icmp_ln19_fu_742_p2 ^ 1'd1);

assign xor_ln52_1_fu_902_p2 = (1'd1 ^ and_ln17_3_fu_846_p2);

assign xor_ln52_fu_682_p2 = (icmp_ln17_fu_654_p2 ^ 1'd1);

assign zext_ln52_fu_1119_p1 = select_ln52_4_reg_1360;

endmodule //yolo_upsamp_top
